<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio Developer Edition 9.0.11.3078 (http://www.liquid-technologies.com) -->
<wsdl:definitions xmlns:tns="http://www.hauser-wenz.de/Guid/" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://schemas.xmlsoap.org/wsdl/" 
  name="Guid" 
targetNamespace="http://www.hauser-wenz.de/Guid/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <types />
    <message name="getGuidResponse">
        <part name="Result" type="xsd:string" />
    </message>
    <message name="getGuidRequest">
        <part name="prefix" type="xsd:string" />
    </message>
    <portType name="GuidPortType">
        <operation name="getGuid" parameterOrder="prefix">
            <input message="tns:getGuidRequest" />
            <output message="tns:getGuidResponse" />
        </operation>
    </portType>
    <binding name="GuidBinding" type="tns:GuidPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="getGuid">
            <soap:operation soapAction="urn:php5unleashed-guid#getGuid" />
            <input>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:php5unleashed-guid" use="encoded" />
            </input>
            <output>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:php5unleashed-guid" use="encoded" />
            </output>
        </operation>
    </binding>
    <service name="GuidService">
        <port name="GuidPort" binding="tns:GuidBinding">
            <soap:address location="http://localhost:8080/soap/guid-server.php" />
        </port>
    </service>
</wsdl:definitions>
