INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDERITEM_INVOICE', 'INVOICE_DTM.NEW', 'D', 'NOT EXISTS', 'NULL', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDERTAX_INVOICE', 'INVOICE_DTM.NEW', 'D', 'NOT EXISTS', 'NULL', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_INVOICE', 'AMOUNT_EUR', 'N', '>', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ACCOUNT_STORE', 'ACCOUNT_ID', 'N', 'IS', 'NULL', NULL);

COMMIT WORK;

