INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_INVOICE', 'AMOUNT_EUR', 'N', '>', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ACCOUNT_STORE', 'ACCOUNT_ID', 'N', 'IS', 'NULL', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ACCOUNT_DEBIT', 'AMOUNT_EUR', 'N', '>', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ACCOUNT_MANUALCREDIT', 'AMOUNT_EUR', 'N', '>', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ACCOUNT_MANUALDEBIT', 'AMOUNT_EUR', 'N', '>=', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_ANULLED', 'ACTIVEITEMSCOUNT', 'N', '=', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_CANCELLED', 'ACTIVEITEMSCOUNT', 'N', '=', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDERITEM_APPROVE', 'STATUS_SIGN', 'S', '=', 'NEW', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDERITEM_DELIVERED', 'STATUS_SIGN', 'S', '=', 'DELIVERING', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ACCOUNT_CREDIT_EUR', 'AMOUNT_EUR', 'N', '>', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDERITEM_UNCLAIM', 'STATUS_SIGN', 'S', '=', 'DELIVERING', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_EMPTY', 'ACTIVEITEMSCOUNT', 'N', '=', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_PAID', 'COST_EUR', 'N', '<=', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDERITEM_INDOUBT', 'STATUS_SIGN', 'S', 'IN', 'ACCEPTED,PREPAKED', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_PAID', 'ORDER_PAIDABLE', 'N', '=', '1', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_DISCARD', 'DISCARDCOUNT', 'N', '>', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_DISCARD', 'RETURNCOUNT', 'N', '=', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDER_HAVERETURN', 'RETURNCOUNT', 'N', '>', '0', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('MONEYBACK_CREATE', 'KIND', 'S', 'IN', 'BELPOST,BANK', NULL);
INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES ('ORDERITEM_ERROR', 'STATUS_SIGN', 'S', 'IN', 'NEW,ACCEPTREQUEST', NULL);

COMMIT WORK;

