INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (2, 'ORDER_ID', 'A', 'ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (4, 'ORDER_ID', 'A', 'ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (3, 'ORDER_ID', 'A', 'ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (5, 'ID', 'A', 'CLIENT_ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (31, 'ORDER_ID', 'A', 'ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (31, 'NEW.STATUS_SIGN', 'V', 'ACCEPTREQUEST');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (4, 'NEW.STATUS_SIGN', 'V', 'APPROVED');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (3, 'NEW.STATUS_SIGN', 'V', 'APPROVED');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (5, 'NEW.STATUS_SIGN', 'A', 'APPROVED');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (22, 'ORDER_ID', 'A', 'ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (22, 'NEW.STATUS_SIGN', 'V', 'DRAFT');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (21, 'ORDER_ID', 'A', 'ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (21, 'NEW.STATUS_SIGN', 'V', 'DRAFT');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (8, 'EVENT_SIGN', 'V', 'SMS_ORDER_CODE');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (8, 'OBJECT_ID', 'A', 'ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (30, 'AMOUNT_EUR', 'A', 'AMOUNT_EUR');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (30, 'BYR2EUR', 'A', 'BYR2EUR');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (30, 'ID', 'A', 'ID');
INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE) VALUES (30, 'ORDER_ID', 'A', 'ORDER_ID');

COMMIT WORK;

