INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES (71, 'STATUS_SIGN', 'S', '=', 'ACCEPTED', NULL);
INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES (72, 'STATUS_SIGN', 'S', '=', 'PREPACKED', NULL);
INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES (65, 'KIND', 'S', '<>', 'LEAVE', NULL);
INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES (10, 'BONUS_ID', 'N', 'IS NOT', 'NULL', NULL);

COMMIT WORK;

