INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES (10, 'BONUS_ID', 'N', 'IS NOT', 'NULL', NULL);
INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES (36, 'COST_EUR', 'N', '>', '0', NULL);
INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2) VALUES (36, 'PRODUCT_ID', 'N', '=', '2', NULL);

COMMIT WORK;

