INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (5, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (3, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (17, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (18, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (9, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (19, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (11, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (4, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (6, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (2, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (1, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (1, 'V[[:DIGIT:]]{6}(30|IX)', '[1][2][3][4][5][6][7]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (12, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (13, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (14, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (15, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (16, '[[:DIGIT:]]{6}([[:UPPER:]]|[[:DIGIT:]]{1,2})', '[1][2][3][4][5][6]');
INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK) VALUES (10, 'V[[:DIGIT:]]{6}[[:ALNUM:]]{1,2}', '[1][2][3][4][5][6][7]');

COMMIT WORK;

