INSERT INTO CALCPOINTS (CALCPOINT_ID, OBJECT_SIGN, OBJECT_STATUS_ID) VALUES (1, 'ORDER', 201);
INSERT INTO CALCPOINTS (CALCPOINT_ID, OBJECT_SIGN, OBJECT_STATUS_ID) VALUES (2, 'ORDER', 205);

COMMIT WORK;

