INSERT INTO CALCPOINTS (CALCPOINT_ID, OBJECT_SIGN, OBJECT_STATUS_ID) VALUES (1, 'ORDER', 202);
INSERT INTO CALCPOINTS (CALCPOINT_ID, OBJECT_SIGN, OBJECT_STATUS_ID) VALUES (2, 'ORDER', 210);
INSERT INTO CALCPOINTS (CALCPOINT_ID, OBJECT_SIGN, OBJECT_STATUS_ID) VALUES (3, 'ORDER', 217);
INSERT INTO CALCPOINTS (CALCPOINT_ID, OBJECT_SIGN, OBJECT_STATUS_ID) VALUES (5, 'ORDER', 291);
INSERT INTO CALCPOINTS (CALCPOINT_ID, OBJECT_SIGN, OBJECT_STATUS_ID) VALUES (4, 'ORDER', 279);

COMMIT WORK;

