INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (1, 1);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (1, 2);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (2, 1);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (2, 2);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (3, 1);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (3, 2);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (4, 1);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (4, 2);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (11, 1);
INSERT INTO CATALOG2PLUGIN (CATALOG_ID, PLUGIN_ID) VALUES (11, 2);

COMMIT WORK;

