INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 2, 'PORTION_NO', '[11][12]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 3, 'DAYNO', '[16][17][18]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 3, 'PARTNER_NUMBER', '[4][5][6][7][8][9][10][11]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 4, 'PARTNER_NUMBER', '[10][11][12][13][14][15][16][17]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 6, 'PARTNER_NUMBER', '[8][9][10][11][12][13][14][15]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 8, 'PARTNER_NUMBER', '[4][5][6][7][8][9][10][11]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 9, 'PARTNER_NUMBER', '[6][7][8][9][10][11][12][13]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 10, 'DAYNO', '[26][27][28]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 10, 'PACKLIST_NO', '[14][15][16][17][18]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 10, 'PARTNER_NUMBER', '[6][7][8][9][10][11][12][13]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 14, 'PARTNER_NUMBER', '[6][7][8][9][10][11][12][13]');
INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK) VALUES ('MESSAGE', 15, 'PARTNER_NUMBER', '[6][7][8][9][10][11][12][13]');

COMMIT WORK;

