INSERT INTO EVENTCODES (EVENT_SIGN, OBJECT_SIGN, EVENT_NAME) VALUES ('SMS_ORDER_CODE', 'ORDER', 'SMS-сообщение о присвоении номена заявки');
INSERT INTO EVENTCODES (EVENT_SIGN, OBJECT_SIGN, EVENT_NAME) VALUES ('FORM_PROTOCOL', 'MESSAGE', 'Показать протокол обработки сообщения');

COMMIT WORK;

