INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ORDER', 'Заявка', 'ORDERS', 'ORDER_ID', 'ORDER_ATTRS', 'ORDER_READ');
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ARTICLE', 'Артикул', 'ARTICLES', 'ARTICLE_ID', 'ARTICLE_ATTRS', NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ORDERITEM', 'Позиция заявки', 'ORDERITEMS', 'ORDERITEM_ID', 'ORDERITEM_ATTRS', 'ORDERITEM_READ');
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('CLIENT', 'Клиент', 'CLIENTS', 'CLIENT_ID', 'CLIENT_ATTRS', NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ADRESS', 'Адрес', 'ADRESSES', 'ADRESS_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('PLACE', 'Города', 'PLACES', 'PLACE_ID', NULL, 'PLACE_READ');
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('CATALOG', 'Каталог', 'CATALOGS', 'CATALOG_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('MAGAZINE', 'Журнал', 'MAGAZINES', 'MAGAZINE_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('EVENT', 'Событие', 'EVENTS', 'EVENT_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ARTICLECODE', 'Вариант артикула', 'ARTICLECODES', 'ARTICLECODE_ID', 'ARTICLECODE_ATTRS', NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ACTION', 'Действие', 'ACTIONS', 'ACTION_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ACCOUNT', 'Счет', 'ACCOUNTS', 'ACCOUNT_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('MESSAGE', 'Сообщение', 'MESSAGES', 'MESSAGE_ID', 'MESSAGE_ATTRS', NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('NOTIFY', 'Замечание', 'NOTIFIES', 'NOTIFY_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ARTICLESIGN', 'Группа артикулов', 'ARTICLESIGNS', 'ARTICLESIGN_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('TAXPLAN', 'Тарифный план', 'TAXPLANS', 'TAXPLAN_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('TAXSERV', 'Услуга', 'TAXSERVS', 'TAXSERV_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('TAXRATE', 'Тариф', 'TAXRATES', 'TAXRATE_ID', 'TAXRATE_ATTRS', NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('VENDOR', 'Поставщик', 'VENDORS', 'VENDOR_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('PRODUCT', 'Продукт', 'PRODUCTS', 'PRODUCT_ID', 'PRODUCT_ATTRS', NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ORDERTAX', 'Комиссия по заявке', 'ORDERTAXS', 'ORDERTAX_ID', NULL, 'ORDERTAX_READ');
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('SETTING', 'Настройки', 'SETTINGS', 'SETTING_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('INVOICE', 'Извещение', 'INVOICES', 'INVOICE_ID', 'INVOICE_ATTRS', NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('PAYMENT', 'Платежи', 'PAYMENTS', 'PAYMENT_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('ORDERMONEY', 'Платежи', 'ORDERMONEYS', 'ORDERMONEY_ID', NULL, NULL);
INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ) VALUES ('WAY', 'Направление портирования файлов', 'WAYS', 'WAY_ID', NULL, NULL);

COMMIT WORK;

