INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', '=');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', '<>');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', '>=');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', '<=');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('S', '=');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('S', 'LIKE');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('S', '<>');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', 'IS');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', 'IS NOT');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', 'BETWEEN_[]');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', 'BETWEEN_[)');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', 'NOT EXISTS');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', 'BETWEEN_(]');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', 'BETWEEN_()');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('S', 'NOT EXISTS');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('D', 'NOT EXISTS');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('L', 'NOT EXISTS');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', '<');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('N', '>');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('S', 'IN');
INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION) VALUES ('S', 'NOT IN');

COMMIT WORK;

