INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('V', 'Значение', 0, 1);
INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('A', 'Параметр', 0, 2);
INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('O', 'Output параметр', 1, 1);
INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('I', 'Input параметр', 0, 0);
INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('B', 'Объект', 0, 10);
INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('X', 'Процедура', 0, 9);
INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('P', 'Пул параметров', 0, 8);
INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('Y', 'Процедура', 1, 9);
INSERT INTO PARAMKINDS (PARAM_KIND, PARAMKIND_NAME, IS_OUTPUT, ORDER_NO) VALUES ('W', 'Записать в атрибуты дейсвия', 1, 2);

COMMIT WORK;

