INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (29, 2);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (33, 2);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (25, 2);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (44, 2);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (17, 1);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (163, 1);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (162, 1);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (1643, 1);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (2131, 1);
INSERT INTO PHONEPREFIXES (PHONEPREFIX_CODE, PHONETYPE_CODE) VALUES (2153, 1);

COMMIT WORK;

