INSERT INTO PLACETYPES (PLACETYPE_CODE, PLACETYPE_NAME, ADRTYPE_SHORT, PLACETYPE_SIGN) VALUES (1, 'Страна', 'Республика', 'Республика');
INSERT INTO PLACETYPES (PLACETYPE_CODE, PLACETYPE_NAME, ADRTYPE_SHORT, PLACETYPE_SIGN) VALUES (2, 'Область', 'обл', 'обл');
INSERT INTO PLACETYPES (PLACETYPE_CODE, PLACETYPE_NAME, ADRTYPE_SHORT, PLACETYPE_SIGN) VALUES (3, 'Район', 'р-н', 'р-н');
INSERT INTO PLACETYPES (PLACETYPE_CODE, PLACETYPE_NAME, ADRTYPE_SHORT, PLACETYPE_SIGN) VALUES (4, 'Город', 'г', 'г');
INSERT INTO PLACETYPES (PLACETYPE_CODE, PLACETYPE_NAME, ADRTYPE_SHORT, PLACETYPE_SIGN) VALUES (5, 'Городской поселок', 'гп', 'гп');
INSERT INTO PLACETYPES (PLACETYPE_CODE, PLACETYPE_NAME, ADRTYPE_SHORT, PLACETYPE_SIGN) VALUES (6, 'Поселок', 'пос', 'пос');
INSERT INTO PLACETYPES (PLACETYPE_CODE, PLACETYPE_NAME, ADRTYPE_SHORT, PLACETYPE_SIGN) VALUES (7, 'Деревня', 'дер', 'дер');
INSERT INTO PLACETYPES (PLACETYPE_CODE, PLACETYPE_NAME, ADRTYPE_SHORT, PLACETYPE_SIGN) VALUES (8, 'Военная часть', 'вч', 'вч');

COMMIT WORK;

