INSERT INTO PLUGINS (PLUGIN_ID, PLUGIN_NAME, PLUGIN_SIGN) VALUES (1, 'otto. Проверка доступности', 'OTTO_CHECK_AVAILABLE');
INSERT INTO PLUGINS (PLUGIN_ID, PLUGIN_NAME, PLUGIN_SIGN) VALUES (2, 'otto. Информация по артикулам', 'OTTO_GET_ARTICLE');

COMMIT WORK;

