INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID) VALUES (1, 1);
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID) VALUES (2, 1);
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID) VALUES (3, 1);
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID) VALUES (4, 1);

COMMIT WORK;

