INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (1, 1, '/httpdocs/orders/73105061', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (1, 1, '/httpdocs/orders/73105050', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (2, 1, '/htdocs/orders/73105061', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (2, 1, '/htdocs/orders/73105061', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (3, 3, '/out', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (3, 4, '/out', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (3, 6, '/out', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (3, 8, '/out', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (3, 9, '/out', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (4, 1, '/www/postcatalog.by/orders/73105050', 'Messages\In');
INSERT INTO PORT2TEMPLATE (PORT_ID, TEMPLATE_ID, SOURCE_PATH, DEST_PATH) VALUES (4, 1, '/www/postcatalog.by/orders/73105061', 'Messages\In');

COMMIT WORK;

