INSERT INTO PRODUCT2TAXPLAN (PRODUCT_ID, TAXPLAN_ID) VALUES (1, 1);
INSERT INTO PRODUCT2TAXPLAN (PRODUCT_ID, TAXPLAN_ID) VALUES (1, 2);
INSERT INTO PRODUCT2TAXPLAN (PRODUCT_ID, TAXPLAN_ID) VALUES (2, 3);
INSERT INTO PRODUCT2TAXPLAN (PRODUCT_ID, TAXPLAN_ID) VALUES (2, 4);
INSERT INTO PRODUCT2TAXPLAN (PRODUCT_ID, TAXPLAN_ID) VALUES (3, 5);
INSERT INTO PRODUCT2TAXPLAN (PRODUCT_ID, TAXPLAN_ID) VALUES (3, 6);

COMMIT WORK;

