INSERT INTO PRODUCT_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (1, 1501, '73105061');
INSERT INTO PRODUCT_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (2, 1501, '73105050');
INSERT INTO PRODUCT_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (1, 1502, 'CZ');
INSERT INTO PRODUCT_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (2, 1502, 'CY');
INSERT INTO PRODUCT_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (3, 1501, '81500000');
INSERT INTO PRODUCT_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (3, 1502, 'RR');

COMMIT WORK;

