INSERT INTO SETTINGSIGNS (SETTING_SIGN, SETTING_NAME, DATATYPE_SIGN) VALUES ('BYR2EUR', 'Курс пересчета BYR->EUR', 'I');
INSERT INTO SETTINGSIGNS (SETTING_SIGN, SETTING_NAME, DATATYPE_SIGN) VALUES ('TAXFREE_COST', 'Беспошлинный лимит', 'I');

COMMIT WORK;

