INSERT INTO SETTINGSIGNS (SETTING_SIGN, SETTING_NAME, DATATYPE_SIGN) VALUES ('BYR2EUR', 'Курс пересчета BYR->EUR', 'I');
INSERT INTO SETTINGSIGNS (SETTING_SIGN, SETTING_NAME, DATATYPE_SIGN) VALUES ('TAXFREE_COST', 'Беспошлинный лимит', 'I');
INSERT INTO SETTINGSIGNS (SETTING_SIGN, SETTING_NAME, DATATYPE_SIGN) VALUES ('BELPOST_FEE', 'Комиссия БелПочты', 'I');
INSERT INTO SETTINGSIGNS (SETTING_SIGN, SETTING_NAME, DATATYPE_SIGN) VALUES ('BANK_FEE', 'Комиссия при банковском переводе', 'I');
INSERT INTO SETTINGSIGNS (SETTING_SIGN, SETTING_NAME, DATATYPE_SIGN) VALUES ('NDS_FEE', 'НДС', 'I');

COMMIT WORK;

