INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (1, 'Улица', 'ул', 1, 'ул');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (2, 'Проспект', 'п-т', NULL, 'п-т');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (3, 'Переулок', 'пер', NULL, 'пер');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (4, 'Проезд', 'пр-д', NULL, 'пр-д');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (5, 'Микрорайон', 'м-н', NULL, 'м-н');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (6, 'Тракт', 'тр-т', NULL, 'тр-т');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (7, 'Площадь', 'пл', NULL, 'пл');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (8, 'Бульвар', 'б-р', NULL, 'б-р');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (9, 'Шоссе', 'ш', NULL, 'ш');
INSERT INTO STREETTYPES (STREETTYPE_CODE, STREETTYPE_NAME, STREETTYPE_SHORT, IS_DEFAULT, STREETTYPE_SIGN) VALUES (10, 'Павильон', 'пав', NULL, 'пав');

COMMIT WORK;

