INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (1, 1, 1, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (3, 1, 2, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (2, 2, 1, 'TAX_WEIGHT', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (4, 2, 2, 'TAX_WEIGHT', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (5, 1, 3, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (6, 3, 3, 'TAX_WEIGHT', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (7, 1, 4, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (8, 3, 4, 'TAX_WEIGHT', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (9, 4, 3, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (10, 4, 4, 'TAX_FIXED_SUM', 131);

COMMIT WORK;

