INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (1, 1, 1, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (3, 1, 2, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (2, 3, 1, 'TAX_WEIGHT', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (4, 3, 2, 'TAX_WEIGHT', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (5, 1, 3, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (6, 3, 3, 'TAX_WEIGHT', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (7, 1, 4, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (8, 3, 4, 'TAX_WEIGHT', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (9, 4, 3, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (10, 4, 4, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (11, 4, 1, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (12, 4, 2, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (14, 5, 3, 'TAX_ENTERED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (15, 5, 4, 'TAX_ENTERED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (21, 6, 1, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (22, 7, 1, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (23, 8, 1, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (16, 9, 1, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (17, 9, 2, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (18, 9, 3, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (19, 9, 4, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (31, 1, 5, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (41, 1, 6, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (32, 4, 5, 'TAX_FIXED_SUM', 131);
INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID) VALUES (42, 4, 6, 'TAX_FIXED_SUM', 131);

COMMIT WORK;

