INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (1, 1301, '7');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (3, 1301, '0');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (2, 1302, '1000');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (2, 1303, '1.5');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (4, 1302, '1000');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (4, 1303, '1.5');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (5, 1301, '8');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (6, 1302, '1000');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (6, 1303, '1.5');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (6, 1304, '3000');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (7, 1301, '0');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (8, 1302, '1000');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (8, 1303, '1.5');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (8, 1304, '3000');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (9, 1301, '3');
INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE) VALUES (10, 1301, '3');

COMMIT WORK;

