INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (1, 'Сервисный сбор', 121, 1);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (2, 'Предварительный весовой сбор', 121, NULL);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (3, 'Весовой сбор', 121, 2);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (4, 'Плата за возврат', 121, 3);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (5, 'Возврат сервисного сбора при возврате', 121, 3);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (6, 'Красный бонус по акции', 121, NULL);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (7, 'Желтый бонус по акции', 121, NULL);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (8, 'Cиний бонус по акции', 121, NULL);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (9, 'Штраф за невостребованную заявку', 121, 5);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (10, 'Плата за возврат в Литву', 121, NULL);

COMMIT WORK;

