INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (1, 'Сервисный сбор', 121, 1);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (2, 'Предварительный весовой сбор', 121, 1);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (3, 'Весовой сбор', 121, 2);
INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID) VALUES (4, 'Предоплата', 121, 1);

COMMIT WORK;

