INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (1, 'zakaz&#45;[[:DIGIT:]]{4}&#45;[[:DIGIT:]]{2}&#45;[[:DIGIT:]]{2}&#45;[[:DIGIT:]]{6,}.dat', 'order');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (2, 'a[[:DIGIT:]]{8}[_][[:DIGIT:]]{2}.[[:DIGIT:]]{3}', 'default');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (3, 'n&#45;a[[:DIGIT:]]{8}[_][[:DIGIT:]]{2}.[[:DIGIT:]]{3}.[[:DIGIT:]]{3}', 'protocol');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (4, 'liefau[[:ALNUM :]]{2}[_][[:DIGIT:]]{8}.[[:DIGIT:]]{3}', 'liefer');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (7, 'ob[[:LOWER:]][_][[:DIGIT:]]{2}.[[:DIGIT:]]{2,3}.txt', 'PaymentIn');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (6, 't&#45;cons[_][[:DIGIT:]]{8}.[[:DIGIT:]]{5}.[[:DIGIT:]]{5,6}', 'Consignment');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (5, 'packl[_][[:DIGIT:]]{8}.[[:DIGIT:]]{5}', 'Packliist');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (8, 'n&#45;s[[:DIGIT:]]{8}[_][[:DIGIT:]]{2,5}.[[:DIGIT:]]{3}.[[:DIGIT:]]{3}', 'Cancellation');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (9, 'info[_][[:DIGIT:]]{8}[_]artn[[:DIGIT:]]{3}.txt', 'ArtN');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (10, 'info[_][[:DIGIT:]]{8}[_][[:DIGIT:]]{5}[_]2pay[_][[:DIGIT:]]{3}.txt', 'Info2Pay');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (11, ' ', 'Out');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (12, 'order&#45;[[:DIGIT:]]{8}&#45;[[:DIGIT:]]{3}&#45;%.xml', 'Заявка xml');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (14, 'info[_][[:DIGIT:]]{8}[_]komnr[_][[:DIGIT:]]{3}.txt', 'KomnR');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (15, 'info[_][[:DIGIT:]]{8}[_]art[_][[:DIGIT:]]{3}.txt', 'Art');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (16, 'balt&#45;post.cod.[[:DIGIT:]]{8}&#45;[[:DIGIT:]]{8}.csv', 'Платежи Наложенные');

COMMIT WORK;

