INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (1, 'zakaz&#45;[[:DIGIT:]]{4}&#45;[[:DIGIT:]]{2}&#45;[[:DIGIT:]]{2}&#45;[[:DIGIT:]]{6,}.dat', 'order');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (2, 'a[[:DIGIT:]]{8}_[[:DIGIT:]]{2}.[[:DIGIT:]]{3}', 'default');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (3, 'n&#45;a[[:DIGIT:]]{8}_[[:DIGIT:]]{2}.[[:DIGIT:]]{3}.[[:DIGIT:]]{3}', 'protocol');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (4, 'liefau[[:ALNUM :]]{2}_[[:DIGIT:]]{8}.[[:DIGIT:]]{3}', 'liefer');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (7, 'ob[[:LOWER:]]_[[:DIGIT:]]{2}.[[:DIGIT:]]{2,3}.txt', 'PaymentIn');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (6, 't&#45;cons_[[:DIGIT:]]{8}.[[:DIGIT:]]{5}.[[:DIGIT:]]{5,6}', 'Consignment');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (5, 'packl_[[:DIGIT:]]{8}.[[:DIGIT:]]{5}', 'Packliist');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (8, 'n&#45;s[[:DIGIT:]]{8}_[[:DIGIT:]]{2}.[[:DIGIT:]]{3}.[[:DIGIT:]]{3}', 'Cancellation');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (9, 'info_[[:DIGIT:]]{8}_artn[[:DIGIT:]]{3}.txt', 'ArtN');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (10, 'info_[[:DIGIT:]]{8}_[[:DIGIT:]]{5}_2pay_[[:DIGIT:]]{3}.txt', 'Info2Pay');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (11, ' ', 'Out');
INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME) VALUES (12, 'order&#45;[[:DIGIT:]]{8}&#45;[[:DIGIT:]]{3}&#45;%.xml', 'Заявка xml');

COMMIT WORK;

