INSERT INTO BLOCK_REF (BLOCK_SIGN, LITERA) VALUES ('18', 'С');
REINSERT ('25', 'Ш');
REINSERT ('11', 'К');
REINSERT ('13', 'М');
REINSERT ('11_11', NULL);
REINSERT ('ROOT', NULL);
REINSERT ('11_34', NULL);
REINSERT ('00', NULL);
REINSERT ('01', 'А');
REINSERT ('02', 'Б');
REINSERT ('15', 'О');
REINSERT ('19', 'Т');

COMMIT WORK;

