INSERT INTO DOCUMENTS (DOCUMENT_ID, REFDOC_ID) VALUES (1, NULL);
REINSERT (3, NULL);
REINSERT (4, NULL);
REINSERT (10, NULL);
REINSERT (14, NULL);
REINSERT (17, NULL);
REINSERT (18, 17);
REINSERT (19, NULL);
REINSERT (22, NULL);
REINSERT (23, NULL);
REINSERT (32, NULL);

COMMIT WORK;

