INSERT INTO INSTRUMENTS (INSTR_ID) VALUES (8);
REINSERT (9);
REINSERT (11);
REINSERT (12);
REINSERT (13);
REINSERT (15);
REINSERT (16);
REINSERT (20);
REINSERT (21);
REINSERT (24);
REINSERT (25);
REINSERT (26);
REINSERT (27);
REINSERT (28);
REINSERT (29);
REINSERT (30);
REINSERT (31);

COMMIT WORK;

