INSERT INTO OBJTYPEATTRS (ATTR_ID, OBJTYPE, ATTR_CODE, KEI, ATTR_VALUE) VALUES (1, '1', 'ALLOW_DEFAULT_DOCSET', 924, '1');
REINSERT (2, '1', 'DEFAULT_DOCSET_NAME', 924, '-All-');
REINSERT (3, '144', 'ALLOW_DEFAULT_DOCSET', 924, '0');

COMMIT WORK;

