DROP PROCEDURE TEST_PARAMS;
DROP PROCEDURE TEST_SUSPEND;
DROP PROCEDURE IBDAC_BLOB_INSERT;
DROP PROCEDURE COUNT_BY_SAL;
DROP PROCEDURE SEL_FROM_EMP;
DROP PROCEDURE IBDAC_SEL_FROM_TEXT_BLOB;

COMMIT;

DROP TABLE EMP;

COMMIT;

DROP TABLE DEPT;
DROP TABLE IBDAC_BLOB;
DROP TABLE CRGRID_TEST;
DROP TABLE IBDAC_LONG_CHAR;
DROP TABLE IBDAC_PICTURES;
DROP TABLE IBDAC_BLOB_TEXT;

DELETE FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'IBDAC_GEN';
DROP TABLE IBDAC_ARRAYS;
DROP TABLE DB_KEY_TABLE;
DROP TABLE THREAD_TABLE;
DROP TABLE IBDAC_Loaded;

COMMIT;