
DECLARE EXTERNAL FUNCTION COPYFRONT_WITHKEY
    CSTRING(4000),
    CSTRING(20),
RETURNS CSTRING(4000)
ENTRY_POINT 'CopyFront_WithKey' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION COPYFRONT_WITHOUTKEY
    CSTRING(4000),
    CSTRING(20),
RETURNS CSTRING(4000)
ENTRY_POINT 'CopyFront_WithOutKey' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION COPY_START_END
    CSTRING(4000),
    CSTRING(20),
    CSTRING(20),
    INTEGER,
    INTEGER
RETURNS CSTRING(4000)
ENTRY_POINT 'Copy_Start_End' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION COPY_BETWEEN
    CSTRING(4000),
    CSTRING(20),
    CSTRING(20),
    INTEGER,
    INTEGER
RETURNS CSTRING(4000)
ENTRY_POINT 'Copy_Between' MODULE_NAME 'GvUDF.DLL';
