SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (65, 'ORDER_PACKED', 1, 'ORDER_FOREACH_TAXRATE');

INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (66, 'ORDER_PACKED', 2, 'ACCOUNT_CREDITORDER');



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (65, 'ORDER_ID', 'A', 'ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (66, 'AMOUNT_EUR', 'F', 'select o.cost_eur from v_order_summary o where o.order_id = [ID]');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (66, 'ID', 'A', 'ACCOUNT_ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (66, 'NOTES', 'V', 'Доплата за весовой сбор по заявке [ORDER_CODE]');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (66, 'ORDER_CODE', 'A', 'ORDER_CODE');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (66, 'ORDER_ID', 'A', 'ID');

UPDATE ACTIONTREE_PARAMS
SET PARAM_VALUE = 'Штраф за невостребованную заявку [ORDER_CODE] [AMOUNT_EUR] EUR'
WHERE (ACTIONTREEITEM_ID = 77) AND (PARAM_NAME = 'NOTES') AND (PARAM_KIND = 'V');



DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 70) AND (PARAM_NAME = 'ORDER_ID') AND (PARAM_KIND = 'A');


DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 70);


