SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDER_EMPTY', 'Пустая', 'ORDER', 'ORDER_STORE');


COMMIT WORK;

INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES ('ORDER_EMPTY', 'ACTIVEITEMSCOUNT', 'N', '=', '0', NULL);



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_EMPTY', 'ACTIVEITEMSCOUNT', 'F', 'select sum(oi.amount) from orderitems oi where oi.order_id = [ID]');

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_EMPTY', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_EMPTY', 'NEW.STATUS_SIGN', 'V', 'EMPTY');



INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (7, 'ORDER_APPROVE', 5, 'ORDER_EMPTY');

INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (44, 'ORDERITEM_REJECT', 1, 'ORDER_ANULLED');



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (3, 'NEW.FLAG_SIGN', 'V', 'APPROVED');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (7, 'ID', 'A', 'ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (44, 'ID', 'A', 'ORDER_ID');



INSERT INTO ARTICLEMASKS (CATALOG_ID, ARTICLE_CODE_MASK, ARTICLE_SIGN_MASK)
  VALUES (10, 'V[[:DIGIT:]]{6}[[:ALNUM:]]{1,2}', '[1][2][3][4][5][6][7]');



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (317, 'CLIENT', 'NOTE', 'Примечание', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (714, 'ORDER', 'NOTE', 'Примечание', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (761, 'ORDER', 'SOURCE', 'Источник заявки', 'SOURCE', NULL);




INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (214, 'Пустая', 'ORDER', NULL, 'EMPTY', NULL, ',APPENDABLE,BALANCEABLE,CANCELABLE,DELETEABLE,EDITABLE,', NULL, NULL);




INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (285, 'Возврат отправлен в Вильнюс', 'ORDERITEM', NULL, 'RETURNSENTVILNIUS', NULL, NULL, NULL, 1);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (286, 'Возврат отправлен в Германию', 'ORDERITEM', NULL, 'RETURNSENTGERMANY', NULL, NULL, NULL, 1);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (287, 'Возврат доставлен в Вильнюс', 'ORDERITEM', NULL, 'RETURNACCEPTEDVILNIUS', NULL, NULL, NULL, NULL);



INSERT INTO FLAGS (FLAG_SIGN, FLAG_NAME, GROUP_NO)
  VALUES ('RETURN', 'Возврат', NULL);



INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (178, 'APPROVED');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (187, 'RETURN');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (203, 'DELETEABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (205, 'BALANCEABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (207, 'BALANCEABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (210, 'BALANCEABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (214, 'APPENDABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (214, 'BALANCEABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (214, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (214, 'DELETEABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (214, 'EDITABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (217, 'RETURN');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (277, 'RETURN');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (279, 'RETURN');



UPDATE TEMPLATES
SET FILENAME_MASK = ' ',
    PLUGIN_NAME = 'Out'
WHERE (TEMPLATE_ID = 11);



INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDER', 'PRODUCT_NAME2ID', 'Наложенный платеж', '2');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDER', 'PRODUCT_NAME2ID', 'Предоплата', '1');



INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (173, 178, 'ORDERITEM_STORE');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (203, 214, 'ORDER_EMPTY');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (214, 203, 'ORDER_APPROVE');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (214, 209, 'ORDER_CANCELLED');


DELETE FROM ATTRS
WHERE (ATTR_ID = 726);
DELETE FROM ATTRS
WHERE (ATTR_ID = 727);
DELETE FROM ATTRS
WHERE (ATTR_ID = 728);
DELETE FROM ATTRS
WHERE (ATTR_ID = 729);

DELETE FROM ARTICLEMASKS
WHERE (CATALOG_ID = 10) AND (ARTICLE_CODE_MASK = 'V[[:DIGIT:]]{6}(IX|30)');


DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 3) AND (PARAM_NAME = 'NEW.STATUS_SIGN') AND (PARAM_KIND = 'V');


