SET SQL DIALECT 3;

SET NAMES WIN1251;

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (264, 'Задержка 2 недели', 'ORDERITEM', NULL, 'DELAY2WEEK', NULL, NULL, NULL);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (265, 'Задержка 9 недель', 'ORDERITEM', NULL, 'DELAY9WEEK', NULL, NULL, NULL);



INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (175, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (264, 'AVAILABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (264, 'DELAY');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (265, 'AVAILABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (265, 'DELAY');



INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (175, 182, 'ORDERITEM_CANCELREQUEST');


UPDATE ORDERITEMS 
SET STATUS_ID =180
WHERE ORDERITEM_ID = 45;

UPDATE ORDERITEMS
SET ARTICLE_CODE=upper(ARTICLE_CODE);