SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_PAY', 'Оплата позиции заявки', 'ORDERITEM', 'ORDERITEM_STORE');



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_PAY', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_PAY', 'REST_EUR', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_PAY', 'REST_EUR', 'O', NULL);



INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (14, 'ORDERITEM_PAY', 1, 'ACCOUNT_CREDIT');



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (14, 'AMOUNT_EUR', 'A', 'AMOUNT_EUR');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (14, 'ID', 'A', 'ACCOUNT_ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (14, 'ORDERITEM_ID', 'A', 'ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (14, 'ORDER_ID', 'A', 'ORDER_ID');



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (730, 'ORDER', 'STATUS_SIGN', 'Сигнатура статуса', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (731, 'ORDER', 'STATUS_FLAG_LIST', 'Перечень флагов статуса', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (809, 'ORDERTAX', 'PAID_EUR', 'Оплаченная сумма', 'PAID_EUR', NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (810, 'ORDERTAX', 'STATUS_SIGN', 'Сигнатура статуса', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (811, 'ORDERTAX', 'STATUS_FLAG_LIST', 'Список флагов статуса', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (933, 'ORDERITEM', 'PAID_EUR', 'Оплаченная сумма', 'PAID_EUR', NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (934, 'ORDERITEM', 'STATUS_SIGN', 'Сигнатура статуса', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (935, 'ORDERITEM', 'STATUS_FLAG_LIST', 'Список флагов статуса', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (936, 'ORDERITEM', 'STATE_SIGN', 'Cигнатура состояния', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (937, 'ORDERITEM', 'STATE_FLAG_LIST', 'Список флагов состояния', NULL, 'R');



INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (174, 'DELETEABLE');

