/* Server version: WI-V6.3.1.26351 Firebird 2.5 
SET CLIENTLIB 'fbclient.dll';
   SQLDialect: 3. ODS: 11.2. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 2048 (8192 Kb). Read-only: False. */
SET NAMES CYRL;

SET SQL DIALECT 3;

SET AUTODDL ON;

/* Create(Add) Crant */
GRANT ALL ON ACCOPERS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACCOUNTS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACTION_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACTIONCODE_CRITERIAS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACTIONCODE_PARAMS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACTIONCODES TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACTIONS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACTIONTREE TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACTIONTREE_CRITERIAS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ACTIONTREE_PARAMS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ADRESSES TO VALERY WITH GRANT OPTION;

GRANT ALL ON ARTICLE_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ARTICLECODE_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ARTICLECODES TO VALERY WITH GRANT OPTION;

GRANT ALL ON ARTICLEMASKS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ARTICLES TO VALERY WITH GRANT OPTION;

GRANT ALL ON ARTICLESIGNS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON BUILDS TO VALERY WITH GRANT OPTION;

GRANT ALL ON CALCPOINTS TO VALERY WITH GRANT OPTION;

GRANT ALL ON CATALOG2PLUGIN TO VALERY WITH GRANT OPTION;

GRANT ALL ON CATALOGS TO VALERY WITH GRANT OPTION;

GRANT ALL ON CLIENT_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON CLIENTS TO VALERY WITH GRANT OPTION;

GRANT ALL ON COUNTERS TO VALERY WITH GRANT OPTION;

GRANT ALL ON DETECTOR TO VALERY WITH GRANT OPTION;

GRANT ALL ON EVENTCODES TO VALERY WITH GRANT OPTION;

GRANT ALL ON EVENTS TO VALERY WITH GRANT OPTION;

GRANT ALL ON FLAGS TO VALERY WITH GRANT OPTION;

GRANT ALL ON FLAGS2STATUSES TO VALERY WITH GRANT OPTION;

GRANT ALL ON IMP_CITYGET TO VALERY WITH GRANT OPTION;

GRANT ALL ON IMP_CITYTYPE TO VALERY WITH GRANT OPTION;

GRANT ALL ON IMP_CLIENT TO VALERY WITH GRANT OPTION;

GRANT ALL ON IMP_OBLAST TO VALERY WITH GRANT OPTION;

GRANT ALL ON IMP_REGION TO VALERY WITH GRANT OPTION;

GRANT ALL ON LOGS TO VALERY WITH GRANT OPTION;

GRANT ALL ON MAGAZINES TO VALERY WITH GRANT OPTION;

GRANT ALL ON MESSAGE_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON MESSAGES TO VALERY WITH GRANT OPTION;

GRANT ALL ON NOTIFIES TO VALERY WITH GRANT OPTION;

GRANT ALL ON OBJECTS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ORDER_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ORDERHISTORY TO VALERY WITH GRANT OPTION;

GRANT ALL ON ORDERITEM_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ORDERITEMS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ORDERMONEYS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ORDERS TO VALERY WITH GRANT OPTION;

GRANT ALL ON ORDERTAXS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PARAMACTIONS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PARAMHEADS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PARAMKINDS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PARAMS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PAYMENTS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PHONEPREFIXES TO VALERY WITH GRANT OPTION;

GRANT ALL ON PHONETYPES TO VALERY WITH GRANT OPTION;

GRANT ALL ON PLACES TO VALERY WITH GRANT OPTION;

GRANT ALL ON PLACETYPES TO VALERY WITH GRANT OPTION;

GRANT ALL ON PLUGIN_PARAMS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PLUGINS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PORT2TEMPLATE TO VALERY WITH GRANT OPTION;

GRANT ALL ON PORTS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PRODUCT_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON PRODUCTS TO VALERY WITH GRANT OPTION;

GRANT ALL ON RECODES TO VALERY WITH GRANT OPTION;

GRANT ALL ON SEARCHES TO VALERY WITH GRANT OPTION;

GRANT ALL ON SESSIONS TO VALERY WITH GRANT OPTION;

GRANT ALL ON SETTINGS TO VALERY WITH GRANT OPTION;

GRANT ALL ON SETTINGSIGNS TO VALERY WITH GRANT OPTION;

GRANT ALL ON STATUS_RULES TO VALERY WITH GRANT OPTION;

GRANT ALL ON STATUSES TO VALERY WITH GRANT OPTION;

GRANT ALL ON STREETTYPES TO VALERY WITH GRANT OPTION;

GRANT ALL ON TAXPLANS TO VALERY WITH GRANT OPTION;

GRANT ALL ON TAXRATE_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON TAXRATES TO VALERY WITH GRANT OPTION;

GRANT ALL ON TAXSERVS TO VALERY WITH GRANT OPTION;

GRANT ALL ON TEMPLATES TO VALERY WITH GRANT OPTION;

GRANT ALL ON TMP_OTTO_ARTICLE TO VALERY WITH GRANT OPTION;

GRANT ALL ON TMP_SEARCHES TO VALERY WITH GRANT OPTION;

GRANT ALL ON USERS TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ACTION_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ADRESS_TEXT TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ARTICLES TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ATTRINPARAM TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_CLIENT_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_CLIENTADRESS TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_CLIENTS_FIO TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ORDER_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ORDER_FULL_SPECIFICATION TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ORDER_INVOICEABLE TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ORDER_PAID TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ORDER_SUMMARY TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ORDERITEM_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_ORDERS TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_PLACE_TEXT TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_PLACES TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_SETTINGS TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_STATUS_AVAILABLE TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_STATUSES TO VALERY WITH GRANT OPTION;

GRANT ALL ON V_TAXRATE_ATTRS TO VALERY WITH GRANT OPTION;

GRANT ALL ON VALUTES TO VALERY WITH GRANT OPTION;

GRANT ALL ON VENDORS TO VALERY WITH GRANT OPTION;

GRANT EXECUTE ON PROCEDURE AALL_CLEAR TO VALERY;

GRANT EXECUTE ON PROCEDURE ACCOUNT_X_SEARCH TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDIT TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDITORDER TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBIT TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBITORDER TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_PAYMENTIN TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ADRESS_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_CLIENT_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_EVENT_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_MAGAZINE_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_MESSAGE_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_DEBIT TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERITEM TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERTAX TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_TAXRATE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDERITEM_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_CREDIT TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_DEBIT TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_ORDERTAX_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_PAYMENT_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACT_PLACE_STORE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACTION_DETECT TO VALERY;

GRANT EXECUTE ON PROCEDURE ACTION_EXECUTE TO VALERY;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN TO VALERY;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN_ACTION TO VALERY;

GRANT EXECUTE ON PROCEDURE ACTION_RUN TO VALERY;

GRANT EXECUTE ON PROCEDURE ARTICLE_GOC TO VALERY;

GRANT EXECUTE ON PROCEDURE ARTICLECODE_GOC TO VALERY;

GRANT EXECUTE ON PROCEDURE ARTICLES_PUMP TO VALERY;

GRANT EXECUTE ON PROCEDURE ARTICLESIGN_DETECT TO VALERY;

GRANT EXECUTE ON PROCEDURE ATTR_PUT TO VALERY;

GRANT EXECUTE ON PROCEDURE COUNTER_NEXTVAL TO VALERY;

GRANT EXECUTE ON PROCEDURE IMP_CLIENTS TO VALERY;

GRANT EXECUTE ON PROCEDURE LOG_CREATE TO VALERY;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE TO VALERY;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE_SKIPED TO VALERY;

GRANT EXECUTE ON PROCEDURE MAGAZINE_DETECT TO VALERY;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY TO VALERY;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY_2 TO VALERY;

GRANT EXECUTE ON PROCEDURE MESSAGE_CREATE TO VALERY;

GRANT EXECUTE ON PROCEDURE MESSAGE_RELEASE TO VALERY;

GRANT EXECUTE ON PROCEDURE NOTIFY_CREATE TO VALERY;

GRANT EXECUTE ON PROCEDURE NOTIFY_QUERY TO VALERY;

GRANT EXECUTE ON PROCEDURE OBJECT_GET TO VALERY;

GRANT EXECUTE ON PROCEDURE OBJECT_PUT TO VALERY;

GRANT EXECUTE ON PROCEDURE OBJECT_READ TO VALERY;

GRANT EXECUTE ON PROCEDURE OBJECT_UPDATEABLE TO VALERY;

GRANT EXECUTE ON PROCEDURE ORDER_READ TO VALERY;

GRANT EXECUTE ON PROCEDURE ORDER_X_ACTIVEITEMSCOUNT TO VALERY;

GRANT EXECUTE ON PROCEDURE ORDER_X_UNINVOICED TO VALERY;

GRANT EXECUTE ON PROCEDURE ORDERHISTORY_UPDATE TO VALERY;

GRANT EXECUTE ON PROCEDURE ORDERITEM_READ TO VALERY;

GRANT EXECUTE ON PROCEDURE ORDERITEM_X_GETSTATEID TO VALERY;

GRANT EXECUTE ON PROCEDURE ORDERTAX_READ TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_IN TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_OUT TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_CLONE TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_CREATE TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_CRITERIA TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_DEL TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_FILLPATTERN TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_GET TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE_4ACTION TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_SET TO VALERY;

GRANT EXECUTE ON PROCEDURE PARAM_UNPARSE TO VALERY;

GRANT EXECUTE ON PROCEDURE PIVOT_RECORD TO VALERY;

GRANT EXECUTE ON PROCEDURE PLACE_DETECT TO VALERY;

GRANT EXECUTE ON PROCEDURE PLACE_READ TO VALERY;

GRANT EXECUTE ON PROCEDURE PLUGIN_VALUE TO VALERY;

GRANT EXECUTE ON PROCEDURE SEARCH TO VALERY;

GRANT EXECUTE ON PROCEDURE SEARCH_GET_NGRAMM TO VALERY;

GRANT EXECUTE ON PROCEDURE SETTING_GET TO VALERY;

GRANT EXECUTE ON PROCEDURE SETTING_SET TO VALERY;

GRANT EXECUTE ON PROCEDURE SPLITBLOB TO VALERY;

GRANT EXECUTE ON PROCEDURE SPLITSTRING TO VALERY;

GRANT EXECUTE ON PROCEDURE STATUS_CHECK_CONVERSION TO VALERY;

GRANT EXECUTE ON PROCEDURE STATUS_CONVERSION_BY_FLAG TO VALERY;

GRANT EXECUTE ON PROCEDURE STATUS_GET_CONVERSION TO VALERY;

GRANT EXECUTE ON PROCEDURE STATUS_GET_DEFAULT TO VALERY;

GRANT EXECUTE ON PROCEDURE STATUS_STORE_DATE TO VALERY;

GRANT EXECUTE ON PROCEDURE TAX_FIXED_SUM TO VALERY;

GRANT EXECUTE ON PROCEDURE TAX_USE_REST TO VALERY;

GRANT EXECUTE ON PROCEDURE TAX_WEIGHT TO VALERY;

GRANT EXECUTE ON PROCEDURE TAXRATE_CALC TO VALERY;


