SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ)
  VALUES ('DEALERNOTIFY', 'Сообщение дилеру', 'DEALERNOTIFIES', 'DEALERNOTIFY_ID', NULL, NULL);


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('DEALERNOTIFY_CREATE', 'Создать сообщение для дилера', 'DEALERNOTIFY', 'DEALERNOTIFY_STORE');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('DEALERNOTIFY_STORE', 'Сохранить сообщение для дилера', 'DEALERNOTIFY', NULL);

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('DEALERNOTIFY_UPLOAD', 'Выгрузить сообщение в файл', 'DEALERNOTIFY', 'DEALERNOTIFY_STORE');



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('DEALERNOTIFY_CREATE', 'DEALER_ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('DEALERNOTIFY_CREATE', 'MESSAGE_ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('DEALERNOTIFY_CREATE', 'NOTIFY_TEXT', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('DEALERNOTIFY_UPLOAD', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('DEALERNOTIFY_UPLOAD', 'NEW.STATUS_SIGN', 'V', 'UPLOADED');


INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (808, 'ORDERTAX', 'COST_BYR', 'Стоимость услуги в BYR', NULL, 'R');



INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (31, 'Новое', 'DEALERNOTIFY', 1, 'NEW', 'DEALERNOTIFY_CREATE', NULL, NULL, NULL);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (32, 'Выгружено', 'DEALERNOTIFY', NULL, 'UPLOADED', NULL, NULL, NULL, NULL);



INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (31, 'NEW');



INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATE', '30', 'NULL');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATE', '40', 'NULL');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATE', '50', 'NULL');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATE', '70', 'NULL');

UPDATE RECODES
SET RECODED_VALUE = 'ACCEPTREQUEST,ACCEPTED'
WHERE (OBJECT_SIGN = 'ORDERITEM') AND (ATTR_SIGN = 'ART_STATUS') AND (ORIGINAL_VALUE = '10');

UPDATE RECODES
SET RECODED_VALUE = 'BUNDLING,PREPACKED'
WHERE (OBJECT_SIGN = 'ORDERITEM') AND (ATTR_SIGN = 'ART_STATUS') AND (ORIGINAL_VALUE = '30');

UPDATE RECODES
SET RECODED_VALUE = 'BUNDLING,PREPACKED'
WHERE (OBJECT_SIGN = 'ORDERITEM') AND (ATTR_SIGN = 'ART_STATUS') AND (ORIGINAL_VALUE = '40');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', '50', 'PACKED');

UPDATE RECODES
SET RECODED_VALUE = 'ANULLED,CANCELLED,REJECTED'
WHERE (OBJECT_SIGN = 'ORDERITEM') AND (ATTR_SIGN = 'ART_STATUS') AND (ORIGINAL_VALUE = '90');

UPDATE RECODES
SET RECODED_VALUE = 'ANULLED,CANCELLED,REJECTED'
WHERE (OBJECT_SIGN = 'ORDERITEM') AND (ATTR_SIGN = 'ART_STATUS') AND (ORIGINAL_VALUE = 's0');


