SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (52, 'NEW.STATUS_SIGN', 'V', 'CANCELLED');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (52, 'ORDER_ID', 'A', 'ID');


COMMIT WORK;

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERTAX_CANCELLED'
WHERE (OLD_STATUS_ID = 162) AND (NEW_STATUS_ID = 163);

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (205, 209, 'ORDER_CANCELLED');


COMMIT WORK;


delete from logs;
delete from paramheads;