SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE ACTIONCODES
SET PROCEDURE_NAME = NULL
WHERE (ACTION_SIGN = 'ACCOUNT_DEBIT');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ACCOUNT_MANUALDEBIT', 'Ручное зачисление на счет', 'ACCOUNT', 'ACCOUNT_DEBIT');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('PLACE_CREATE', 'Зарегистрирвать населенный пункт', 'PLACE', 'PLACE_STORE');



INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES ('ACCOUNT_MANUALDEBIT', 'AMOUNT_EUR', 'N', '>=', '0', NULL);



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ACCOUNT_MANUALDEBIT', 'AMOUNT_EUR', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ACCOUNT_MANUALDEBIT', 'BYR2EUR', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ACCOUNT_MANUALDEBIT', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ACCOUNT_MANUALDEBIT', 'NOTES', 'V', 'Ручное зачисление cуммы на счет по курсу [BYR2EUR]');

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('PLACE_CREATE', 'AREA_ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('PLACE_CREATE', 'PLACETYPE_CODE', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('PLACE_CREATE', 'PLACE_NAME', 'I', NULL);



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (732, 'ORDER', 'ACCOUNT_ID', 'Id счета', 'ACCOUNT_ID', NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (733, 'ORDER', 'AUFTRAG_ID', 'Id заказа в отто', NULL, NULL);



DELETE FROM ATTRS
WHERE (ATTR_ID = 809);
DELETE FROM ATTRS
WHERE (ATTR_ID = 933);


DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 1) AND (PARAM_NAME = 'ID') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 1) AND (PARAM_NAME = 'REST_EUR') AND (PARAM_KIND = 'A');


DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 1);


DELETE FROM ACTIONCODE_PARAMS
WHERE (ACTION_SIGN = 'ACCOUNT_USERDEBIT') AND (PARAM_NAME = 'AMOUNT_EUR') AND (PARAM_KIND = 'I');
DELETE FROM ACTIONCODE_PARAMS
WHERE (ACTION_SIGN = 'ACCOUNT_USERDEBIT') AND (PARAM_NAME = 'AMOUNT_EUR') AND (PARAM_KIND = 'W');
DELETE FROM ACTIONCODE_PARAMS
WHERE (ACTION_SIGN = 'ACCOUNT_USERDEBIT') AND (PARAM_NAME = 'BALANCE_EUR') AND (PARAM_KIND = 'W');
DELETE FROM ACTIONCODE_PARAMS
WHERE (ACTION_SIGN = 'ACCOUNT_USERDEBIT') AND (PARAM_NAME = 'ID') AND (PARAM_KIND = 'I');
DELETE FROM ACTIONCODE_PARAMS
WHERE (ACTION_SIGN = 'ACCOUNT_USERDEBIT') AND (PARAM_NAME = 'REST_EUR') AND (PARAM_KIND = 'W');
DELETE FROM ACTIONCODE_PARAMS
WHERE (ACTION_SIGN = 'ACCOUNT_USERDEBIT') AND (PARAM_NAME = 'SIGN') AND (PARAM_KIND = 'V');


DELETE FROM ACTIONCODE_CRITERIAS
WHERE (ACTIONCODE_SIGN = 'ACCOUNT_USERDEBIT') AND (PARAM_NAME = 'AMOUNT_EUR');


DELETE FROM ACTIONCODES
WHERE (ACTION_SIGN = 'ACCOUNT_USERDEBIT');


