SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES ('ORDER_PAID', 'COST_EUR', 'N', '<=', '0', NULL);


INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_PAID', 'COST_EUR', 'F', 'select os.cost_eur from v_order_summary os where os.order_id = [ID]');


INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (32, 'ACCOUNT_CREDITORDER', 1, 'ORDER_PAID');


INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (32, 'ID', 'A', 'ORDER_ID');


UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 214);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 242);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (280, 'Задержка 1 неделю', 'ORDERITEM', NULL, 'DELAY1WEEK', NULL, ',AVAILABLE,DELAY,', NULL, 1);


INSERT INTO FLAGS (FLAG_SIGN, FLAG_NAME, GROUP_NO)
  VALUES ('PAYINABLE', 'Можно зачислать платежи', NULL);


INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (205, 'PAYINABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (280, 'AVAILABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (280, 'DELAY');


INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '21', 'DELAY1WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 1 Wochen', 'Задержка до 1 недели');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 10 Wochen', 'Задержка до 10 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 11 Wochen', 'Задержка до 11 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 12 Wochen', 'Задержка до 12 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 13 Wochen', 'Задержка до 13 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 14 Wochen', 'Задержка до 14 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 15 Wochen', 'Задержка до 15 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 17 Wochen', 'Задержка до 17 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 18 Wochen', 'Задержка до 18 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 3 Wochen', 'Задержка до 3 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 6 Wochen', 'Задержка до 6 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 8 Wochen', 'Задержка до 8 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 9 Wochen', 'Задержка до 9 недель');


