SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE ACTIONCODE_CRITERIAS
SET PARAM_ACTION = '>='
WHERE (ACTIONCODE_SIGN = 'ACCOUNT_USERDEBIT') AND (PARAM_NAME = 'AMOUNT_EUR');


