SET SQL DIALECT 3;

SET NAMES WIN1251;

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (1304, 'TAXRATE', 'FREE_AMOUNT', 'Бесплатный порог', NULL, NULL);

UPDATE CALCPOINTS
SET OBJECT_STATUS_ID = 205
WHERE (CALCPOINT_ID = 2);


UPDATE TAXPLANS
SET STATUS_ID = 119
WHERE (TAXPLAN_ID = 1);

UPDATE TAXPLANS
SET STATUS_ID = 119
WHERE (TAXPLAN_ID = 2);

INSERT INTO TAXPLANS (TAXPLAN_ID, TAXPLAN_NAME, STATUS_ID, STATUS_DTM)
  VALUES (3, 'Стандарт', 114, null);

INSERT INTO TAXPLANS (TAXPLAN_ID, TAXPLAN_NAME, STATUS_ID, STATUS_DTM)
  VALUES (4, 'Свои', 115, null);



INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID)
  VALUES (3, 'Весовой сбор', 121, 2);



INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (5, 1, 3, 'TAX_FIXED_SUM', 131);

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (6, 3, 3, 'TAX_WEIGHT', 131);

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (7, 1, 4, 'TAX_FIXED_SUM', 131);

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (8, 3, 4, 'TAX_WEIGHT', 131);


INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (5, 1301, '8');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (6, 1302, '1000');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (6, 1303, '1.5');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (6, 1304, '3000');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (7, 1301, '0');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (8, 1302, '1000');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (8, 1303, '1.5');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (8, 1304, '3000');


