SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDER_DRAFT', 'Сохранить черновик заявки', 'ORDER', 'ORDER_STORE');


COMMIT WORK;

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_DRAFT', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_DRAFT', 'NEW.STATUS_SIGN', 'V', 'DRAFT');

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_DRAFT', 'PRODUCT_ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_DRAFT', 'TAXPLAN_ID', 'I', NULL);


COMMIT WORK;

UPDATE ACTIONTREE
SET ACTION_SIGN = 'ORDER_DRAFT'
WHERE (ACTIONTREEITEM_ID = 2);


COMMIT WORK;

UPDATE CALCPOINTS
SET OBJECT_STATUS_ID = 202
WHERE (CALCPOINT_ID = 1);


COMMIT WORK;

UPDATE PRODUCTS
SET STATUS_DTM = '1-FEB-2012 14:31:29'
WHERE (PRODUCT_ID = 2);


COMMIT WORK;

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (201, 202, 'ORDER_DRAFT');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (202, 203, 'ORDER_APPROVE');


COMMIT WORK;

UPDATE TEMPLATES
SET FILENAME_MASK = 't&#45;cons_[[:DIGIT:]]{8}.[[:DIGIT:]]{5}.[[:DIGIT:]]{5,6}'
WHERE (TEMPLATE_ID = 6);


COMMIT WORK;

DELETE FROM STATUS_RULES
WHERE (OLD_STATUS_ID = 201) AND (NEW_STATUS_ID = 203);

COMMIT WORK;

