SET SQL DIALECT 3;

SET NAMES UTF8;

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 175) AND (NEW_STATUS_ID = 178);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 175) AND (NEW_STATUS_ID = 179);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 175) AND (NEW_STATUS_ID = 180);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 180) AND (NEW_STATUS_ID = 181);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 180) AND (NEW_STATUS_ID = 182);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 182) AND (NEW_STATUS_ID = 183);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 182) AND (NEW_STATUS_ID = 185);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 185) AND (NEW_STATUS_ID = 186);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_STATUS'
WHERE (OLD_STATUS_ID = 186) AND (NEW_STATUS_ID = 187);


COMMIT WORK;

