SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO OBJECTS (OBJECT_SIGN, OBJECT_NAME, TABLE_NAME, IDFIELD_NAME, ATTR_TABLE_NAME, PROCEDURE_READ)
  VALUES ('BONUS', 'Бонусы', 'BONUSES', 'BONUS_ID', NULL, NULL);



INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('BONUS_CREATE', 'Создать бонус', 'BONUS', 'BONUS_STORE');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('BONUS_RETURN', 'Вернуть бонус', 'BONUS', NULL);

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('BONUS_STORE', 'Сохранить бонус', 'BONUS', NULL);

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('BONUS_USE', 'Использовать бонус', 'BONUS', NULL);



INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION)
  VALUES ('S', 'IN');

INSERT INTO PARAMACTIONS (PARAM_KIND, PARAM_ACTION)
  VALUES ('S', 'NOT IN');



INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES ('ORDER_PAID', 'ORDER_PAIDABLE', 'N', '=', '1', NULL);



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('BONUS_CREATE', 'CLIENT_ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('BONUS_CREATE', 'TAXSERV_ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('BONUS_USE', 'ORDER_ID', 'I', NULL);



INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (11, 'BONUS_USE', 1, 'ORDERTAX_CREATE');



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (32, 'ORDER_PAIDABLE', 'F', 'select count(*)
from orders o
  inner join status_rules sr on (sr.old_status_id = o.status_id)
  inner join statuses sn on (sn.status_id = sr.new_status_id)
where o.order_id = [ORDER_ID] and sn.status_sign = ''PAID''');



INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (76, 'Новый', 'BONUS', 1, 'NEW', 'BONUS_CREATE', NULL, NULL, NULL);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (77, 'Использован', 'BONUS', NULL, 'USED', NULL, NULL, NULL, NULL);



UPDATE TAXPLANS
SET STATUS_DTM = '3-SEP-2012 15:19:14'
WHERE (TAXPLAN_ID = 1);

UPDATE TAXPLANS
SET STATUS_DTM = '3-SEP-2012 15:19:08'
WHERE (TAXPLAN_ID = 2);



INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (76, 77, 'BONUS_USE');



INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID)
  VALUES (6, 'Красный бонус по акции', 121, NULL);

INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID)
  VALUES (7, 'Желтый бонус по акции', 121, NULL);

INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID)
  VALUES (8, 'Cиний бонус по акции', 121, NULL);



INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (21, 6, 1, 'TAX_FIXED_SUM', 131);

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (22, 7, 1, 'TAX_FIXED_SUM', 131);

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (23, 8, 1, 'TAX_FIXED_SUM', 131);



INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (21, 1301, '50');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (22, 1301, '35');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (23, 1301, '5');



DELETE FROM ACTIONCODE_CRITERIAS
WHERE (ACTIONCODE_SIGN = 'ORDER_PAID') AND (PARAM_NAME = 'STATUS_SIGN');


