SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (734, 'ORDER', 'STATE_ID', 'Id дополнтельного состояния', 'STATE_ID', NULL);



UPDATE STATUSES
SET FLAG_SIGN_LIST = NULL
WHERE (STATUS_ID = 173);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (270, 'Оплата отправлена', 'ORDER', NULL, 'PAYSENT', NULL, NULL, 1);



DELETE FROM STATUSES
WHERE (STATUS_ID = 231);
DELETE FROM STATUSES
WHERE (STATUS_ID = 232);
DELETE FROM STATUSES
WHERE (STATUS_ID = 234);
DELETE FROM STATUSES
WHERE (STATUS_ID = 235);
DELETE FROM STATUSES
WHERE (STATUS_ID = 236);
DELETE FROM STATUSES
WHERE (STATUS_ID = 239);


DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 6) AND (PARAM_NAME = 'AMOUNT_EUR') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 6) AND (PARAM_NAME = 'ID') AND (PARAM_KIND = 'B');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 6) AND (PARAM_NAME = 'ORDERITEM_ID') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 7) AND (PARAM_NAME = 'AMOUNT_EUR') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 7) AND (PARAM_NAME = 'ID') AND (PARAM_KIND = 'B');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 7) AND (PARAM_NAME = 'ORDERTAX_ID') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 10) AND (PARAM_NAME = 'AMOUNT_EUR') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 10) AND (PARAM_NAME = 'ID') AND (PARAM_KIND = 'B');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 10) AND (PARAM_NAME = 'ORDERITEM_ID') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 11) AND (PARAM_NAME = 'AMOUNT_EUR') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 11) AND (PARAM_NAME = 'ID') AND (PARAM_KIND = 'B');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 11) AND (PARAM_NAME = 'ORDERITEM_ID') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 14) AND (PARAM_NAME = 'AMOUNT_EUR') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 14) AND (PARAM_NAME = 'ID') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 14) AND (PARAM_NAME = 'ORDERITEM_ID') AND (PARAM_KIND = 'A');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 14) AND (PARAM_NAME = 'ORDER_ID') AND (PARAM_KIND = 'A');


DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 6);
DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 7);
DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 10);
DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 11);
DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 14);
DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 23);
DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 24);


