SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE OBJECTS
SET PROCEDURE_READ = 'ADRESS_READ'
WHERE (OBJECT_SIGN = 'ADRESS');



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (209, 'ADRESS', 'STREETTYPE_SIGN', 'Сигнатура типа улицы', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (702, 'ORDER', 'COST_BYR', 'Стоимость заявки BYR', 'COST_BYR', 'R');

UPDATE ATTRS
SET FIELD_NAME = 'COST_EUR',
    DIRECTION = 'R'
WHERE (ATTR_ID = 706);

UPDATE ATTRS
SET FIELD_NAME = 'PARTNER_NUMBER'
WHERE (ATTR_ID = 1501);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (1504, 'PRODUCT', 'PAYTYPE_SIGN', 'Форма платежа', 'PAYTYPE_SIGN', 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (1505, 'PRODUCT', 'MANUAL_BAR_CODE_ABLE', 'Ручная установка Кода посылки', 'MANUAL_BAR_CODE_ABLE', NULL);



INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 14, 'PARTNER_NUMBER', '[6][7][8][9][10][11][12][13]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 15, 'PARTNER_NUMBER', '[6][7][8][9][10][11][12][13]');



INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME)
  VALUES (14, 'info_[[:DIGIT:]]{8}_komnr_[[:DIGIT:]]{3}.txt', 'KomnR');

INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME)
  VALUES (15, 'info_[[:DIGIT:]]{8}_art_[[:DIGIT:]]{3}.txt', 'Art');



INSERT INTO TAXPLANS (TAXPLAN_ID, TAXPLAN_NAME, STATUS_ID, STATUS_DTM)
  VALUES (6, 'Свои П', 115, '1-APR-2013 23:38:44');



INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (41, 1, 6, 'TAX_FIXED_SUM', 131);



INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (41, 1301, '0');



