SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATE', '22', 'DELAY2WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATE', '23', 'DELAY3WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', '20', 'ACCEPTED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', '22', 'ACCEPTED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', '23', 'ACCEPTED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', '30', 'BUNDLING,PREPACK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', '40', 'PACKED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', '70', 'DELIVERING,DELIVERED,RETURNING,DISCARDED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', '90', 'ANULLED,CANCELLED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'ART_STATUS', 's0', 'ANULLED,CANCELLED');

