SET SQL DIALECT 3;

SET NAMES UTF8;

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_REQUESTSEND', 'Отправить файл с запросом', 'ORDERITEM', 'ORDERITEM_STORE');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_SMSREJECTSEND', 'Установить состояние отправки SMS об отказе', 'ORDERITEM', 'ORDERITEM_STORE');


INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_SMSREJECTSEND', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_SMSREJECTSEND', 'NEW.STATE_SIGN', 'V', 'SMSREJECTSENDED');

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_SMSREJECTSEND', 'STATE_ID', 'X', 'GETSTATEID');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (922, 'ORDERITEM', 'DTM.SMSREJECTSENT', 'Дата отправки SMS об отказе', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (923, 'ORDERITEM', 'DTM.ACCEPTED', 'Дата приема артикула', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (924, 'ORDERITEM', 'DTM.ACCEPTREQUEST', 'Дата отправки запроса', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (925, 'ORDERITEM', 'DTM.CANCELREQUEST', 'Дата отправки запроса на ануляцию', NULL, NULL);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 178);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (261, 'Запрос на отмену отправлен', 'ORDERITEM', NULL, 'CANCELREQUESTSENT', NULL, NULL, 1);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (262, 'SMS отправлена', 'ORDERITEM', NULL, 'SMSREJECTSENT', 'ORDERITEM_SMSREJECTSEND', NULL, 1);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (263, 'Запрос принятия отправлен', 'ORDERITEM', NULL, 'ACCEPTREQUESRSENT', NULL, NULL, 1);

INSERT INTO FLAGS (FLAG_SIGN, FLAG_NAME, GROUP_NO)
  VALUES ('CANCELABLE', 'Возможен запрос на ануляцию', NULL);

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (174, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (180, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (201, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (202, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (203, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (204, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (205, 'CANCELABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (207, 'CANCELABLE');
