SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE OBJECTS
SET PROCEDURE_READ = 'MESSAGE_READ'
WHERE (OBJECT_SIGN = 'MESSAGE');



INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_INDOUBT', 'Позиция под вопросом', 'ORDERITEM', 'ORDERITEM_STORE');



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_INDOUBT', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_INDOUBT', 'NEW.STATE_SIGN', 'V', '');

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_INDOUBT', 'NEW.STATUS_SIGN', 'V', 'INDOUBT');


INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (71, 'ORDER_PREPACKED', 1, 'ORDER_FOREACH_ORDERITEM');

INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (72, 'ORDER_PREPACKED', 2, 'ORDER_FOREACH_ORDERITEM');


INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES (71, 'STATUS_SIGN', 'S', '=', 'ACCEPTED', NULL);

INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES (72, 'STATUS_SIGN', 'S', '=', 'PREPACKED', NULL);



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (71, 'NEW.STATUS_SIGN', 'V', 'INDOUBT');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (71, 'ORDER_ID', 'A', 'ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (72, 'NEW.STATUS_SIGN', 'V', 'INDOUBT');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (72, 'ORDER_ID', 'A', 'ID');



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (405, 'MESSAGE', 'PARTNER_NUMBER', 'Код партнера', NULL, 'R');

UPDATE ATTRS
SET FIELD_NAME = 'AUFTRAG_ID'
WHERE (ATTR_ID = 941);



INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (288, 'Доставка под вопросом', 'ORDERITEM', NULL, 'INDOUBT', NULL, NULL, NULL, NULL);



INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 3, 'DAYNO', '[16][17][18]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 3, 'PARTNER_NUMBER', '[4][5][6][7][8][9][10][11]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 4, 'PARTNER_NUMBER', '[10][11][12][13][14][15][16][17]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 6, 'PARTNER_NUMBER', '[8][9][10][11][12][13][14][15]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 8, 'PARTNER_NUMBER', '[4][5][6][7][8][9][10][11]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 9, 'PARTNER_NUMBER', '[6][7][8][9][10][11][12][13]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 10, 'DAYNO', '[26][27][28]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 10, 'PACKLIST_NO', '[14][15][16][17][18]');

INSERT INTO DETECTOR (OBJECT_SIGN, OBJECT_ID, PARAM_SIGN, VALUE_MASK)
  VALUES ('MESSAGE', 10, 'PARTNER_NUMBER', '[6][7][8][9][10][11][12][13]');



INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (180, 288, 'ORDERITEM_INDOUBT');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (189, 288, 'ORDERITEM_INDOUBT');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (288, 189, 'ORDERITEM_PREPACK');


