SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_ERROR', 'Ошибка в заявке', 'ORDERITEM', 'ORDERITEM_STORE');



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_ERROR', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_ERROR', 'NEW.STATUS_SIGN', 'V', 'ERROR');



UPDATE TEMPLATES
SET FILENAME_MASK = 'a[[:DIGIT:]]{8}[_][[:DIGIT:]]{2}.[[:DIGIT:]]{3}'
WHERE (TEMPLATE_ID = 2);

UPDATE TEMPLATES
SET FILENAME_MASK = 'n&#45;a[[:DIGIT:]]{8}[_][[:DIGIT:]]{2}.[[:DIGIT:]]{3}.[[:DIGIT:]]{3}'
WHERE (TEMPLATE_ID = 3);

UPDATE TEMPLATES
SET FILENAME_MASK = 'liefau[[:ALNUM :]]{2}[_][[:DIGIT:]]{8}.[[:DIGIT:]]{3}'
WHERE (TEMPLATE_ID = 4);

UPDATE TEMPLATES
SET FILENAME_MASK = 'packl[_][[:DIGIT:]]{8}.[[:DIGIT:]]{5}'
WHERE (TEMPLATE_ID = 5);

UPDATE TEMPLATES
SET FILENAME_MASK = 't&#45;cons[_][[:DIGIT:]]{8}.[[:DIGIT:]]{5}.[[:DIGIT:]]{5,6}'
WHERE (TEMPLATE_ID = 6);

UPDATE TEMPLATES
SET FILENAME_MASK = 'ob[[:LOWER:]][_][[:DIGIT:]]{2}.[[:DIGIT:]]{2,3}.txt'
WHERE (TEMPLATE_ID = 7);

UPDATE TEMPLATES
SET FILENAME_MASK = 'n&#45;s[[:DIGIT:]]{8}[_][[:DIGIT:]]{2}.[[:DIGIT:]]{3}.[[:DIGIT:]]{3}'
WHERE (TEMPLATE_ID = 8);

UPDATE TEMPLATES
SET FILENAME_MASK = 'info[_][[:DIGIT:]]{8}[_]artn[[:DIGIT:]]{3}.txt'
WHERE (TEMPLATE_ID = 9);

UPDATE TEMPLATES
SET FILENAME_MASK = 'info[_][[:DIGIT:]]{8}[_][[:DIGIT:]]{5}[_]2pay[_][[:DIGIT:]]{3}.txt'
WHERE (TEMPLATE_ID = 10);

UPDATE TEMPLATES
SET FILENAME_MASK = 'info[_][[:DIGIT:]]{8}[_]komnr[_][[:DIGIT:]]{3}.txt'
WHERE (TEMPLATE_ID = 14);

UPDATE TEMPLATES
SET FILENAME_MASK = 'info[_][[:DIGIT:]]{8}[_]art[_][[:DIGIT:]]{3}.txt'
WHERE (TEMPLATE_ID = 15);



INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '9', 'ERROR');



INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (175, 172, 'ORDERITEM_ERROR');



