/* Server version: WI-V6.3.1.26351 Firebird 2.5 
   SQLDialect: 3. ODS: 11.2. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 2048 (8192 Kb). Read-only: False. */
SET CLIENTLIB 'fbclient.dll';
SET NAMES CYRL;

SET SQL DIALECT 3;

CONNECT 'localhost:D:\Otto\Data.Etalon\OTTO_PPZ.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

SET AUTODDL ON;

/* Create Domains... */
CREATE DOMAIN ID_DEALER AS SMALLINT;

CREATE DOMAIN SIGN_DICT AS VARCHAR(255) CHARACTER SET ASCII;

/* Create Table... */
CREATE TABLE DEALERNOTIFIES(DEALERNOTIFY_ID ID_NOTIFY NOT NULL,
DEALER_ID ID_DEALER NOT NULL,
MESSAGE_ID ID_MESSAGE NOT NULL,
NOTIFY_TEXT VALUE_ATTR NOT NULL,
STATUS_ID ID_STATUS,
STATUS_DTM DTM_STATUS,
CREATE_DTM DTM_CREATE);


CREATE TABLE DEALERORDERS(PRODUCT_ID ID_PRODUCT NOT NULL,
DEALER_ID ID_DEALER NOT NULL,
ORDER_CODE_START CODE_ORDER NOT NULL,
ORDER_CODE_END CODE_ORDER NOT NULL);


CREATE TABLE DEALERS(DEALER_ID ID_DEALER NOT NULL,
DEALER_NAME NAME_OBJECT);



/* Create Procedure... */
SET TERM ^ ;

CREATE PROCEDURE ACT_DEALERNOTIFY_STORE(I_PARAM_ID TYPE OF ID_PARAM NOT NULL,
I_OBJECT_ID TYPE OF ID_OBJECT,
I_OBJECT_SIGN TYPE OF SIGN_OBJECT = 'DEALERNOTIFY')
 AS
 BEGIN EXIT; END
^


/* Create generator... */
SET TERM ; ^

CREATE GENERATOR SEQ_DEALERNOTIFY_ID;


/* Create Exception... */
CREATE EXCEPTION EX_UNKNOWN_SEQUENCENAME 'Unknown sequence name';


/* Create Primary Key... */
ALTER TABLE DEALERNOTIFIES ADD CONSTRAINT PK_DEALERNOTIFIES PRIMARY KEY (DEALERNOTIFY_ID);

ALTER TABLE DEALERORDERS ADD CONSTRAINT PK_DEALERORDERS PRIMARY KEY (PRODUCT_ID, DEALER_ID);

ALTER TABLE DEALERS ADD CONSTRAINT PK_DEALERS PRIMARY KEY (DEALER_ID);

/* Create Foreign Key... */
RECONNECT;

ALTER TABLE DEALERNOTIFIES ADD CONSTRAINT FK_DEALERNOTIFIES_DEALER FOREIGN KEY (DEALER_ID) REFERENCES DEALERS (DEALER_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE DEALERNOTIFIES ADD CONSTRAINT FK_DEALERNOTIFIES_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGES (MESSAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE DEALERNOTIFIES ADD CONSTRAINT FK_DEALERNOTIFIES_STATUS FOREIGN KEY (STATUS_ID) REFERENCES STATUSES (STATUS_ID) ON UPDATE CASCADE;

ALTER TABLE DEALERORDERS ADD CONSTRAINT FK_DEALERORDERS_DEALER FOREIGN KEY (DEALER_ID) REFERENCES DEALERS (DEALER_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE DEALERORDERS ADD CONSTRAINT FK_DEALERORDERS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID) ON UPDATE CASCADE;

/* Alter Procedure... */
/* Alter (ORDERTAX_READ) */
SET TERM ^ ;

ALTER PROCEDURE ORDERTAX_READ(I_OBJECT_ID TYPE OF ID_OBJECT)
 RETURNS(O_PARAM_NAME TYPE OF SIGN_OBJECT,
O_PARAM_VALUE TYPE OF VALUE_ATTR)
 AS
declare variable V_TAXSERV_ID type of ID_TAX;
declare variable V_TAXSERV_NAME type of NAME_REF;
declare variable V_STATUS_SIGN type of SIGN_OBJECT;
declare variable V_STATUS_NAME type of NAME_OBJECT;
declare variable V_COST_EUR type of MONEY_EUR;
declare variable V_BYR2EUR type of MONEY_BYR;
begin
  select ts.taxserv_id, ts.taxserv_name, s.status_sign, s.status_name,
         ot.cost_eur, o.byr2eur
    from ordertaxs ot
      inner join taxrates tr on (tr.taxrate_id = ot.taxrate_id)
      inner join taxservs ts on (ts.taxserv_id = tr.taxserv_id)
      inner join statuses s on (s.status_id = ot.status_id)
      inner join orders o on (o.order_id = ot.order_id)
    where ot.ordertax_id = :i_object_id
    into :v_taxserv_id, :v_taxserv_name, :v_status_sign, :v_status_name,
         :v_cost_eur, :v_byr2eur;

  o_param_name = 'TAXSERV_ID';
  o_param_value = :v_taxserv_id;
  suspend;
  o_param_name = 'TAXSERV_NAME';
  o_param_value = :v_taxserv_name;
  suspend;
  o_param_name = 'STATUS_SIGN';
  o_param_value = v_status_sign;
  suspend;
  o_param_name = 'STATUS_NAME';
  o_param_value = v_status_name;
  suspend;
  o_param_name = 'COST_BYR';
  select o_money_byr from money_eur2byr(:v_cost_eur, :v_byr2eur) into o_param_value;
  suspend;
end
^

/* Restore proc. body: ACT_DEALERNOTIFY_STORE */
ALTER PROCEDURE ACT_DEALERNOTIFY_STORE(I_PARAM_ID TYPE OF ID_PARAM NOT NULL,
I_OBJECT_ID TYPE OF ID_OBJECT,
I_OBJECT_SIGN TYPE OF SIGN_OBJECT = 'DEALERNOTIFY')
 AS
declare variable V_NOW_STATUS_ID type of ID_STATUS;
declare variable V_NEW_STATUS_ID type of ID_STATUS;
declare variable V_UPDATEABLE type of VALUE_BOOLEAN;
declare variable V_NOTIFY_TEXT type of VALUE_ATTR;
declare variable V_DEALER_ID type of ID_DEALER;
declare variable V_MESSAGE_ID type of ID_MESSAGE;
begin
  if (coalesce(i_object_id, 0) = 0) then i_object_id = gen_id(seq_dealernotify_id, 1);

  update paramheads set object_id = :i_object_id where param_id = :i_param_id;

  execute procedure param_set(:i_param_id, 'ID', :i_object_id);

  select status_id from dealernotifies where dealernotify_id = :i_object_id into :v_now_status_id;

  if (:v_now_status_id is null) then
  begin
    select o_value from param_get(:i_param_id, 'DEALER_ID') into :v_dealer_id;
    select o_value from param_get(:i_param_id, 'MESSAGE_ID') into :v_message_id;
    select o_value from param_get(:i_param_id, 'NOTIFY_TEXT') into :v_notify_text;
    select o_pattern from param_fillpattern(:i_param_id, :v_notify_text) into :v_notify_text;

    insert into dealernotifies (dealernotify_id, dealer_id, message_id, notify_text)
      values(:i_object_id, :v_dealer_id, :v_message_id, :v_notify_text)
      returning status_id
      into :v_new_status_id;
    v_updateable = 1;
  end
  else
  begin
    select o_updateable, o_new_status_id
      from object_updateable(:i_param_id, :v_now_status_id, :i_object_sign)
      into :v_updateable, :v_new_status_id;
  end

  if (v_updateable = 1) then
  begin
    execute procedure param_set(:i_param_id, 'STATUS_ID', :v_new_status_id);
    execute procedure object_put(:i_param_id);
  end
end
^

/* Creating trigger... */
CREATE TRIGGER DEALERNOTIFIES_BI0 FOR DEALERNOTIFIES
ACTIVE BEFORE INSERT POSITION 0 
AS
begin
  if (new.dealernotify_id is null) then
    new.dealernotify_id= gen_id(seq_dealernotify_id, 1);
  if (new.status_id is null) then
    select o_status_id from status_get_default('DEALERNOTIFY') into new.status_id;
  new.status_dtm = current_timestamp;
  new.create_dtm = current_timestamp;
end
^


/* Alter Procedure... */
/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO ANNA */
SET TERM ; ^

REVOKE ALL ON CLIENTNOTIFIES FROM ANNA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO CATRIN */
REVOKE ALL ON CLIENTNOTIFIES FROM CATRIN;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO ELENA */
REVOKE ALL ON CLIENTNOTIFIES FROM ELENA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO KATYA */
REVOKE ALL ON CLIENTNOTIFIES FROM KATYA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO LANA */
REVOKE ALL ON CLIENTNOTIFIES FROM LANA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO LENA */
REVOKE ALL ON CLIENTNOTIFIES FROM LENA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO NASTYA */
REVOKE ALL ON CLIENTNOTIFIES FROM NASTYA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO NASTYA17 */
REVOKE ALL ON CLIENTNOTIFIES FROM NASTYA17;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO NATA */
REVOKE ALL ON CLIENTNOTIFIES FROM NATA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO NATVL */
REVOKE ALL ON CLIENTNOTIFIES FROM NATVL;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO ND */
REVOKE ALL ON CLIENTNOTIFIES FROM ND;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO OKSANA */
REVOKE ALL ON CLIENTNOTIFIES FROM OKSANA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO PUBLIC */
REVOKE ALL ON CLIENTNOTIFIES FROM PUBLIC;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO SVETLANA */
REVOKE ALL ON CLIENTNOTIFIES FROM SVETLANA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO VALERY */
REVOKE ALL ON CLIENTNOTIFIES FROM VALERY;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO VIKA */
REVOKE ALL ON CLIENTNOTIFIES FROM VIKA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO YULYA */
REVOKE ALL ON CLIENTNOTIFIES FROM YULYA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO ANNA */
REVOKE ALL ON RECODE_MASKS FROM ANNA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO CATRIN */
REVOKE ALL ON RECODE_MASKS FROM CATRIN;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO ELENA */
REVOKE ALL ON RECODE_MASKS FROM ELENA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO KATYA */
REVOKE ALL ON RECODE_MASKS FROM KATYA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO LANA */
REVOKE ALL ON RECODE_MASKS FROM LANA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO LENA */
REVOKE ALL ON RECODE_MASKS FROM LENA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO NASTYA */
REVOKE ALL ON RECODE_MASKS FROM NASTYA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO NASTYA17 */
REVOKE ALL ON RECODE_MASKS FROM NASTYA17;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO NATA */
REVOKE ALL ON RECODE_MASKS FROM NATA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO NATVL */
REVOKE ALL ON RECODE_MASKS FROM NATVL;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO ND */
REVOKE ALL ON RECODE_MASKS FROM ND;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO OKSANA */
REVOKE ALL ON RECODE_MASKS FROM OKSANA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO PUBLIC */
REVOKE ALL ON RECODE_MASKS FROM PUBLIC;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO SVETLANA */
REVOKE ALL ON RECODE_MASKS FROM SVETLANA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO VALERY */
REVOKE ALL ON RECODE_MASKS FROM VALERY;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO VIKA */
REVOKE ALL ON RECODE_MASKS FROM VIKA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO YULYA */
REVOKE ALL ON RECODE_MASKS FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO ANNA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO ELENA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO KATYA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO LANA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO LENA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO NATA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO NATVL */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO ND */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO VALERY */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO VIKA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO YULYA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO ANNA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO ELENA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO KATYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO LANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO LENA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO NATA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO NATVL */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO ND */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO VALERY */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO VIKA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO YULYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO ANNA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO ELENA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO KATYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO LANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO LENA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO NATA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO NATVL */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO ND */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO VALERY */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO VIKA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO YULYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO ANNA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO CATRIN */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO ELENA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO KATYA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO LANA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO LENA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO NASTYA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO NATA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO NATVL */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO ND */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO OKSANA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO VALERY */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO VIKA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO YULYA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO ANNA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO ELENA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO KATYA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO LANA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO LENA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO NATA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO NATVL */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO ND */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO VALERY */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO VIKA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO YULYA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM YULYA;

/* Create(Add) privilege */
GRANT ALL ON DEALERNOTIFIES TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON DEALERORDERS TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON DEALERS TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON USERS TO NATVL;


