SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_APPROVE', 'BONUS_ID', 'F', 'select first 1 b.bonus_id
from bonuses b 
where b.client_id = [CLIENT_ID] and b.ordertax_id is null');


INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (10, 'ORDER_APPROVE', 0, 'BONUS_USE');


INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES (10, 'BONUS_ID', 'N', 'IS NOT', 'NULL', NULL);


INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (10, 'ID', 'A', 'BONUS_ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (10, 'ORDER_ID', 'A', 'ID');


DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 11);

