SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_DELIVERED', 'COST_EUR', 'F', 'select os.cost_eur from v_order_summary os where os.order_id = [ID]');



INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (36, 'ORDER_DELIVERED', 2, 'ORDERMONEY_STORE');



INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES (36, 'COST_EUR', 'N', '>', '0', NULL);

INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES (36, 'PRODUCT_ID', 'N', '=', '2', NULL);



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (36, 'ACCOUNT_ID', 'A', 'ACCOUNT_ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (36, 'AMOUNT_EUR', 'A', 'COST_EUR');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (36, 'ORDER_ID', 'A', 'ID');



INSERT INTO FLAGS (FLAG_SIGN, FLAG_NAME, GROUP_NO)
  VALUES ('DELIVERED', 'Доставлена', NULL);


INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (217, 'DELIVERED');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (218, 'DELIVERED');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (279, 'DELIVERED');


DELETE FROM STATUS_RULES
WHERE (OLD_STATUS_ID = 211) AND (NEW_STATUS_ID = 217);


DELETE FROM ACTIONCODE_PARAMS
WHERE (ACTION_SIGN = 'ORDERMONEY_STORE') AND (PARAM_NAME = 'ID') AND (PARAM_KIND = 'I');


