SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (189, 'ПреПаклист', 'ORDERITEM', NULL, 'PREPACKED', NULL, NULL, NULL);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (213, 'ПреПаклист', 'ORDER', NULL, 'PREPACKED', NULL, NULL, NULL);


COMMIT WORK;

UPDATE PRODUCTS
SET STATUS_ID = 155,
    STATUS_DTM = '31-JAN-2012 12:00:49'
WHERE (PRODUCT_ID = 2);


COMMIT WORK;

INSERT INTO PRODUCT_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (2, 1501, '73105050');


UPDATE TAXRATE_ATTRS
SET ATTR_VALUE = '7'
WHERE (OBJECT_ID = 5) AND (ATTR_ID = 1301);


COMMIT WORK;

