SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (505, 'PLACE', 'PLACETYPE_SIGN', 'Сигнатура типа населенного пункта', NULL, 'R');


COMMIT WORK;

UPDATE TEMPLATES
SET FILENAME_MASK = 'ob[[:LOWER:]]_[[:DIGIT:]]{2}.[[:DIGIT:]]{2,3}.txt'
WHERE (TEMPLATE_ID = 7);


COMMIT WORK;

