/* Server version: WI-V6.3.1.26351 Firebird 2.5 
SET CLIENTLIB 'fbclient.dll';
   SQLDialect: 3. ODS: 11.2. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 2048 (8192 Kb). Read-only: False. */
SET NAMES CYRL;

SET SQL DIALECT 3;

SET AUTODDL ON;

/* Alter Procedure... */
/* Alter (PLACE_READ) */
SET TERM ^ ;

ALTER PROCEDURE PLACE_READ(I_OBJECT_ID TYPE OF ID_OBJECT)
 RETURNS(O_PARAM_NAME TYPE OF SIGN_OBJECT,
O_PARAM_VALUE TYPE OF VALUE_ATTR)
 AS
declare variable V_REGION_NAME type of NAME_OBJECT;
declare variable V_AREA_NAME type of NAME_OBJECT;
declare variable V_PLACETYPE_SIGN type of NAME_SHORT;
begin
  select p.area_name, p.region_name, p.placetype_sign
    from v_places p
    where p.place_id = :i_object_id
    into :v_area_name, :v_region_name, :v_placetype_sign;

  if (:v_area_name is not null) then
  begin
    o_param_name = 'AREA_NAME';
    o_param_value = :v_area_name;
    suspend;
  end

  if (:v_region_name is not null) then
  begin
    o_param_name = 'REGION_NAME';
    o_param_value = :v_region_name;
    suspend;
  end

  o_param_name = 'PLACETYPE_SIGN';
  o_param_value = :v_placetype_sign;
  suspend;

end
^

/* Creating roles */
SET TERM ; ^

CREATE ROLE USERS;


/* Create(Add) Crant */
GRANT ALL ON ACCOPERS TO ELENA;

GRANT ALL ON ACCOPERS TO NASTYA;

GRANT ALL ON ACCOPERS TO NASTYA17;

GRANT ALL ON ACCOPERS TO NATVL;

GRANT ALL ON ACCOPERS TO ND;

GRANT ALL ON ACCOPERS TO USERS WITH GRANT OPTION;

GRANT ALL ON ACCOPERS TO YULYA;

GRANT ALL ON ACCOUNTS TO ELENA;

GRANT ALL ON ACCOUNTS TO NASTYA;

GRANT ALL ON ACCOUNTS TO NASTYA17;

GRANT ALL ON ACCOUNTS TO NATVL;

GRANT ALL ON ACCOUNTS TO ND;

GRANT ALL ON ACCOUNTS TO USERS WITH GRANT OPTION;

GRANT ALL ON ACCOUNTS TO YULYA;

GRANT ALL ON ACTION_ATTRS TO ELENA;

GRANT ALL ON ACTION_ATTRS TO NASTYA;

GRANT ALL ON ACTION_ATTRS TO NASTYA17;

GRANT ALL ON ACTION_ATTRS TO NATVL;

GRANT ALL ON ACTION_ATTRS TO ND;

GRANT ALL ON ACTION_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON ACTION_ATTRS TO YULYA;

GRANT ALL ON ACTIONCODE_CRITERIAS TO ELENA;

GRANT ALL ON ACTIONCODE_CRITERIAS TO NASTYA;

GRANT ALL ON ACTIONCODE_CRITERIAS TO NASTYA17;

GRANT ALL ON ACTIONCODE_CRITERIAS TO NATVL;

GRANT ALL ON ACTIONCODE_CRITERIAS TO ND;

GRANT ALL ON ACTIONCODE_CRITERIAS TO USERS WITH GRANT OPTION;

GRANT ALL ON ACTIONCODE_CRITERIAS TO YULYA;

GRANT ALL ON ACTIONCODE_PARAMS TO ELENA;

GRANT ALL ON ACTIONCODE_PARAMS TO NASTYA;

GRANT ALL ON ACTIONCODE_PARAMS TO NASTYA17;

GRANT ALL ON ACTIONCODE_PARAMS TO NATVL;

GRANT ALL ON ACTIONCODE_PARAMS TO ND;

GRANT ALL ON ACTIONCODE_PARAMS TO USERS WITH GRANT OPTION;

GRANT ALL ON ACTIONCODE_PARAMS TO YULYA;

GRANT ALL ON ACTIONCODES TO ELENA;

GRANT ALL ON ACTIONCODES TO NASTYA;

GRANT ALL ON ACTIONCODES TO NASTYA17;

GRANT ALL ON ACTIONCODES TO NATVL;

GRANT ALL ON ACTIONCODES TO ND;

GRANT ALL ON ACTIONCODES TO USERS WITH GRANT OPTION;

GRANT ALL ON ACTIONCODES TO YULYA;

GRANT ALL ON ACTIONS TO ELENA;

GRANT ALL ON ACTIONS TO NASTYA;

GRANT ALL ON ACTIONS TO NASTYA17;

GRANT ALL ON ACTIONS TO NATVL;

GRANT ALL ON ACTIONS TO ND;

GRANT ALL ON ACTIONS TO USERS WITH GRANT OPTION;

GRANT ALL ON ACTIONS TO YULYA;

GRANT ALL ON ACTIONTREE TO ELENA;

GRANT ALL ON ACTIONTREE TO NASTYA;

GRANT ALL ON ACTIONTREE TO NASTYA17;

GRANT ALL ON ACTIONTREE TO NATVL;

GRANT ALL ON ACTIONTREE TO ND;

GRANT ALL ON ACTIONTREE TO USERS WITH GRANT OPTION;

GRANT ALL ON ACTIONTREE TO YULYA;

GRANT ALL ON ACTIONTREE_CRITERIAS TO ELENA;

GRANT ALL ON ACTIONTREE_CRITERIAS TO NASTYA;

GRANT ALL ON ACTIONTREE_CRITERIAS TO NASTYA17;

GRANT ALL ON ACTIONTREE_CRITERIAS TO NATVL;

GRANT ALL ON ACTIONTREE_CRITERIAS TO ND;

GRANT ALL ON ACTIONTREE_CRITERIAS TO USERS WITH GRANT OPTION;

GRANT ALL ON ACTIONTREE_CRITERIAS TO YULYA;

GRANT ALL ON ACTIONTREE_PARAMS TO ELENA;

GRANT ALL ON ACTIONTREE_PARAMS TO NASTYA;

GRANT ALL ON ACTIONTREE_PARAMS TO NASTYA17;

GRANT ALL ON ACTIONTREE_PARAMS TO NATVL;

GRANT ALL ON ACTIONTREE_PARAMS TO ND;

GRANT ALL ON ACTIONTREE_PARAMS TO USERS WITH GRANT OPTION;

GRANT ALL ON ACTIONTREE_PARAMS TO YULYA;

GRANT ALL ON ADRESSES TO ELENA;

GRANT ALL ON ADRESSES TO NASTYA;

GRANT ALL ON ADRESSES TO NASTYA17;

GRANT ALL ON ADRESSES TO NATVL;

GRANT ALL ON ADRESSES TO ND;

GRANT ALL ON ADRESSES TO USERS WITH GRANT OPTION;

GRANT ALL ON ADRESSES TO YULYA;

GRANT ALL ON ARTICLE_ATTRS TO ELENA;

GRANT ALL ON ARTICLE_ATTRS TO NASTYA;

GRANT ALL ON ARTICLE_ATTRS TO NASTYA17;

GRANT ALL ON ARTICLE_ATTRS TO NATVL;

GRANT ALL ON ARTICLE_ATTRS TO ND;

GRANT ALL ON ARTICLE_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON ARTICLE_ATTRS TO YULYA;

GRANT ALL ON ARTICLECODE_ATTRS TO ELENA;

GRANT ALL ON ARTICLECODE_ATTRS TO NASTYA;

GRANT ALL ON ARTICLECODE_ATTRS TO NASTYA17;

GRANT ALL ON ARTICLECODE_ATTRS TO NATVL;

GRANT ALL ON ARTICLECODE_ATTRS TO ND;

GRANT ALL ON ARTICLECODE_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON ARTICLECODE_ATTRS TO YULYA;

GRANT ALL ON ARTICLECODES TO ELENA;

GRANT ALL ON ARTICLECODES TO NASTYA;

GRANT ALL ON ARTICLECODES TO NASTYA17;

GRANT ALL ON ARTICLECODES TO NATVL;

GRANT ALL ON ARTICLECODES TO ND;

GRANT ALL ON ARTICLECODES TO USERS WITH GRANT OPTION;

GRANT ALL ON ARTICLECODES TO YULYA;

GRANT ALL ON ARTICLEMASKS TO ELENA;

GRANT ALL ON ARTICLEMASKS TO NASTYA;

GRANT ALL ON ARTICLEMASKS TO NASTYA17;

GRANT ALL ON ARTICLEMASKS TO NATVL;

GRANT ALL ON ARTICLEMASKS TO ND;

GRANT ALL ON ARTICLEMASKS TO USERS WITH GRANT OPTION;

GRANT ALL ON ARTICLEMASKS TO YULYA;

GRANT ALL ON ARTICLES TO ELENA;

GRANT ALL ON ARTICLES TO NASTYA;

GRANT ALL ON ARTICLES TO NASTYA17;

GRANT ALL ON ARTICLES TO NATVL;

GRANT ALL ON ARTICLES TO ND;

GRANT ALL ON ARTICLES TO USERS WITH GRANT OPTION;

GRANT ALL ON ARTICLES TO YULYA;

GRANT ALL ON ARTICLESIGNS TO ELENA;

GRANT ALL ON ARTICLESIGNS TO NASTYA;

GRANT ALL ON ARTICLESIGNS TO NASTYA17;

GRANT ALL ON ARTICLESIGNS TO NATVL;

GRANT ALL ON ARTICLESIGNS TO ND;

GRANT ALL ON ARTICLESIGNS TO USERS WITH GRANT OPTION;

GRANT ALL ON ARTICLESIGNS TO YULYA;

GRANT ALL ON ATTRS TO ELENA;

GRANT ALL ON ATTRS TO NASTYA;

GRANT ALL ON ATTRS TO NASTYA17;

GRANT ALL ON ATTRS TO NATVL;

GRANT ALL ON ATTRS TO ND;

GRANT ALL ON ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON ATTRS TO YULYA;

GRANT ALL ON BUILDS TO ELENA;

GRANT ALL ON BUILDS TO NASTYA;

GRANT ALL ON BUILDS TO NASTYA17;

GRANT ALL ON BUILDS TO NATVL;

GRANT ALL ON BUILDS TO ND;

GRANT ALL ON BUILDS TO USERS WITH GRANT OPTION;

GRANT ALL ON BUILDS TO YULYA;

GRANT ALL ON CALCPOINTS TO ELENA;

GRANT ALL ON CALCPOINTS TO NASTYA;

GRANT ALL ON CALCPOINTS TO NASTYA17;

GRANT ALL ON CALCPOINTS TO NATVL;

GRANT ALL ON CALCPOINTS TO ND;

GRANT ALL ON CALCPOINTS TO USERS WITH GRANT OPTION;

GRANT ALL ON CALCPOINTS TO YULYA;

GRANT ALL ON CATALOG2PLUGIN TO ELENA;

GRANT ALL ON CATALOG2PLUGIN TO NASTYA;

GRANT ALL ON CATALOG2PLUGIN TO NASTYA17;

GRANT ALL ON CATALOG2PLUGIN TO NATVL;

GRANT ALL ON CATALOG2PLUGIN TO ND;

GRANT ALL ON CATALOG2PLUGIN TO USERS WITH GRANT OPTION;

GRANT ALL ON CATALOG2PLUGIN TO YULYA;

GRANT ALL ON CATALOGS TO ELENA;

GRANT ALL ON CATALOGS TO NASTYA;

GRANT ALL ON CATALOGS TO NASTYA17;

GRANT ALL ON CATALOGS TO NATVL;

GRANT ALL ON CATALOGS TO ND;

GRANT ALL ON CATALOGS TO USERS WITH GRANT OPTION;

GRANT ALL ON CATALOGS TO YULYA;

GRANT ALL ON CLIENT_ATTRS TO ELENA;

GRANT ALL ON CLIENT_ATTRS TO NASTYA;

GRANT ALL ON CLIENT_ATTRS TO NASTYA17;

GRANT ALL ON CLIENT_ATTRS TO NATVL;

GRANT ALL ON CLIENT_ATTRS TO ND;

GRANT ALL ON CLIENT_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON CLIENT_ATTRS TO YULYA;

GRANT ALL ON CLIENTS TO ELENA;

GRANT ALL ON CLIENTS TO NASTYA;

GRANT ALL ON CLIENTS TO NASTYA17;

GRANT ALL ON CLIENTS TO NATVL;

GRANT ALL ON CLIENTS TO ND;

GRANT ALL ON CLIENTS TO USERS WITH GRANT OPTION;

GRANT ALL ON CLIENTS TO YULYA;

GRANT ALL ON COUNTERS TO ELENA;

GRANT ALL ON COUNTERS TO NASTYA;

GRANT ALL ON COUNTERS TO NASTYA17;

GRANT ALL ON COUNTERS TO NATVL;

GRANT ALL ON COUNTERS TO ND;

GRANT ALL ON COUNTERS TO USERS WITH GRANT OPTION;

GRANT ALL ON COUNTERS TO YULYA;

GRANT ALL ON DETECTOR TO ELENA;

GRANT ALL ON DETECTOR TO NASTYA;

GRANT ALL ON DETECTOR TO NASTYA17;

GRANT ALL ON DETECTOR TO NATVL;

GRANT ALL ON DETECTOR TO ND;

GRANT ALL ON DETECTOR TO USERS WITH GRANT OPTION;

GRANT ALL ON DETECTOR TO YULYA;

GRANT ALL ON EVENTCODES TO ELENA;

GRANT ALL ON EVENTCODES TO NASTYA;

GRANT ALL ON EVENTCODES TO NASTYA17;

GRANT ALL ON EVENTCODES TO NATVL;

GRANT ALL ON EVENTCODES TO ND;

GRANT ALL ON EVENTCODES TO USERS WITH GRANT OPTION;

GRANT ALL ON EVENTCODES TO YULYA;

GRANT ALL ON EVENTS TO ELENA;

GRANT ALL ON EVENTS TO NASTYA;

GRANT ALL ON EVENTS TO NASTYA17;

GRANT ALL ON EVENTS TO NATVL;

GRANT ALL ON EVENTS TO ND;

GRANT ALL ON EVENTS TO USERS WITH GRANT OPTION;

GRANT ALL ON EVENTS TO YULYA;

GRANT ALL ON FLAGS TO ELENA;

GRANT ALL ON FLAGS TO NASTYA;

GRANT ALL ON FLAGS TO NASTYA17;

GRANT ALL ON FLAGS TO NATVL;

GRANT ALL ON FLAGS TO ND;

GRANT ALL ON FLAGS TO USERS WITH GRANT OPTION;

GRANT ALL ON FLAGS TO YULYA;

GRANT ALL ON FLAGS2STATUSES TO ELENA;

GRANT ALL ON FLAGS2STATUSES TO NASTYA;

GRANT ALL ON FLAGS2STATUSES TO NASTYA17;

GRANT ALL ON FLAGS2STATUSES TO NATVL;

GRANT ALL ON FLAGS2STATUSES TO ND;

GRANT ALL ON FLAGS2STATUSES TO USERS WITH GRANT OPTION;

GRANT ALL ON FLAGS2STATUSES TO YULYA;

GRANT ALL ON IMP_CITYGET TO ELENA;

GRANT ALL ON IMP_CITYGET TO NASTYA;

GRANT ALL ON IMP_CITYGET TO NASTYA17;

GRANT ALL ON IMP_CITYGET TO NATVL;

GRANT ALL ON IMP_CITYGET TO ND;

GRANT ALL ON IMP_CITYGET TO USERS WITH GRANT OPTION;

GRANT ALL ON IMP_CITYGET TO YULYA;

GRANT ALL ON IMP_CITYTYPE TO ELENA;

GRANT ALL ON IMP_CITYTYPE TO NASTYA;

GRANT ALL ON IMP_CITYTYPE TO NASTYA17;

GRANT ALL ON IMP_CITYTYPE TO NATVL;

GRANT ALL ON IMP_CITYTYPE TO ND;

GRANT ALL ON IMP_CITYTYPE TO USERS WITH GRANT OPTION;

GRANT ALL ON IMP_CITYTYPE TO YULYA;

GRANT ALL ON IMP_CLIENT TO ELENA;

GRANT ALL ON IMP_CLIENT TO NASTYA;

GRANT ALL ON IMP_CLIENT TO NASTYA17;

GRANT ALL ON IMP_CLIENT TO NATVL;

GRANT ALL ON IMP_CLIENT TO ND;

GRANT ALL ON IMP_CLIENT TO USERS WITH GRANT OPTION;

GRANT ALL ON IMP_CLIENT TO YULYA;

GRANT ALL ON IMP_OBLAST TO ELENA;

GRANT ALL ON IMP_OBLAST TO NASTYA;

GRANT ALL ON IMP_OBLAST TO NASTYA17;

GRANT ALL ON IMP_OBLAST TO NATVL;

GRANT ALL ON IMP_OBLAST TO ND;

GRANT ALL ON IMP_OBLAST TO USERS WITH GRANT OPTION;

GRANT ALL ON IMP_OBLAST TO YULYA;

GRANT ALL ON IMP_REGION TO ELENA;

GRANT ALL ON IMP_REGION TO NASTYA;

GRANT ALL ON IMP_REGION TO NASTYA17;

GRANT ALL ON IMP_REGION TO NATVL;

GRANT ALL ON IMP_REGION TO ND;

GRANT ALL ON IMP_REGION TO USERS WITH GRANT OPTION;

GRANT ALL ON IMP_REGION TO YULYA;

GRANT ALL ON LOGS TO ELENA;

GRANT ALL ON LOGS TO NASTYA;

GRANT ALL ON LOGS TO NASTYA17;

GRANT ALL ON LOGS TO NATVL;

GRANT ALL ON LOGS TO ND;

GRANT ALL ON LOGS TO USERS WITH GRANT OPTION;

GRANT ALL ON LOGS TO YULYA;

GRANT ALL ON MAGAZINES TO ELENA;

GRANT ALL ON MAGAZINES TO NASTYA;

GRANT ALL ON MAGAZINES TO NASTYA17;

GRANT ALL ON MAGAZINES TO NATVL;

GRANT ALL ON MAGAZINES TO ND;

GRANT ALL ON MAGAZINES TO USERS WITH GRANT OPTION;

GRANT ALL ON MAGAZINES TO YULYA;

GRANT ALL ON MESSAGE_ATTRS TO ELENA;

GRANT ALL ON MESSAGE_ATTRS TO NASTYA;

GRANT ALL ON MESSAGE_ATTRS TO NASTYA17;

GRANT ALL ON MESSAGE_ATTRS TO NATVL;

GRANT ALL ON MESSAGE_ATTRS TO ND;

GRANT ALL ON MESSAGE_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON MESSAGE_ATTRS TO YULYA;

GRANT ALL ON MESSAGES TO ELENA;

GRANT ALL ON MESSAGES TO NASTYA;

GRANT ALL ON MESSAGES TO NASTYA17;

GRANT ALL ON MESSAGES TO NATVL;

GRANT ALL ON MESSAGES TO ND;

GRANT ALL ON MESSAGES TO USERS WITH GRANT OPTION;

GRANT ALL ON MESSAGES TO YULYA;

GRANT ALL ON NOTIFIES TO ELENA;

GRANT ALL ON NOTIFIES TO NASTYA;

GRANT ALL ON NOTIFIES TO NASTYA17;

GRANT ALL ON NOTIFIES TO NATVL;

GRANT ALL ON NOTIFIES TO ND;

GRANT ALL ON NOTIFIES TO USERS WITH GRANT OPTION;

GRANT ALL ON NOTIFIES TO YULYA;

GRANT ALL ON OBJECTS TO ELENA;

GRANT ALL ON OBJECTS TO NASTYA;

GRANT ALL ON OBJECTS TO NASTYA17;

GRANT ALL ON OBJECTS TO NATVL;

GRANT ALL ON OBJECTS TO ND;

GRANT ALL ON OBJECTS TO USERS WITH GRANT OPTION;

GRANT ALL ON OBJECTS TO YULYA;

GRANT ALL ON ORDER_ATTRS TO ELENA;

GRANT ALL ON ORDER_ATTRS TO NASTYA;

GRANT ALL ON ORDER_ATTRS TO NASTYA17;

GRANT ALL ON ORDER_ATTRS TO NATVL;

GRANT ALL ON ORDER_ATTRS TO ND;

GRANT ALL ON ORDER_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON ORDER_ATTRS TO YULYA;

GRANT ALL ON ORDERHISTORY TO ELENA;

GRANT ALL ON ORDERHISTORY TO NASTYA;

GRANT ALL ON ORDERHISTORY TO NASTYA17;

GRANT ALL ON ORDERHISTORY TO NATVL;

GRANT ALL ON ORDERHISTORY TO ND;

GRANT ALL ON ORDERHISTORY TO USERS WITH GRANT OPTION;

GRANT ALL ON ORDERHISTORY TO YULYA;

GRANT ALL ON ORDERITEM_ATTRS TO ELENA;

GRANT ALL ON ORDERITEM_ATTRS TO NASTYA;

GRANT ALL ON ORDERITEM_ATTRS TO NASTYA17;

GRANT ALL ON ORDERITEM_ATTRS TO NATVL;

GRANT ALL ON ORDERITEM_ATTRS TO ND;

GRANT ALL ON ORDERITEM_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON ORDERITEM_ATTRS TO YULYA;

GRANT ALL ON ORDERITEMS TO ELENA;

GRANT ALL ON ORDERITEMS TO NASTYA;

GRANT ALL ON ORDERITEMS TO NASTYA17;

GRANT ALL ON ORDERITEMS TO NATVL;

GRANT ALL ON ORDERITEMS TO ND;

GRANT ALL ON ORDERITEMS TO USERS WITH GRANT OPTION;

GRANT ALL ON ORDERITEMS TO YULYA;

GRANT ALL ON ORDERMONEYS TO ELENA;

GRANT ALL ON ORDERMONEYS TO NASTYA;

GRANT ALL ON ORDERMONEYS TO NASTYA17;

GRANT ALL ON ORDERMONEYS TO NATVL;

GRANT ALL ON ORDERMONEYS TO ND;

GRANT ALL ON ORDERMONEYS TO USERS WITH GRANT OPTION;

GRANT ALL ON ORDERMONEYS TO YULYA;

GRANT ALL ON ORDERS TO ELENA;

GRANT ALL ON ORDERS TO NASTYA;

GRANT ALL ON ORDERS TO NASTYA17;

GRANT ALL ON ORDERS TO NATVL;

GRANT ALL ON ORDERS TO ND;

GRANT ALL ON ORDERS TO USERS WITH GRANT OPTION;

GRANT ALL ON ORDERS TO YULYA;

GRANT ALL ON ORDERTAXS TO ELENA;

GRANT ALL ON ORDERTAXS TO NASTYA;

GRANT ALL ON ORDERTAXS TO NASTYA17;

GRANT ALL ON ORDERTAXS TO NATVL;

GRANT ALL ON ORDERTAXS TO ND;

GRANT ALL ON ORDERTAXS TO USERS WITH GRANT OPTION;

GRANT ALL ON ORDERTAXS TO YULYA;

GRANT ALL ON PARAMACTIONS TO ELENA;

GRANT ALL ON PARAMACTIONS TO NASTYA;

GRANT ALL ON PARAMACTIONS TO NASTYA17;

GRANT ALL ON PARAMACTIONS TO NATVL;

GRANT ALL ON PARAMACTIONS TO ND;

GRANT ALL ON PARAMACTIONS TO USERS WITH GRANT OPTION;

GRANT ALL ON PARAMACTIONS TO YULYA;

GRANT ALL ON PARAMHEADS TO ELENA;

GRANT ALL ON PARAMHEADS TO NASTYA;

GRANT ALL ON PARAMHEADS TO NASTYA17;

GRANT ALL ON PARAMHEADS TO NATVL;

GRANT ALL ON PARAMHEADS TO ND;

GRANT ALL ON PARAMHEADS TO USERS WITH GRANT OPTION;

GRANT ALL ON PARAMHEADS TO YULYA;

GRANT ALL ON PARAMKINDS TO ELENA;

GRANT ALL ON PARAMKINDS TO NASTYA;

GRANT ALL ON PARAMKINDS TO NASTYA17;

GRANT ALL ON PARAMKINDS TO NATVL;

GRANT ALL ON PARAMKINDS TO ND;

GRANT ALL ON PARAMKINDS TO USERS WITH GRANT OPTION;

GRANT ALL ON PARAMKINDS TO YULYA;

GRANT ALL ON PARAMS TO ELENA;

GRANT ALL ON PARAMS TO NASTYA;

GRANT ALL ON PARAMS TO NASTYA17;

GRANT ALL ON PARAMS TO NATVL;

GRANT ALL ON PARAMS TO ND;

GRANT ALL ON PARAMS TO USERS WITH GRANT OPTION;

GRANT ALL ON PARAMS TO YULYA;

GRANT ALL ON PAYMENTS TO ELENA;

GRANT ALL ON PAYMENTS TO NASTYA;

GRANT ALL ON PAYMENTS TO NASTYA17;

GRANT ALL ON PAYMENTS TO NATVL;

GRANT ALL ON PAYMENTS TO ND;

GRANT ALL ON PAYMENTS TO USERS WITH GRANT OPTION;

GRANT ALL ON PAYMENTS TO YULYA;

GRANT ALL ON PHONEPREFIXES TO ELENA;

GRANT ALL ON PHONEPREFIXES TO NASTYA;

GRANT ALL ON PHONEPREFIXES TO NASTYA17;

GRANT ALL ON PHONEPREFIXES TO NATVL;

GRANT ALL ON PHONEPREFIXES TO ND;

GRANT ALL ON PHONEPREFIXES TO USERS WITH GRANT OPTION;

GRANT ALL ON PHONEPREFIXES TO YULYA;

GRANT ALL ON PHONETYPES TO ELENA;

GRANT ALL ON PHONETYPES TO NASTYA;

GRANT ALL ON PHONETYPES TO NASTYA17;

GRANT ALL ON PHONETYPES TO NATVL;

GRANT ALL ON PHONETYPES TO ND;

GRANT ALL ON PHONETYPES TO USERS WITH GRANT OPTION;

GRANT ALL ON PHONETYPES TO YULYA;

GRANT ALL ON PLACES TO ELENA;

GRANT ALL ON PLACES TO NASTYA;

GRANT ALL ON PLACES TO NASTYA17;

GRANT ALL ON PLACES TO NATVL;

GRANT ALL ON PLACES TO ND;

GRANT ALL ON PLACES TO USERS WITH GRANT OPTION;

GRANT ALL ON PLACES TO YULYA;

GRANT ALL ON PLACETYPES TO ELENA;

GRANT ALL ON PLACETYPES TO NASTYA;

GRANT ALL ON PLACETYPES TO NASTYA17;

GRANT ALL ON PLACETYPES TO NATVL;

GRANT ALL ON PLACETYPES TO ND;

GRANT ALL ON PLACETYPES TO USERS WITH GRANT OPTION;

GRANT ALL ON PLACETYPES TO YULYA;

GRANT ALL ON PLUGIN_PARAMS TO ELENA;

GRANT ALL ON PLUGIN_PARAMS TO NASTYA;

GRANT ALL ON PLUGIN_PARAMS TO NASTYA17;

GRANT ALL ON PLUGIN_PARAMS TO NATVL;

GRANT ALL ON PLUGIN_PARAMS TO ND;

GRANT ALL ON PLUGIN_PARAMS TO USERS WITH GRANT OPTION;

GRANT ALL ON PLUGIN_PARAMS TO YULYA;

GRANT ALL ON PLUGINS TO ELENA;

GRANT ALL ON PLUGINS TO NASTYA;

GRANT ALL ON PLUGINS TO NASTYA17;

GRANT ALL ON PLUGINS TO NATVL;

GRANT ALL ON PLUGINS TO ND;

GRANT ALL ON PLUGINS TO USERS WITH GRANT OPTION;

GRANT ALL ON PLUGINS TO YULYA;

GRANT ALL ON PORT2TEMPLATE TO ELENA;

GRANT ALL ON PORT2TEMPLATE TO NASTYA;

GRANT ALL ON PORT2TEMPLATE TO NASTYA17;

GRANT ALL ON PORT2TEMPLATE TO NATVL;

GRANT ALL ON PORT2TEMPLATE TO ND;

GRANT ALL ON PORT2TEMPLATE TO USERS WITH GRANT OPTION;

GRANT ALL ON PORT2TEMPLATE TO YULYA;

GRANT ALL ON PORTS TO ELENA;

GRANT ALL ON PORTS TO NASTYA;

GRANT ALL ON PORTS TO NASTYA17;

GRANT ALL ON PORTS TO NATVL;

GRANT ALL ON PORTS TO ND;

GRANT ALL ON PORTS TO USERS WITH GRANT OPTION;

GRANT ALL ON PORTS TO YULYA;

GRANT ALL ON PRODUCT_ATTRS TO ELENA;

GRANT ALL ON PRODUCT_ATTRS TO NASTYA;

GRANT ALL ON PRODUCT_ATTRS TO NASTYA17;

GRANT ALL ON PRODUCT_ATTRS TO NATVL;

GRANT ALL ON PRODUCT_ATTRS TO ND;

GRANT ALL ON PRODUCT_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON PRODUCT_ATTRS TO YULYA;

GRANT ALL ON PRODUCTS TO ELENA;

GRANT ALL ON PRODUCTS TO NASTYA;

GRANT ALL ON PRODUCTS TO NASTYA17;

GRANT ALL ON PRODUCTS TO NATVL;

GRANT ALL ON PRODUCTS TO ND;

GRANT ALL ON PRODUCTS TO USERS WITH GRANT OPTION;

GRANT ALL ON PRODUCTS TO YULYA;

GRANT ALL ON RECODES TO ELENA;

GRANT ALL ON RECODES TO NASTYA;

GRANT ALL ON RECODES TO NASTYA17;

GRANT ALL ON RECODES TO NATVL;

GRANT ALL ON RECODES TO ND;

GRANT ALL ON RECODES TO USERS WITH GRANT OPTION;

GRANT ALL ON RECODES TO YULYA;

GRANT ALL ON SEARCHES TO ELENA;

GRANT ALL ON SEARCHES TO NASTYA;

GRANT ALL ON SEARCHES TO NASTYA17;

GRANT ALL ON SEARCHES TO NATVL;

GRANT ALL ON SEARCHES TO ND;

GRANT ALL ON SEARCHES TO USERS WITH GRANT OPTION;

GRANT ALL ON SEARCHES TO YULYA;

GRANT ALL ON SESSIONS TO ELENA;

GRANT ALL ON SESSIONS TO NASTYA;

GRANT ALL ON SESSIONS TO NASTYA17;

GRANT ALL ON SESSIONS TO NATVL;

GRANT ALL ON SESSIONS TO ND;

GRANT ALL ON SESSIONS TO USERS WITH GRANT OPTION;

GRANT ALL ON SESSIONS TO YULYA;

GRANT ALL ON SETTINGS TO ELENA;

GRANT ALL ON SETTINGS TO NASTYA;

GRANT ALL ON SETTINGS TO NASTYA17;

GRANT ALL ON SETTINGS TO NATVL;

GRANT ALL ON SETTINGS TO ND;

GRANT ALL ON SETTINGS TO USERS WITH GRANT OPTION;

GRANT ALL ON SETTINGS TO YULYA;

GRANT ALL ON SETTINGSIGNS TO ELENA;

GRANT ALL ON SETTINGSIGNS TO NASTYA;

GRANT ALL ON SETTINGSIGNS TO NASTYA17;

GRANT ALL ON SETTINGSIGNS TO NATVL;

GRANT ALL ON SETTINGSIGNS TO ND;

GRANT ALL ON SETTINGSIGNS TO USERS WITH GRANT OPTION;

GRANT ALL ON SETTINGSIGNS TO YULYA;

GRANT ALL ON STATUS_RULES TO ELENA;

GRANT ALL ON STATUS_RULES TO NASTYA;

GRANT ALL ON STATUS_RULES TO NASTYA17;

GRANT ALL ON STATUS_RULES TO NATVL;

GRANT ALL ON STATUS_RULES TO ND;

GRANT ALL ON STATUS_RULES TO USERS WITH GRANT OPTION;

GRANT ALL ON STATUS_RULES TO YULYA;

GRANT ALL ON STATUSES TO ELENA;

GRANT ALL ON STATUSES TO NASTYA;

GRANT ALL ON STATUSES TO NASTYA17;

GRANT ALL ON STATUSES TO NATVL;

GRANT ALL ON STATUSES TO ND;

GRANT ALL ON STATUSES TO USERS WITH GRANT OPTION;

GRANT ALL ON STATUSES TO YULYA;

GRANT ALL ON STREETTYPES TO ELENA;

GRANT ALL ON STREETTYPES TO NASTYA;

GRANT ALL ON STREETTYPES TO NASTYA17;

GRANT ALL ON STREETTYPES TO NATVL;

GRANT ALL ON STREETTYPES TO ND;

GRANT ALL ON STREETTYPES TO USERS WITH GRANT OPTION;

GRANT ALL ON STREETTYPES TO YULYA;

GRANT ALL ON TAXPLANS TO ELENA;

GRANT ALL ON TAXPLANS TO NASTYA;

GRANT ALL ON TAXPLANS TO NASTYA17;

GRANT ALL ON TAXPLANS TO NATVL;

GRANT ALL ON TAXPLANS TO ND;

GRANT ALL ON TAXPLANS TO USERS WITH GRANT OPTION;

GRANT ALL ON TAXPLANS TO YULYA;

GRANT ALL ON TAXRATE_ATTRS TO ELENA;

GRANT ALL ON TAXRATE_ATTRS TO NASTYA;

GRANT ALL ON TAXRATE_ATTRS TO NASTYA17;

GRANT ALL ON TAXRATE_ATTRS TO NATVL;

GRANT ALL ON TAXRATE_ATTRS TO ND;

GRANT ALL ON TAXRATE_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON TAXRATE_ATTRS TO YULYA;

GRANT ALL ON TAXRATES TO ELENA;

GRANT ALL ON TAXRATES TO NASTYA;

GRANT ALL ON TAXRATES TO NASTYA17;

GRANT ALL ON TAXRATES TO NATVL;

GRANT ALL ON TAXRATES TO ND;

GRANT ALL ON TAXRATES TO USERS WITH GRANT OPTION;

GRANT ALL ON TAXRATES TO YULYA;

GRANT ALL ON TAXSERVS TO ELENA;

GRANT ALL ON TAXSERVS TO NASTYA;

GRANT ALL ON TAXSERVS TO NASTYA17;

GRANT ALL ON TAXSERVS TO NATVL;

GRANT ALL ON TAXSERVS TO ND;

GRANT ALL ON TAXSERVS TO USERS WITH GRANT OPTION;

GRANT ALL ON TAXSERVS TO YULYA;

GRANT ALL ON TEMPLATES TO ELENA;

GRANT ALL ON TEMPLATES TO NASTYA;

GRANT ALL ON TEMPLATES TO NASTYA17;

GRANT ALL ON TEMPLATES TO NATVL;

GRANT ALL ON TEMPLATES TO ND;

GRANT ALL ON TEMPLATES TO USERS WITH GRANT OPTION;

GRANT ALL ON TEMPLATES TO YULYA;

GRANT ALL ON TMP_OTTO_ARTICLE TO ELENA;

GRANT ALL ON TMP_OTTO_ARTICLE TO NASTYA;

GRANT ALL ON TMP_OTTO_ARTICLE TO NASTYA17;

GRANT ALL ON TMP_OTTO_ARTICLE TO NATVL;

GRANT ALL ON TMP_OTTO_ARTICLE TO ND;

GRANT ALL ON TMP_OTTO_ARTICLE TO USERS WITH GRANT OPTION;

GRANT ALL ON TMP_OTTO_ARTICLE TO YULYA;

GRANT ALL ON TMP_SEARCHES TO ELENA;

GRANT ALL ON TMP_SEARCHES TO NASTYA;

GRANT ALL ON TMP_SEARCHES TO NASTYA17;

GRANT ALL ON TMP_SEARCHES TO NATVL;

GRANT ALL ON TMP_SEARCHES TO ND;

GRANT ALL ON TMP_SEARCHES TO USERS WITH GRANT OPTION;

GRANT ALL ON TMP_SEARCHES TO YULYA;

GRANT ALL ON USERS TO ELENA;

GRANT ALL ON USERS TO NASTYA;

GRANT ALL ON USERS TO NASTYA17;

GRANT ALL ON USERS TO NATVL;

GRANT ALL ON USERS TO ND;

GRANT ALL ON USERS TO USERS WITH GRANT OPTION;

GRANT ALL ON USERS TO YULYA;

GRANT ALL ON V_ACTION_ATTRS TO ELENA;

GRANT ALL ON V_ACTION_ATTRS TO NASTYA;

GRANT ALL ON V_ACTION_ATTRS TO NASTYA17;

GRANT ALL ON V_ACTION_ATTRS TO NATVL;

GRANT ALL ON V_ACTION_ATTRS TO ND;

GRANT ALL ON V_ACTION_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ACTION_ATTRS TO YULYA;

GRANT ALL ON V_ADRESS_TEXT TO ELENA;

GRANT ALL ON V_ADRESS_TEXT TO NASTYA;

GRANT ALL ON V_ADRESS_TEXT TO NASTYA17;

GRANT ALL ON V_ADRESS_TEXT TO NATVL;

GRANT ALL ON V_ADRESS_TEXT TO ND;

GRANT ALL ON V_ADRESS_TEXT TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ADRESS_TEXT TO YULYA;

GRANT ALL ON V_ARTICLES TO ELENA;

GRANT ALL ON V_ARTICLES TO NASTYA;

GRANT ALL ON V_ARTICLES TO NASTYA17;

GRANT ALL ON V_ARTICLES TO NATVL;

GRANT ALL ON V_ARTICLES TO ND;

GRANT ALL ON V_ARTICLES TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ARTICLES TO YULYA;

GRANT ALL ON V_ATTRINPARAM TO ELENA;

GRANT ALL ON V_ATTRINPARAM TO NASTYA;

GRANT ALL ON V_ATTRINPARAM TO NASTYA17;

GRANT ALL ON V_ATTRINPARAM TO NATVL;

GRANT ALL ON V_ATTRINPARAM TO ND;

GRANT ALL ON V_ATTRINPARAM TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ATTRINPARAM TO YULYA;

GRANT ALL ON V_CLIENT_ATTRS TO ELENA;

GRANT ALL ON V_CLIENT_ATTRS TO NASTYA;

GRANT ALL ON V_CLIENT_ATTRS TO NASTYA17;

GRANT ALL ON V_CLIENT_ATTRS TO NATVL;

GRANT ALL ON V_CLIENT_ATTRS TO ND;

GRANT ALL ON V_CLIENT_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_CLIENT_ATTRS TO YULYA;

GRANT ALL ON V_CLIENTADRESS TO ELENA;

GRANT ALL ON V_CLIENTADRESS TO NASTYA;

GRANT ALL ON V_CLIENTADRESS TO NASTYA17;

GRANT ALL ON V_CLIENTADRESS TO NATVL;

GRANT ALL ON V_CLIENTADRESS TO ND;

GRANT ALL ON V_CLIENTADRESS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_CLIENTADRESS TO YULYA;

GRANT ALL ON V_CLIENTS_FIO TO ELENA;

GRANT ALL ON V_CLIENTS_FIO TO NASTYA;

GRANT ALL ON V_CLIENTS_FIO TO NASTYA17;

GRANT ALL ON V_CLIENTS_FIO TO NATVL;

GRANT ALL ON V_CLIENTS_FIO TO ND;

GRANT ALL ON V_CLIENTS_FIO TO USERS WITH GRANT OPTION;

GRANT ALL ON V_CLIENTS_FIO TO YULYA;

GRANT ALL ON V_ORDER_ATTRS TO ELENA;

GRANT ALL ON V_ORDER_ATTRS TO NASTYA;

GRANT ALL ON V_ORDER_ATTRS TO NASTYA17;

GRANT ALL ON V_ORDER_ATTRS TO NATVL;

GRANT ALL ON V_ORDER_ATTRS TO ND;

GRANT ALL ON V_ORDER_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ORDER_ATTRS TO YULYA;

GRANT ALL ON V_ORDER_FULL_SPECIFICATION TO ELENA;

GRANT ALL ON V_ORDER_FULL_SPECIFICATION TO NASTYA;

GRANT ALL ON V_ORDER_FULL_SPECIFICATION TO NASTYA17;

GRANT ALL ON V_ORDER_FULL_SPECIFICATION TO NATVL;

GRANT ALL ON V_ORDER_FULL_SPECIFICATION TO ND;

GRANT ALL ON V_ORDER_FULL_SPECIFICATION TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ORDER_FULL_SPECIFICATION TO YULYA;

GRANT ALL ON V_ORDER_INVOICEABLE TO ELENA;

GRANT ALL ON V_ORDER_INVOICEABLE TO NASTYA;

GRANT ALL ON V_ORDER_INVOICEABLE TO NASTYA17;

GRANT ALL ON V_ORDER_INVOICEABLE TO NATVL;

GRANT ALL ON V_ORDER_INVOICEABLE TO ND;

GRANT ALL ON V_ORDER_INVOICEABLE TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ORDER_INVOICEABLE TO YULYA;

GRANT ALL ON V_ORDER_PAID TO ELENA;

GRANT ALL ON V_ORDER_PAID TO NASTYA;

GRANT ALL ON V_ORDER_PAID TO NASTYA17;

GRANT ALL ON V_ORDER_PAID TO NATVL;

GRANT ALL ON V_ORDER_PAID TO ND;

GRANT ALL ON V_ORDER_PAID TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ORDER_PAID TO YULYA;

GRANT ALL ON V_ORDER_SUMMARY TO ELENA;

GRANT ALL ON V_ORDER_SUMMARY TO NASTYA;

GRANT ALL ON V_ORDER_SUMMARY TO NASTYA17;

GRANT ALL ON V_ORDER_SUMMARY TO NATVL;

GRANT ALL ON V_ORDER_SUMMARY TO ND;

GRANT ALL ON V_ORDER_SUMMARY TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ORDER_SUMMARY TO YULYA;

GRANT ALL ON V_ORDERITEM_ATTRS TO ELENA;

GRANT ALL ON V_ORDERITEM_ATTRS TO NASTYA;

GRANT ALL ON V_ORDERITEM_ATTRS TO NASTYA17;

GRANT ALL ON V_ORDERITEM_ATTRS TO NATVL;

GRANT ALL ON V_ORDERITEM_ATTRS TO ND;

GRANT ALL ON V_ORDERITEM_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ORDERITEM_ATTRS TO YULYA;

GRANT ALL ON V_ORDERS TO ELENA;

GRANT ALL ON V_ORDERS TO NASTYA;

GRANT ALL ON V_ORDERS TO NASTYA17;

GRANT ALL ON V_ORDERS TO NATVL;

GRANT ALL ON V_ORDERS TO ND;

GRANT ALL ON V_ORDERS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ORDERS TO YULYA;

GRANT ALL ON V_PLACE_TEXT TO ELENA;

GRANT ALL ON V_PLACE_TEXT TO NASTYA;

GRANT ALL ON V_PLACE_TEXT TO NASTYA17;

GRANT ALL ON V_PLACE_TEXT TO NATVL;

GRANT ALL ON V_PLACE_TEXT TO ND;

GRANT ALL ON V_PLACE_TEXT TO USERS WITH GRANT OPTION;

GRANT ALL ON V_PLACE_TEXT TO YULYA;

GRANT ALL ON V_PLACES TO ELENA;

GRANT ALL ON V_PLACES TO NASTYA;

GRANT ALL ON V_PLACES TO NASTYA17;

GRANT ALL ON V_PLACES TO NATVL;

GRANT ALL ON V_PLACES TO ND;

GRANT ALL ON V_PLACES TO USERS WITH GRANT OPTION;

GRANT ALL ON V_PLACES TO YULYA;

GRANT ALL ON V_SETTINGS TO ELENA;

GRANT ALL ON V_SETTINGS TO NASTYA;

GRANT ALL ON V_SETTINGS TO NASTYA17;

GRANT ALL ON V_SETTINGS TO NATVL;

GRANT ALL ON V_SETTINGS TO ND;

GRANT ALL ON V_SETTINGS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_SETTINGS TO YULYA;

GRANT ALL ON V_STATUS_AVAILABLE TO ELENA;

GRANT ALL ON V_STATUS_AVAILABLE TO NASTYA;

GRANT ALL ON V_STATUS_AVAILABLE TO NASTYA17;

GRANT ALL ON V_STATUS_AVAILABLE TO NATVL;

GRANT ALL ON V_STATUS_AVAILABLE TO ND;

GRANT ALL ON V_STATUS_AVAILABLE TO USERS WITH GRANT OPTION;

GRANT ALL ON V_STATUS_AVAILABLE TO YULYA;

GRANT ALL ON V_STATUSES TO ELENA;

GRANT ALL ON V_STATUSES TO NASTYA;

GRANT ALL ON V_STATUSES TO NASTYA17;

GRANT ALL ON V_STATUSES TO NATVL;

GRANT ALL ON V_STATUSES TO ND;

GRANT ALL ON V_STATUSES TO USERS WITH GRANT OPTION;

GRANT ALL ON V_STATUSES TO YULYA;

GRANT ALL ON V_TAXRATE_ATTRS TO ELENA;

GRANT ALL ON V_TAXRATE_ATTRS TO NASTYA;

GRANT ALL ON V_TAXRATE_ATTRS TO NASTYA17;

GRANT ALL ON V_TAXRATE_ATTRS TO NATVL;

GRANT ALL ON V_TAXRATE_ATTRS TO ND;

GRANT ALL ON V_TAXRATE_ATTRS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_TAXRATE_ATTRS TO YULYA;

GRANT ALL ON VALUTES TO ELENA;

GRANT ALL ON VALUTES TO NASTYA;

GRANT ALL ON VALUTES TO NASTYA17;

GRANT ALL ON VALUTES TO NATVL;

GRANT ALL ON VALUTES TO ND;

GRANT ALL ON VALUTES TO USERS WITH GRANT OPTION;

GRANT ALL ON VALUTES TO YULYA;

GRANT ALL ON VENDORS TO ELENA;

GRANT ALL ON VENDORS TO NASTYA;

GRANT ALL ON VENDORS TO NASTYA17;

GRANT ALL ON VENDORS TO NATVL;

GRANT ALL ON VENDORS TO ND;

GRANT ALL ON VENDORS TO USERS WITH GRANT OPTION;

GRANT ALL ON VENDORS TO YULYA;

GRANT EXECUTE ON PROCEDURE AALL_CLEAR TO ELENA;

GRANT EXECUTE ON PROCEDURE AALL_CLEAR TO NASTYA;

GRANT EXECUTE ON PROCEDURE AALL_CLEAR TO NASTYA17;

GRANT EXECUTE ON PROCEDURE AALL_CLEAR TO NATVL;

GRANT EXECUTE ON PROCEDURE AALL_CLEAR TO ND;

GRANT EXECUTE ON PROCEDURE AALL_CLEAR TO YULYA;

GRANT EXECUTE ON PROCEDURE ACCOUNT_X_SEARCH TO ELENA;

GRANT EXECUTE ON PROCEDURE ACCOUNT_X_SEARCH TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACCOUNT_X_SEARCH TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACCOUNT_X_SEARCH TO NATVL;

GRANT EXECUTE ON PROCEDURE ACCOUNT_X_SEARCH TO ND;

GRANT EXECUTE ON PROCEDURE ACCOUNT_X_SEARCH TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDIT TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDIT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDIT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDIT TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDIT TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDIT TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDITORDER TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDITORDER TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDITORDER TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDITORDER TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDITORDER TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_CREDITORDER TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBIT TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBIT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBIT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBIT TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBIT TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBIT TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBITORDER TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBITORDER TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBITORDER TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBITORDER TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBITORDER TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_DEBITORDER TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_PAYMENTIN TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_PAYMENTIN TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_PAYMENTIN TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_PAYMENTIN TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_PAYMENTIN TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_PAYMENTIN TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ACCOUNT_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ADRESS_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ADRESS_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ADRESS_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ADRESS_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ADRESS_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ADRESS_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_CLIENT_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_CLIENT_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_CLIENT_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_CLIENT_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_CLIENT_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_CLIENT_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_EVENT_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_EVENT_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_EVENT_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_EVENT_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_EVENT_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_EVENT_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_MAGAZINE_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_MAGAZINE_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_MAGAZINE_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_MAGAZINE_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_MAGAZINE_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_MAGAZINE_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_MESSAGE_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_MESSAGE_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_MESSAGE_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_MESSAGE_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_MESSAGE_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_MESSAGE_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_DEBIT TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_DEBIT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_DEBIT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_DEBIT TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_DEBIT TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_DEBIT TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERITEM TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERITEM TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERITEM TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERITEM TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERITEM TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERITEM TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERTAX TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERTAX TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERTAX TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERTAX TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERTAX TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_ORDERTAX TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_TAXRATE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_TAXRATE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_TAXRATE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_TAXRATE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_TAXRATE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_FOREACH_TAXRATE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDER_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERITEM_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERITEM_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERITEM_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDERITEM_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDERITEM_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDERITEM_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_CREDIT TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_CREDIT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_CREDIT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_CREDIT TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_CREDIT TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_CREDIT TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_DEBIT TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_DEBIT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_DEBIT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_DEBIT TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_DEBIT TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_DEBIT TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDERMONEY_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERTAX_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERTAX_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_ORDERTAX_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_ORDERTAX_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_ORDERTAX_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_ORDERTAX_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_PAYMENT_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_PAYMENT_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_PAYMENT_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_PAYMENT_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_PAYMENT_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_PAYMENT_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACT_PLACE_STORE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACT_PLACE_STORE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACT_PLACE_STORE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACT_PLACE_STORE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACT_PLACE_STORE TO ND;

GRANT EXECUTE ON PROCEDURE ACT_PLACE_STORE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACTION_DETECT TO ELENA;

GRANT EXECUTE ON PROCEDURE ACTION_DETECT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACTION_DETECT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACTION_DETECT TO NATVL;

GRANT EXECUTE ON PROCEDURE ACTION_DETECT TO ND;

GRANT EXECUTE ON PROCEDURE ACTION_DETECT TO YULYA;

GRANT EXECUTE ON PROCEDURE ACTION_EXECUTE TO ELENA;

GRANT EXECUTE ON PROCEDURE ACTION_EXECUTE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACTION_EXECUTE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACTION_EXECUTE TO NATVL;

GRANT EXECUTE ON PROCEDURE ACTION_EXECUTE TO ND;

GRANT EXECUTE ON PROCEDURE ACTION_EXECUTE TO YULYA;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN TO ELENA;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN TO NATVL;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN TO ND;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN TO YULYA;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN_ACTION TO ELENA;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN_ACTION TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN_ACTION TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN_ACTION TO NATVL;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN_ACTION TO ND;

GRANT EXECUTE ON PROCEDURE ACTION_RERUN_ACTION TO YULYA;

GRANT EXECUTE ON PROCEDURE ACTION_RUN TO ELENA;

GRANT EXECUTE ON PROCEDURE ACTION_RUN TO NASTYA;

GRANT EXECUTE ON PROCEDURE ACTION_RUN TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ACTION_RUN TO NATVL;

GRANT EXECUTE ON PROCEDURE ACTION_RUN TO ND;

GRANT EXECUTE ON PROCEDURE ACTION_RUN TO YULYA;

GRANT EXECUTE ON PROCEDURE ARTICLE_GOC TO ELENA;

GRANT EXECUTE ON PROCEDURE ARTICLE_GOC TO NASTYA;

GRANT EXECUTE ON PROCEDURE ARTICLE_GOC TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ARTICLE_GOC TO NATVL;

GRANT EXECUTE ON PROCEDURE ARTICLE_GOC TO ND;

GRANT EXECUTE ON PROCEDURE ARTICLE_GOC TO YULYA;

GRANT EXECUTE ON PROCEDURE ARTICLECODE_GOC TO ELENA;

GRANT EXECUTE ON PROCEDURE ARTICLECODE_GOC TO NASTYA;

GRANT EXECUTE ON PROCEDURE ARTICLECODE_GOC TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ARTICLECODE_GOC TO NATVL;

GRANT EXECUTE ON PROCEDURE ARTICLECODE_GOC TO ND;

GRANT EXECUTE ON PROCEDURE ARTICLECODE_GOC TO YULYA;

GRANT EXECUTE ON PROCEDURE ARTICLES_PUMP TO ELENA;

GRANT EXECUTE ON PROCEDURE ARTICLES_PUMP TO NASTYA;

GRANT EXECUTE ON PROCEDURE ARTICLES_PUMP TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ARTICLES_PUMP TO NATVL;

GRANT EXECUTE ON PROCEDURE ARTICLES_PUMP TO ND;

GRANT EXECUTE ON PROCEDURE ARTICLES_PUMP TO YULYA;

GRANT EXECUTE ON PROCEDURE ARTICLESIGN_DETECT TO ELENA;

GRANT EXECUTE ON PROCEDURE ARTICLESIGN_DETECT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ARTICLESIGN_DETECT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ARTICLESIGN_DETECT TO NATVL;

GRANT EXECUTE ON PROCEDURE ARTICLESIGN_DETECT TO ND;

GRANT EXECUTE ON PROCEDURE ARTICLESIGN_DETECT TO YULYA;

GRANT EXECUTE ON PROCEDURE ATTR_PUT TO ELENA;

GRANT EXECUTE ON PROCEDURE ATTR_PUT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ATTR_PUT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ATTR_PUT TO NATVL;

GRANT EXECUTE ON PROCEDURE ATTR_PUT TO ND;

GRANT EXECUTE ON PROCEDURE ATTR_PUT TO YULYA;

GRANT EXECUTE ON PROCEDURE COUNTER_NEXTVAL TO ELENA;

GRANT EXECUTE ON PROCEDURE COUNTER_NEXTVAL TO NASTYA;

GRANT EXECUTE ON PROCEDURE COUNTER_NEXTVAL TO NASTYA17;

GRANT EXECUTE ON PROCEDURE COUNTER_NEXTVAL TO NATVL;

GRANT EXECUTE ON PROCEDURE COUNTER_NEXTVAL TO ND;

GRANT EXECUTE ON PROCEDURE COUNTER_NEXTVAL TO YULYA;

GRANT EXECUTE ON PROCEDURE IMP_CLIENTS TO ELENA;

GRANT EXECUTE ON PROCEDURE IMP_CLIENTS TO NASTYA;

GRANT EXECUTE ON PROCEDURE IMP_CLIENTS TO NASTYA17;

GRANT EXECUTE ON PROCEDURE IMP_CLIENTS TO NATVL;

GRANT EXECUTE ON PROCEDURE IMP_CLIENTS TO ND;

GRANT EXECUTE ON PROCEDURE IMP_CLIENTS TO YULYA;

GRANT EXECUTE ON PROCEDURE LOG_CREATE TO ELENA;

GRANT EXECUTE ON PROCEDURE LOG_CREATE TO NASTYA;

GRANT EXECUTE ON PROCEDURE LOG_CREATE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE LOG_CREATE TO NATVL;

GRANT EXECUTE ON PROCEDURE LOG_CREATE TO ND;

GRANT EXECUTE ON PROCEDURE LOG_CREATE TO YULYA;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE TO ELENA;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE TO NASTYA;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE TO NATVL;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE TO ND;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE TO YULYA;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE_SKIPED TO ELENA;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE_SKIPED TO NASTYA;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE_SKIPED TO NASTYA17;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE_SKIPED TO NATVL;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE_SKIPED TO ND;

GRANT EXECUTE ON PROCEDURE LOG_UPDATE_SKIPED TO YULYA;

GRANT EXECUTE ON PROCEDURE MAGAZINE_DETECT TO ELENA;

GRANT EXECUTE ON PROCEDURE MAGAZINE_DETECT TO NASTYA;

GRANT EXECUTE ON PROCEDURE MAGAZINE_DETECT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE MAGAZINE_DETECT TO NATVL;

GRANT EXECUTE ON PROCEDURE MAGAZINE_DETECT TO ND;

GRANT EXECUTE ON PROCEDURE MAGAZINE_DETECT TO YULYA;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY TO ELENA;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY TO NASTYA;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY TO NASTYA17;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY TO NATVL;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY TO ND;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY TO YULYA;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY_2 TO ELENA;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY_2 TO NASTYA;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY_2 TO NASTYA17;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY_2 TO NATVL;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY_2 TO ND;

GRANT EXECUTE ON PROCEDURE MESSAGE_BUSY_2 TO YULYA;

GRANT EXECUTE ON PROCEDURE MESSAGE_CREATE TO ELENA;

GRANT EXECUTE ON PROCEDURE MESSAGE_CREATE TO NASTYA;

GRANT EXECUTE ON PROCEDURE MESSAGE_CREATE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE MESSAGE_CREATE TO NATVL;

GRANT EXECUTE ON PROCEDURE MESSAGE_CREATE TO ND;

GRANT EXECUTE ON PROCEDURE MESSAGE_CREATE TO YULYA;

GRANT EXECUTE ON PROCEDURE MESSAGE_RELEASE TO ELENA;

GRANT EXECUTE ON PROCEDURE MESSAGE_RELEASE TO NASTYA;

GRANT EXECUTE ON PROCEDURE MESSAGE_RELEASE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE MESSAGE_RELEASE TO NATVL;

GRANT EXECUTE ON PROCEDURE MESSAGE_RELEASE TO ND;

GRANT EXECUTE ON PROCEDURE MESSAGE_RELEASE TO YULYA;

GRANT EXECUTE ON PROCEDURE NOTIFY_CREATE TO ELENA;

GRANT EXECUTE ON PROCEDURE NOTIFY_CREATE TO NASTYA;

GRANT EXECUTE ON PROCEDURE NOTIFY_CREATE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE NOTIFY_CREATE TO NATVL;

GRANT EXECUTE ON PROCEDURE NOTIFY_CREATE TO ND;

GRANT EXECUTE ON PROCEDURE NOTIFY_CREATE TO YULYA;

GRANT EXECUTE ON PROCEDURE NOTIFY_QUERY TO ELENA;

GRANT EXECUTE ON PROCEDURE NOTIFY_QUERY TO NASTYA;

GRANT EXECUTE ON PROCEDURE NOTIFY_QUERY TO NASTYA17;

GRANT EXECUTE ON PROCEDURE NOTIFY_QUERY TO NATVL;

GRANT EXECUTE ON PROCEDURE NOTIFY_QUERY TO ND;

GRANT EXECUTE ON PROCEDURE NOTIFY_QUERY TO YULYA;

GRANT EXECUTE ON PROCEDURE OBJECT_GET TO ELENA;

GRANT EXECUTE ON PROCEDURE OBJECT_GET TO NASTYA;

GRANT EXECUTE ON PROCEDURE OBJECT_GET TO NASTYA17;

GRANT EXECUTE ON PROCEDURE OBJECT_GET TO NATVL;

GRANT EXECUTE ON PROCEDURE OBJECT_GET TO ND;

GRANT EXECUTE ON PROCEDURE OBJECT_GET TO YULYA;

GRANT EXECUTE ON PROCEDURE OBJECT_PUT TO ELENA;

GRANT EXECUTE ON PROCEDURE OBJECT_PUT TO NASTYA;

GRANT EXECUTE ON PROCEDURE OBJECT_PUT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE OBJECT_PUT TO NATVL;

GRANT EXECUTE ON PROCEDURE OBJECT_PUT TO ND;

GRANT EXECUTE ON PROCEDURE OBJECT_PUT TO YULYA;

GRANT EXECUTE ON PROCEDURE OBJECT_READ TO ELENA;

GRANT EXECUTE ON PROCEDURE OBJECT_READ TO NASTYA;

GRANT EXECUTE ON PROCEDURE OBJECT_READ TO NASTYA17;

GRANT EXECUTE ON PROCEDURE OBJECT_READ TO NATVL;

GRANT EXECUTE ON PROCEDURE OBJECT_READ TO ND;

GRANT EXECUTE ON PROCEDURE OBJECT_READ TO YULYA;

GRANT EXECUTE ON PROCEDURE OBJECT_UPDATEABLE TO ELENA;

GRANT EXECUTE ON PROCEDURE OBJECT_UPDATEABLE TO NASTYA;

GRANT EXECUTE ON PROCEDURE OBJECT_UPDATEABLE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE OBJECT_UPDATEABLE TO NATVL;

GRANT EXECUTE ON PROCEDURE OBJECT_UPDATEABLE TO ND;

GRANT EXECUTE ON PROCEDURE OBJECT_UPDATEABLE TO YULYA;

GRANT EXECUTE ON PROCEDURE ORDER_READ TO ELENA;

GRANT EXECUTE ON PROCEDURE ORDER_READ TO NASTYA;

GRANT EXECUTE ON PROCEDURE ORDER_READ TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ORDER_READ TO NATVL;

GRANT EXECUTE ON PROCEDURE ORDER_READ TO ND;

GRANT EXECUTE ON PROCEDURE ORDER_READ TO YULYA;

GRANT EXECUTE ON PROCEDURE ORDER_X_ACTIVEITEMSCOUNT TO ELENA;

GRANT EXECUTE ON PROCEDURE ORDER_X_ACTIVEITEMSCOUNT TO NASTYA;

GRANT EXECUTE ON PROCEDURE ORDER_X_ACTIVEITEMSCOUNT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ORDER_X_ACTIVEITEMSCOUNT TO NATVL;

GRANT EXECUTE ON PROCEDURE ORDER_X_ACTIVEITEMSCOUNT TO ND;

GRANT EXECUTE ON PROCEDURE ORDER_X_ACTIVEITEMSCOUNT TO YULYA;

GRANT EXECUTE ON PROCEDURE ORDER_X_UNINVOICED TO ELENA;

GRANT EXECUTE ON PROCEDURE ORDER_X_UNINVOICED TO NASTYA;

GRANT EXECUTE ON PROCEDURE ORDER_X_UNINVOICED TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ORDER_X_UNINVOICED TO NATVL;

GRANT EXECUTE ON PROCEDURE ORDER_X_UNINVOICED TO ND;

GRANT EXECUTE ON PROCEDURE ORDER_X_UNINVOICED TO YULYA;

GRANT EXECUTE ON PROCEDURE ORDERHISTORY_UPDATE TO ELENA;

GRANT EXECUTE ON PROCEDURE ORDERHISTORY_UPDATE TO NASTYA;

GRANT EXECUTE ON PROCEDURE ORDERHISTORY_UPDATE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ORDERHISTORY_UPDATE TO NATVL;

GRANT EXECUTE ON PROCEDURE ORDERHISTORY_UPDATE TO ND;

GRANT EXECUTE ON PROCEDURE ORDERHISTORY_UPDATE TO YULYA;

GRANT EXECUTE ON PROCEDURE ORDERITEM_READ TO ELENA;

GRANT EXECUTE ON PROCEDURE ORDERITEM_READ TO NASTYA;

GRANT EXECUTE ON PROCEDURE ORDERITEM_READ TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ORDERITEM_READ TO NATVL;

GRANT EXECUTE ON PROCEDURE ORDERITEM_READ TO ND;

GRANT EXECUTE ON PROCEDURE ORDERITEM_READ TO YULYA;

GRANT EXECUTE ON PROCEDURE ORDERITEM_X_GETSTATEID TO ELENA;

GRANT EXECUTE ON PROCEDURE ORDERITEM_X_GETSTATEID TO NASTYA;

GRANT EXECUTE ON PROCEDURE ORDERITEM_X_GETSTATEID TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ORDERITEM_X_GETSTATEID TO NATVL;

GRANT EXECUTE ON PROCEDURE ORDERITEM_X_GETSTATEID TO ND;

GRANT EXECUTE ON PROCEDURE ORDERITEM_X_GETSTATEID TO YULYA;

GRANT EXECUTE ON PROCEDURE ORDERTAX_READ TO ELENA;

GRANT EXECUTE ON PROCEDURE ORDERTAX_READ TO NASTYA;

GRANT EXECUTE ON PROCEDURE ORDERTAX_READ TO NASTYA17;

GRANT EXECUTE ON PROCEDURE ORDERTAX_READ TO NATVL;

GRANT EXECUTE ON PROCEDURE ORDERTAX_READ TO ND;

GRANT EXECUTE ON PROCEDURE ORDERTAX_READ TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_IN TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_IN TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_IN TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_IN TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_IN TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_IN TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_OUT TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_OUT TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_OUT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_OUT TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_OUT TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_CALC_OUT TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_CLONE TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_CLONE TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_CLONE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_CLONE TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_CLONE TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_CLONE TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_CREATE TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_CREATE TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_CREATE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_CREATE TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_CREATE TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_CREATE TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_CRITERIA TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_CRITERIA TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_CRITERIA TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_CRITERIA TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_CRITERIA TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_CRITERIA TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_DEL TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_DEL TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_DEL TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_DEL TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_DEL TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_DEL TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_FILLPATTERN TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_FILLPATTERN TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_FILLPATTERN TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_FILLPATTERN TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_FILLPATTERN TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_FILLPATTERN TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_GET TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_GET TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_GET TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_GET TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_GET TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_GET TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE_4ACTION TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE_4ACTION TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE_4ACTION TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE_4ACTION TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE_4ACTION TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_PARSE_4ACTION TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_SET TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_SET TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_SET TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_SET TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_SET TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_SET TO YULYA;

GRANT EXECUTE ON PROCEDURE PARAM_UNPARSE TO ELENA;

GRANT EXECUTE ON PROCEDURE PARAM_UNPARSE TO NASTYA;

GRANT EXECUTE ON PROCEDURE PARAM_UNPARSE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PARAM_UNPARSE TO NATVL;

GRANT EXECUTE ON PROCEDURE PARAM_UNPARSE TO ND;

GRANT EXECUTE ON PROCEDURE PARAM_UNPARSE TO YULYA;

GRANT EXECUTE ON PROCEDURE PIVOT_RECORD TO ELENA;

GRANT EXECUTE ON PROCEDURE PIVOT_RECORD TO NASTYA;

GRANT EXECUTE ON PROCEDURE PIVOT_RECORD TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PIVOT_RECORD TO NATVL;

GRANT EXECUTE ON PROCEDURE PIVOT_RECORD TO ND;

GRANT EXECUTE ON PROCEDURE PIVOT_RECORD TO YULYA;

GRANT EXECUTE ON PROCEDURE PLACE_DETECT TO ELENA;

GRANT EXECUTE ON PROCEDURE PLACE_DETECT TO NASTYA;

GRANT EXECUTE ON PROCEDURE PLACE_DETECT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PLACE_DETECT TO NATVL;

GRANT EXECUTE ON PROCEDURE PLACE_DETECT TO ND;

GRANT EXECUTE ON PROCEDURE PLACE_DETECT TO YULYA;

GRANT EXECUTE ON PROCEDURE PLACE_READ TO ELENA;

GRANT EXECUTE ON PROCEDURE PLACE_READ TO NASTYA;

GRANT EXECUTE ON PROCEDURE PLACE_READ TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PLACE_READ TO NATVL;

GRANT EXECUTE ON PROCEDURE PLACE_READ TO ND;

GRANT EXECUTE ON PROCEDURE PLACE_READ TO YULYA;

GRANT EXECUTE ON PROCEDURE PLUGIN_VALUE TO ELENA;

GRANT EXECUTE ON PROCEDURE PLUGIN_VALUE TO NASTYA;

GRANT EXECUTE ON PROCEDURE PLUGIN_VALUE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE PLUGIN_VALUE TO NATVL;

GRANT EXECUTE ON PROCEDURE PLUGIN_VALUE TO ND;

GRANT EXECUTE ON PROCEDURE PLUGIN_VALUE TO YULYA;

GRANT EXECUTE ON PROCEDURE SEARCH TO ELENA;

GRANT EXECUTE ON PROCEDURE SEARCH TO NASTYA;

GRANT EXECUTE ON PROCEDURE SEARCH TO NASTYA17;

GRANT EXECUTE ON PROCEDURE SEARCH TO NATVL;

GRANT EXECUTE ON PROCEDURE SEARCH TO ND;

GRANT EXECUTE ON PROCEDURE SEARCH TO YULYA;

GRANT EXECUTE ON PROCEDURE SEARCH_GET_NGRAMM TO ELENA;

GRANT EXECUTE ON PROCEDURE SEARCH_GET_NGRAMM TO NASTYA;

GRANT EXECUTE ON PROCEDURE SEARCH_GET_NGRAMM TO NASTYA17;

GRANT EXECUTE ON PROCEDURE SEARCH_GET_NGRAMM TO NATVL;

GRANT EXECUTE ON PROCEDURE SEARCH_GET_NGRAMM TO ND;

GRANT EXECUTE ON PROCEDURE SEARCH_GET_NGRAMM TO YULYA;

GRANT EXECUTE ON PROCEDURE SETTING_GET TO ELENA;

GRANT EXECUTE ON PROCEDURE SETTING_GET TO NASTYA;

GRANT EXECUTE ON PROCEDURE SETTING_GET TO NASTYA17;

GRANT EXECUTE ON PROCEDURE SETTING_GET TO NATVL;

GRANT EXECUTE ON PROCEDURE SETTING_GET TO ND;

GRANT EXECUTE ON PROCEDURE SETTING_GET TO YULYA;

GRANT EXECUTE ON PROCEDURE SETTING_SET TO ELENA;

GRANT EXECUTE ON PROCEDURE SETTING_SET TO NASTYA;

GRANT EXECUTE ON PROCEDURE SETTING_SET TO NASTYA17;

GRANT EXECUTE ON PROCEDURE SETTING_SET TO NATVL;

GRANT EXECUTE ON PROCEDURE SETTING_SET TO ND;

GRANT EXECUTE ON PROCEDURE SETTING_SET TO YULYA;

GRANT EXECUTE ON PROCEDURE SPLITBLOB TO ELENA;

GRANT EXECUTE ON PROCEDURE SPLITBLOB TO NASTYA;

GRANT EXECUTE ON PROCEDURE SPLITBLOB TO NASTYA17;

GRANT EXECUTE ON PROCEDURE SPLITBLOB TO NATVL;

GRANT EXECUTE ON PROCEDURE SPLITBLOB TO ND;

GRANT EXECUTE ON PROCEDURE SPLITBLOB TO YULYA;

GRANT EXECUTE ON PROCEDURE SPLITSTRING TO ELENA;

GRANT EXECUTE ON PROCEDURE SPLITSTRING TO NASTYA;

GRANT EXECUTE ON PROCEDURE SPLITSTRING TO NASTYA17;

GRANT EXECUTE ON PROCEDURE SPLITSTRING TO NATVL;

GRANT EXECUTE ON PROCEDURE SPLITSTRING TO ND;

GRANT EXECUTE ON PROCEDURE SPLITSTRING TO YULYA;

GRANT EXECUTE ON PROCEDURE STATUS_CHECK_CONVERSION TO ELENA;

GRANT EXECUTE ON PROCEDURE STATUS_CHECK_CONVERSION TO NASTYA;

GRANT EXECUTE ON PROCEDURE STATUS_CHECK_CONVERSION TO NASTYA17;

GRANT EXECUTE ON PROCEDURE STATUS_CHECK_CONVERSION TO NATVL;

GRANT EXECUTE ON PROCEDURE STATUS_CHECK_CONVERSION TO ND;

GRANT EXECUTE ON PROCEDURE STATUS_CHECK_CONVERSION TO YULYA;

GRANT EXECUTE ON PROCEDURE STATUS_CONVERSION_BY_FLAG TO ELENA;

GRANT EXECUTE ON PROCEDURE STATUS_CONVERSION_BY_FLAG TO NASTYA;

GRANT EXECUTE ON PROCEDURE STATUS_CONVERSION_BY_FLAG TO NASTYA17;

GRANT EXECUTE ON PROCEDURE STATUS_CONVERSION_BY_FLAG TO NATVL;

GRANT EXECUTE ON PROCEDURE STATUS_CONVERSION_BY_FLAG TO ND;

GRANT EXECUTE ON PROCEDURE STATUS_CONVERSION_BY_FLAG TO YULYA;

GRANT EXECUTE ON PROCEDURE STATUS_GET_CONVERSION TO ELENA;

GRANT EXECUTE ON PROCEDURE STATUS_GET_CONVERSION TO NASTYA;

GRANT EXECUTE ON PROCEDURE STATUS_GET_CONVERSION TO NASTYA17;

GRANT EXECUTE ON PROCEDURE STATUS_GET_CONVERSION TO NATVL;

GRANT EXECUTE ON PROCEDURE STATUS_GET_CONVERSION TO ND;

GRANT EXECUTE ON PROCEDURE STATUS_GET_CONVERSION TO YULYA;

GRANT EXECUTE ON PROCEDURE STATUS_GET_DEFAULT TO ELENA;

GRANT EXECUTE ON PROCEDURE STATUS_GET_DEFAULT TO NASTYA;

GRANT EXECUTE ON PROCEDURE STATUS_GET_DEFAULT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE STATUS_GET_DEFAULT TO NATVL;

GRANT EXECUTE ON PROCEDURE STATUS_GET_DEFAULT TO ND;

GRANT EXECUTE ON PROCEDURE STATUS_GET_DEFAULT TO YULYA;

GRANT EXECUTE ON PROCEDURE STATUS_STORE_DATE TO ELENA;

GRANT EXECUTE ON PROCEDURE STATUS_STORE_DATE TO NASTYA;

GRANT EXECUTE ON PROCEDURE STATUS_STORE_DATE TO NASTYA17;

GRANT EXECUTE ON PROCEDURE STATUS_STORE_DATE TO NATVL;

GRANT EXECUTE ON PROCEDURE STATUS_STORE_DATE TO ND;

GRANT EXECUTE ON PROCEDURE STATUS_STORE_DATE TO YULYA;

GRANT EXECUTE ON PROCEDURE TAX_FIXED_SUM TO ELENA;

GRANT EXECUTE ON PROCEDURE TAX_FIXED_SUM TO NASTYA;

GRANT EXECUTE ON PROCEDURE TAX_FIXED_SUM TO NASTYA17;

GRANT EXECUTE ON PROCEDURE TAX_FIXED_SUM TO NATVL;

GRANT EXECUTE ON PROCEDURE TAX_FIXED_SUM TO ND;

GRANT EXECUTE ON PROCEDURE TAX_FIXED_SUM TO YULYA;

GRANT EXECUTE ON PROCEDURE TAX_USE_REST TO ELENA;

GRANT EXECUTE ON PROCEDURE TAX_USE_REST TO NASTYA;

GRANT EXECUTE ON PROCEDURE TAX_USE_REST TO NASTYA17;

GRANT EXECUTE ON PROCEDURE TAX_USE_REST TO NATVL;

GRANT EXECUTE ON PROCEDURE TAX_USE_REST TO ND;

GRANT EXECUTE ON PROCEDURE TAX_USE_REST TO YULYA;

GRANT EXECUTE ON PROCEDURE TAX_WEIGHT TO ELENA;

GRANT EXECUTE ON PROCEDURE TAX_WEIGHT TO NASTYA;

GRANT EXECUTE ON PROCEDURE TAX_WEIGHT TO NASTYA17;

GRANT EXECUTE ON PROCEDURE TAX_WEIGHT TO NATVL;

GRANT EXECUTE ON PROCEDURE TAX_WEIGHT TO ND;

GRANT EXECUTE ON PROCEDURE TAX_WEIGHT TO YULYA;

GRANT EXECUTE ON PROCEDURE TAXRATE_CALC TO ELENA;

GRANT EXECUTE ON PROCEDURE TAXRATE_CALC TO NASTYA;

GRANT EXECUTE ON PROCEDURE TAXRATE_CALC TO NASTYA17;

GRANT EXECUTE ON PROCEDURE TAXRATE_CALC TO NATVL;

GRANT EXECUTE ON PROCEDURE TAXRATE_CALC TO ND;

GRANT EXECUTE ON PROCEDURE TAXRATE_CALC TO YULYA;

GRANT RDB$ADMIN TO SYSDBA;

GRANT USERS TO ELENA;

GRANT USERS TO NASTYA;

GRANT USERS TO NASTYA17;

GRANT USERS TO NATVL;

GRANT USERS TO ND;

GRANT USERS TO YULYA;


