/* Server version: WI-V6.3.1.26351 Firebird 2.5 
   SQLDialect: 3. ODS: 11.2. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 2048 (8192 Kb). Read-only: False. */
SET CLIENTLIB 'fbclient.dll';
SET NAMES CYRL;

SET SQL DIALECT 3;

SET AUTODDL ON;

/* Create Domains... */
CREATE DOMAIN ID_AUFTRAG AS INTEGER;

ALTER TABLE ORDERITEMS ADD AUFTRAG_ID ID_AUFTRAG;

/* Create Procedure... */
SET TERM ^ ;

CREATE PROCEDURE MESSAGE_READ(I_OBJECT_ID TYPE OF ID_MESSAGE)
 RETURNS(O_PARAM_NAME TYPE OF SIGN_OBJECT,
O_PARAM_VALUE TYPE OF VALUE_ATTR)
 AS
 BEGIN SUSPEND; END
^


/* Alter Procedure... */
/* Alter (MESSAGE_RELEASE) */
ALTER PROCEDURE MESSAGE_RELEASE(I_TEMPLATE_ID TYPE OF ID_MESSAGE NOT NULL)
 AS
begin
  update messages m
    set m.busy_id = null
    where m.busy_id = current_connection
      and m.template_id = :i_template_id;
end
^

/* Restore proc. body: MESSAGE_READ */
ALTER PROCEDURE MESSAGE_READ(I_OBJECT_ID TYPE OF ID_MESSAGE)
 RETURNS(O_PARAM_NAME TYPE OF SIGN_OBJECT,
O_PARAM_VALUE TYPE OF VALUE_ATTR)
 AS
begin
  /* Procedure Text */
  for select d.param_sign, recode(m.file_name, d.value_mask)
        from messages m
          inner join detector d on (d.object_sign = 'MESSAGE' and d.object_id = m.template_id)
        where m.message_id = :i_object_id
        into :o_param_name, :o_param_value do
  begin
    suspend;
  end
end
^

/* Alter Procedure... */
SET TERM ; ^

ALTER TABLE ORDERITEMS ALTER COLUMN ORDERITEM_ID POSITION 1;

ALTER TABLE ORDERITEMS ALTER COLUMN ORDER_ID POSITION 2;

ALTER TABLE ORDERITEMS ALTER COLUMN ARTICLE_ID POSITION 3;

ALTER TABLE ORDERITEMS ALTER COLUMN MAGAZINE_ID POSITION 4;

ALTER TABLE ORDERITEMS ALTER COLUMN ARTICLE_CODE POSITION 5;

ALTER TABLE ORDERITEMS ALTER COLUMN DIMENSION POSITION 6;

ALTER TABLE ORDERITEMS ALTER COLUMN PRICE_EUR POSITION 7;

ALTER TABLE ORDERITEMS ALTER COLUMN AMOUNT POSITION 8;

ALTER TABLE ORDERITEMS ALTER COLUMN COST_EUR POSITION 9;

ALTER TABLE ORDERITEMS ALTER COLUMN STATUS_ID POSITION 10;

ALTER TABLE ORDERITEMS ALTER COLUMN STATUS_DTM POSITION 11;

ALTER TABLE ORDERITEMS ALTER COLUMN STATE_ID POSITION 12;

ALTER TABLE ORDERITEMS ALTER COLUMN ORDERITEM_INDEX POSITION 13;

ALTER TABLE ORDERITEMS ALTER COLUMN RETURN_REESTR_ID POSITION 14;

ALTER TABLE ORDERITEMS ALTER COLUMN AUFTRAG_ID POSITION 15;

