/* Server version: WI-V6.3.1.26351 Firebird 2.5
   SQLDialect: 3. ODS: 11.2. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 2048 (8192 Kb). Read-only: False. */
SET CLIENTLIB 'fbclient.dll';
SET NAMES CYRL;

SET SQL DIALECT 3;

SET AUTODDL ON;

/* Alter View (Drop, Create)... */
/* Drop altered view: V_ADRESS_TEXT */
SET TERM ^ ;

ALTER PROCEDURE ORDER_READ(I_OBJECT_ID /* TYPE OF ID_OBJECT */ INTEGER)
 RETURNS(O_PARAM_NAME /* TYPE OF SIGN_OBJECT */ VARCHAR(30),
O_PARAM_VALUE /* TYPE OF VALUE_ATTR */ VARCHAR(4000))
 AS
 BEGIN SUSPEND; END
^

SET TERM ; ^

DROP VIEW V_MONEYBACK_BELPOST;

DROP VIEW V_ORDERITEMS_RETURNING;

DROP VIEW V_CLIENTADRESS;

DROP VIEW V_ORDERS;

DROP VIEW V_ADRESS_TEXT;

/* Create altered view: V_ADRESS_TEXT */
/* Create view: V_ADRESS_TEXT */
CREATE VIEW V_ADRESS_TEXT(
ADRESS_ID,
PLACE_ID,
CLIENT_ID,
ADRESS_TEXT,
STATUS_ID,
STATUS_SIGN,
POSTINDEX)
 AS 
select
  a.adress_id,
  a.place_id,
  a.client_id,
  iif(a.street_name is null, '', st.streettype_sign||'. '||a.street_name||' ')||
    iif(a.house is null,  '', a.house)||
    iif(a.building is null, '',', корп. '||a.building)||
    iif(a.flat is null, '', ', кв. '||a.flat),
  a.status_id,
  s.status_sign,
  a.postindex
from adresses a
 inner join streettypes  st on (st.streettype_code = coalesce(a.streettype_code, 1))
 inner join statuses s on (s.status_id = a.status_id)
;

/* Alter Procedure... */
/* Create view: V_CLIENTADRESS */
CREATE VIEW V_CLIENTADRESS(
CLIENT_ID,
FIO_TEXT,
LAST_NAME,
FIRST_NAME,
MID_NAME,
STATUS_ID,
MOBILE_PHONE,
EMAIL,
PHONE_NUMBER,
PLACE_ID,
PLACE_TEXT,
ADRESS_ID,
ADRESS_TEXT,
POSTINDEX)
 AS 
select c.client_id, cast(c.last_name||' '||c.first_name||iif(c.mid_name is null, '', ' '||c.mid_name) as varchar(100)),
  c.last_name, c.first_name, c.mid_name, c.status_id,
  c.mobile_phone, ca_mail.attr_value, ca_phone.attr_value,
  p.place_id, p.place_text, a.adress_id, a.adress_text, a.postindex
  from clients c
    inner join v_adress_text a on (a.client_id = c.client_id and a.status_sign<>'ARCHIVE')
    inner join v_place_text p on (p.place_id = a.place_id)
    left join v_client_attrs ca_phone on (ca_phone.object_id = c.client_id and ca_phone.attr_sign = 'PHONE_NUMBER')
    left join v_client_attrs ca_mail on (ca_mail.object_id = c.client_id and ca_mail.attr_sign = 'EMAIL')
;

/* Alter (ORDER_READ) */
SET TERM ^ ;

ALTER PROCEDURE ORDER_READ(I_OBJECT_ID TYPE OF ID_OBJECT)
 RETURNS(O_PARAM_NAME TYPE OF SIGN_OBJECT,
O_PARAM_VALUE TYPE OF VALUE_ATTR)
 AS
declare variable V_PRODUCT_NAME type of VALUE_ATTR;
declare variable V_CLIENT_FIO type of VALUE_ATTR;
declare variable V_ADRESS_TEXT type of VALUE_ATTR;
declare variable V_STATUS_SIGN type of SIGN_ATTR;
declare variable V_ACCOUNT_ID type of ID_ACCOUNT;
declare variable V_STATUS_FLAG_LIST type of LIST_SIGNS;
declare variable V_STATUS_NAME type of NAME_OBJECT;
begin
  select p.product_name, vc.client_fio,
         ca.postindex||'. '||ca.place_text||', '||ca.adress_text adress_text,
         s.status_sign, s.flag_sign_list, s.status_name
    from orders o
      left join products p on (p.product_id = o.product_id)
      left join v_clients_fio vc on (vc.client_id = o.client_id)
      left join v_clientadress ca on (ca.adress_id = o.adress_id)
      left join statuses s on (s.status_id = o.status_id)
    where o.order_id = :i_object_id
    into :v_product_name, :v_client_fio, :v_adress_text,
         :v_status_sign, :v_status_flag_list, :v_status_name;

  o_param_name = 'STATUS_SIGN';
  o_param_value = v_status_sign;
  suspend;
  o_param_name = 'STATUS_FLAG_LIST';
  o_param_value = v_status_flag_list;
  suspend;
  o_param_name = 'STATUS_NAME';
  o_param_value = v_status_name;
  suspend;


  if (:v_product_name is not null) then
  begin
    o_param_name = 'PRODUCT_NAME';
    o_param_value = :v_product_name;
    suspend;
  end

  if (v_client_fio is not null) then
  begin
    o_param_name = 'CLIENT_FIO';
    o_param_value = :v_client_fio;
    suspend;
  end

  if (:v_adress_text is not null) then
  begin
    o_param_name = 'ADRESS_TEXT';
    o_param_value = :v_adress_text;
    suspend;
  end

  select a.account_id
    from orders o
      inner join clients cl on (cl.client_id = o.client_id)
      inner join accounts a on (a.account_id = cl.account_id)
    where o.order_id = :i_object_id
    into :v_account_id;
  if (:v_account_id is not null) then
  begin
    o_param_name = 'ACCOUNT_ID';
    o_param_value = :v_account_id;
    suspend;
  end

end
^

/* Alter (ORDERTAX_READ) */
ALTER PROCEDURE ORDERTAX_READ(I_OBJECT_ID TYPE OF ID_OBJECT)
 RETURNS(O_PARAM_NAME TYPE OF SIGN_OBJECT,
O_PARAM_VALUE TYPE OF VALUE_ATTR)
 AS
declare variable V_TAXSERV_ID type of ID_TAX;
declare variable V_TAXSERV_NAME type of NAME_REF;
declare variable V_STATUS_SIGN type of SIGN_OBJECT;
declare variable V_STATUS_NAME type of NAME_OBJECT;
declare variable V_COST_EUR type of MONEY_EUR;
declare variable V_BYR2EUR type of MONEY_BYR;
begin
  select ts.taxserv_id, ts.taxserv_name, s.status_sign, s.status_name,
         ot.cost_eur, o.byr2eur
    from ordertaxs ot
      inner join taxrates tr on (tr.taxrate_id = ot.taxrate_id)
      inner join taxservs ts on (ts.taxserv_id = tr.taxserv_id)
      inner join statuses s on (s.status_id = ot.status_id)
      inner join orders o on (o.order_id = ot.order_id)
    where ot.ordertax_id = :i_object_id
    into :v_taxserv_id, :v_taxserv_name, :v_status_sign, :v_status_name,
         :v_cost_eur, :v_byr2eur;

  o_param_name = 'TAXSERV_ID';
  o_param_value = :v_taxserv_id;
  suspend;
  o_param_name = 'TAXSERV_NAME';
  o_param_value = :v_taxserv_name;
  suspend;
  o_param_name = 'STATUS_SIGN';
  o_param_value = v_status_sign;
  suspend;
  o_param_name = 'STATUS_NAME';
  o_param_value = v_status_name;
  suspend;
  o_param_name = 'COST_BYR';
  select o_money_byr from money_eur2byr(:v_cost_eur, :v_byr2eur) into o_param_value;
  suspend;
end
^

/* Create Views... */
/* Create view: V_MONEYBACK_BELPOST */
SET TERM ; ^

CREATE VIEW V_MONEYBACK_BELPOST(
FIO_TEXT,
PLACE_TEXT,
ADRESS_TEXT,
POSTINDEX,
PAYED_BYR,
POST_FEE_BYR,
NDS_BYR,
AMOUNT_BYR,
NDS_FEE,
BELPOST_FEE,
PURPOSE)
 AS 
select ca.FIO_Text, ca.Place_Text, ca.Adress_Text, a.PostIndex
  , round(mb.amount_byr/(1+belpost.fee),-1) payed_byr
  , round(mb.amount_byr*belpost.fee/(1+belpost.fee)) post_fee_byr
  , round(round(mb.amount_byr*belpost.fee/(1+belpost.fee))*nds.fee) nds_byr
  , mb.amount_byr
  , nds.fee
  , belpost.fee
  , mba.attr_value purpose
from moneybacks mb,
(select cast(o_value as numeric(10,4))/100 fee from setting_get('BELPOST_FEE')) belpost,
(select cast(o_value as numeric(10,2))/100 fee from setting_get('NDS_FEE')) nds
left join v_moneyback_attrs mba on (mba.object_id = mb.moneyback_id and mba.attr_sign = 'PURPOSE')
inner join clients c on (c.account_id = mb.account_id)
inner join v_clientadress ca on (ca.client_id = c.client_id)
inner join statuses s on (s.status_id = mb.status_id)
inner join adresses a on (a.adress_id = ca.adress_id)                                                                                                                              
where mb.kind = 'BELPOST'
  and s.status_sign = 'NEW'
;

/* Create view: V_ORDERITEMS_RETURNING */
CREATE VIEW V_ORDERITEMS_RETURNING(
PRODUCT_ID,
ORDERITEM_ID,
ORDER_ID,
ORDER_CODE,
PARTNER_NUMBER,
CLIENT_ID,
FIO_TEXT,
ADRESS_TEXT,
PLACE_TEXT,
AUFTRAG_ID,
ORDERITEM_INDEX,
ARTICLE_CODE,
DIMENSION,
AMOUNT,
NAME_RUS,
PRICE_EUR,
WEIGHT,
NRRETCODE,
NREGWG,
PACKLIST_NO,
BEPOST_BAR_CODE,
BAR_CODE)
 AS 
select o.product_id
  , oi.orderitem_id
  , o.order_id
  , o.order_code
  , cast(pa.attr_value as numeric(10)) partner_number
  , ca.client_id
  , ca.fio_text
  , ca.adress_text
  , ca.place_text
  , cast(oia1.attr_value as varchar(10)) auftrag_id
  , oi.orderitem_index
  , oi.article_code
  , oi.dimension
  , 1 amount
  , cast(trim(coalesce(oia2.attr_value,'')||' '||coalesce(oia3.attr_value, '')) as varchar(100)) name_rus
  , price_eur
  , cast(oia4.attr_value as numeric(10, 3))/1000 weight
  , cast(oia5.attr_value as varchar(50)) nrretcode
  , cast(oia6.attr_value as varchar(50)) nregwg
  , cast(oa1.attr_value as varchar(10)) packlist_no
  , cast(oa2.attr_value as varchar(20)) bepost_bar_code
  , o.bar_code
from OrderItems oi
inner join statuses sr on (sr.status_id = oi.status_id and sr.status_sign = 'RETURNING')
inner join orders o on (o.order_id = oi.order_id)
inner join v_product_attrs pa on (pa.object_id = o.product_id and pa.attr_sign = 'PARTNER_NUMBER')
inner join v_clientadress ca on (ca.client_id = o.client_id)
left join v_orderitem_attrs oia1 on (oia1.object_id = oi.orderitem_id and oia1.attr_sign = 'AUFTRAG_ID')
left join v_orderitem_attrs oia2 on (oia2.object_id = oi.orderitem_id and oia2.attr_sign = 'NAME_RUS')
left join v_orderitem_attrs oia3 on (oia3.object_id = oi.orderitem_id and oia3.attr_sign = 'KIND_RUS')
left join v_orderitem_attrs oia4 on (oia4.object_id = oi.orderitem_id and oia4.attr_sign = 'WEIGHT')
left join v_orderitem_attrs oia5 on (oia5.object_id = oi.orderitem_id and oia5.attr_sign = 'NRRETCODE')
left join v_orderitem_attrs oia6 on (oia6.object_id = oi.orderitem_id and oia6.attr_sign = 'NREGWG')
left join v_order_attrs oa1 on (oa1.object_id = o.order_id and oa1.attr_sign = 'PACKLIST_NO')
left join v_order_attrs oa2 on (oa2.object_id = o.order_id and oa2.attr_sign = 'BELPOST_BAR_CODE')
where oi.return_reestr_id is null
;

/* Create view: V_ORDERS */
CREATE VIEW V_ORDERS(
ORDER_ID,
ORDER_CODE,
PRODUCT_ID,
PRODUCT_NAME,
VENDOR_ID,
VENDOR_NAME,
CLIENT_ID,
CLIENT_FIO,
ADRESS_ID,
ADRESS_TEXT,
CREATE_DTM,
STATUS_ID,
STATUS_NAME,
STATUS_SIGN,
STATUS_DTM)
 AS 
select 
    orders.order_id,
    orders.order_code,
    orders.product_id,
    products.product_name,
    products.vendor_id,
    vendors.vendor_name,
    orders.client_id,
    v_clients_fio.client_fio,
    orders.adress_id,
    v_adress_text.adress_text,
    orders.create_dtm,
    orders.status_id,
    statuses.status_name,
    statuses.status_sign,
    orders.status_dtm
from orders
   inner join products on (orders.product_id = products.product_id)
   inner join vendors on (products.vendor_id = vendors.vendor_id)
   inner join v_clients_fio on (orders.client_id = v_clients_fio.client_id)
   inner join v_adress_text on (orders.adress_id = v_adress_text.adress_id)
   inner join statuses on (orders.status_id = statuses.status_id)
;


/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO ANNA */
REVOKE ALL ON CLIENTNOTIFIES FROM ANNA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO CATRIN */
REVOKE ALL ON CLIENTNOTIFIES FROM CATRIN;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO ELENA */
REVOKE ALL ON CLIENTNOTIFIES FROM ELENA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO KATYA */
REVOKE ALL ON CLIENTNOTIFIES FROM KATYA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO LANA */
REVOKE ALL ON CLIENTNOTIFIES FROM LANA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO LENA */
REVOKE ALL ON CLIENTNOTIFIES FROM LENA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO NASTYA */
REVOKE ALL ON CLIENTNOTIFIES FROM NASTYA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO NASTYA17 */
REVOKE ALL ON CLIENTNOTIFIES FROM NASTYA17;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO NATA */
REVOKE ALL ON CLIENTNOTIFIES FROM NATA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO NATVL */
REVOKE ALL ON CLIENTNOTIFIES FROM NATVL;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO ND */
REVOKE ALL ON CLIENTNOTIFIES FROM ND;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO OKSANA */
REVOKE ALL ON CLIENTNOTIFIES FROM OKSANA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO PUBLIC */
REVOKE ALL ON CLIENTNOTIFIES FROM PUBLIC;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO SVETLANA */
REVOKE ALL ON CLIENTNOTIFIES FROM SVETLANA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO VALERY */
REVOKE ALL ON CLIENTNOTIFIES FROM VALERY;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO VIKA */
REVOKE ALL ON CLIENTNOTIFIES FROM VIKA;

/* DROP: -- GRANT ALL ON CLIENTNOTIFIES TO YULYA */
REVOKE ALL ON CLIENTNOTIFIES FROM YULYA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO ANNA */
REVOKE ALL ON DEALERNOTIFIES FROM ANNA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO CATRIN */
REVOKE ALL ON DEALERNOTIFIES FROM CATRIN;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO ELENA */
REVOKE ALL ON DEALERNOTIFIES FROM ELENA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO KATYA */
REVOKE ALL ON DEALERNOTIFIES FROM KATYA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO LANA */
REVOKE ALL ON DEALERNOTIFIES FROM LANA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO LENA */
REVOKE ALL ON DEALERNOTIFIES FROM LENA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO NASTYA */
REVOKE ALL ON DEALERNOTIFIES FROM NASTYA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO NASTYA17 */
REVOKE ALL ON DEALERNOTIFIES FROM NASTYA17;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO NATA */
REVOKE ALL ON DEALERNOTIFIES FROM NATA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO NATVL */
REVOKE ALL ON DEALERNOTIFIES FROM NATVL;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO ND */
REVOKE ALL ON DEALERNOTIFIES FROM ND;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO OKSANA */
REVOKE ALL ON DEALERNOTIFIES FROM OKSANA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO PUBLIC */
REVOKE ALL ON DEALERNOTIFIES FROM PUBLIC;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO SVETLANA */
REVOKE ALL ON DEALERNOTIFIES FROM SVETLANA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO VALERY */
REVOKE ALL ON DEALERNOTIFIES FROM VALERY;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO VIKA */
REVOKE ALL ON DEALERNOTIFIES FROM VIKA;

/* DROP: -- GRANT ALL ON DEALERNOTIFIES TO YULYA */
REVOKE ALL ON DEALERNOTIFIES FROM YULYA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO ANNA */
REVOKE ALL ON DEALERORDERS FROM ANNA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO CATRIN */
REVOKE ALL ON DEALERORDERS FROM CATRIN;

/* DROP: -- GRANT ALL ON DEALERORDERS TO ELENA */
REVOKE ALL ON DEALERORDERS FROM ELENA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO KATYA */
REVOKE ALL ON DEALERORDERS FROM KATYA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO LANA */
REVOKE ALL ON DEALERORDERS FROM LANA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO LENA */
REVOKE ALL ON DEALERORDERS FROM LENA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO NASTYA */
REVOKE ALL ON DEALERORDERS FROM NASTYA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO NASTYA17 */
REVOKE ALL ON DEALERORDERS FROM NASTYA17;

/* DROP: -- GRANT ALL ON DEALERORDERS TO NATA */
REVOKE ALL ON DEALERORDERS FROM NATA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO NATVL */
REVOKE ALL ON DEALERORDERS FROM NATVL;

/* DROP: -- GRANT ALL ON DEALERORDERS TO ND */
REVOKE ALL ON DEALERORDERS FROM ND;

/* DROP: -- GRANT ALL ON DEALERORDERS TO OKSANA */
REVOKE ALL ON DEALERORDERS FROM OKSANA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO PUBLIC */
REVOKE ALL ON DEALERORDERS FROM PUBLIC;

/* DROP: -- GRANT ALL ON DEALERORDERS TO SVETLANA */
REVOKE ALL ON DEALERORDERS FROM SVETLANA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO VALERY */
REVOKE ALL ON DEALERORDERS FROM VALERY;

/* DROP: -- GRANT ALL ON DEALERORDERS TO VIKA */
REVOKE ALL ON DEALERORDERS FROM VIKA;

/* DROP: -- GRANT ALL ON DEALERORDERS TO YULYA */
REVOKE ALL ON DEALERORDERS FROM YULYA;

/* DROP: -- GRANT ALL ON DEALERS TO ANNA */
REVOKE ALL ON DEALERS FROM ANNA;

/* DROP: -- GRANT ALL ON DEALERS TO CATRIN */
REVOKE ALL ON DEALERS FROM CATRIN;

/* DROP: -- GRANT ALL ON DEALERS TO ELENA */
REVOKE ALL ON DEALERS FROM ELENA;

/* DROP: -- GRANT ALL ON DEALERS TO KATYA */
REVOKE ALL ON DEALERS FROM KATYA;

/* DROP: -- GRANT ALL ON DEALERS TO LANA */
REVOKE ALL ON DEALERS FROM LANA;

/* DROP: -- GRANT ALL ON DEALERS TO LENA */
REVOKE ALL ON DEALERS FROM LENA;

/* DROP: -- GRANT ALL ON DEALERS TO NASTYA */
REVOKE ALL ON DEALERS FROM NASTYA;

/* DROP: -- GRANT ALL ON DEALERS TO NASTYA17 */
REVOKE ALL ON DEALERS FROM NASTYA17;

/* DROP: -- GRANT ALL ON DEALERS TO NATA */
REVOKE ALL ON DEALERS FROM NATA;

/* DROP: -- GRANT ALL ON DEALERS TO NATVL */
REVOKE ALL ON DEALERS FROM NATVL;

/* DROP: -- GRANT ALL ON DEALERS TO ND */
REVOKE ALL ON DEALERS FROM ND;

/* DROP: -- GRANT ALL ON DEALERS TO OKSANA */
REVOKE ALL ON DEALERS FROM OKSANA;

/* DROP: -- GRANT ALL ON DEALERS TO PUBLIC */
REVOKE ALL ON DEALERS FROM PUBLIC;

/* DROP: -- GRANT ALL ON DEALERS TO SVETLANA */
REVOKE ALL ON DEALERS FROM SVETLANA;

/* DROP: -- GRANT ALL ON DEALERS TO VALERY */
REVOKE ALL ON DEALERS FROM VALERY;

/* DROP: -- GRANT ALL ON DEALERS TO VIKA */
REVOKE ALL ON DEALERS FROM VIKA;

/* DROP: -- GRANT ALL ON DEALERS TO YULYA */
REVOKE ALL ON DEALERS FROM YULYA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO ANNA */
REVOKE ALL ON RECODE_MASKS FROM ANNA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO CATRIN */
REVOKE ALL ON RECODE_MASKS FROM CATRIN;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO ELENA */
REVOKE ALL ON RECODE_MASKS FROM ELENA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO KATYA */
REVOKE ALL ON RECODE_MASKS FROM KATYA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO LANA */
REVOKE ALL ON RECODE_MASKS FROM LANA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO LENA */
REVOKE ALL ON RECODE_MASKS FROM LENA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO NASTYA */
REVOKE ALL ON RECODE_MASKS FROM NASTYA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO NASTYA17 */
REVOKE ALL ON RECODE_MASKS FROM NASTYA17;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO NATA */
REVOKE ALL ON RECODE_MASKS FROM NATA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO NATVL */
REVOKE ALL ON RECODE_MASKS FROM NATVL;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO ND */
REVOKE ALL ON RECODE_MASKS FROM ND;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO OKSANA */
REVOKE ALL ON RECODE_MASKS FROM OKSANA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO PUBLIC */
REVOKE ALL ON RECODE_MASKS FROM PUBLIC;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO SVETLANA */
REVOKE ALL ON RECODE_MASKS FROM SVETLANA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO VALERY */
REVOKE ALL ON RECODE_MASKS FROM VALERY;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO VIKA */
REVOKE ALL ON RECODE_MASKS FROM VIKA;

/* DROP: -- GRANT ALL ON RECODE_MASKS TO YULYA */
REVOKE ALL ON RECODE_MASKS FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO ANNA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO ELENA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO KATYA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO LANA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO LENA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO NATA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO NATVL */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO ND */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO VALERY */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO VIKA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE TO YULYA */
REVOKE EXECUTE ON PROCEDURE ACT_CLIENTNOTIFY_STORE FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO ANNA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO ELENA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO KATYA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO LANA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO LENA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO NATA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO NATVL */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO ND */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO VALERY */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO VIKA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE TO YULYA */
REVOKE EXECUTE ON PROCEDURE ACT_DEALERNOTIFY_STORE FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO ANNA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO ELENA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO KATYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO LANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO LENA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO NATA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO NATVL */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO ND */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO VALERY */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO VIKA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS TO YULYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_INSTATUS FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO ANNA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO ELENA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO KATYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO LANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO LENA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO NATA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO NATVL */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO ND */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO VALERY */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO VIKA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS TO YULYA */
REVOKE EXECUTE ON PROCEDURE ACT_ORDER_4_ORDERITEM_NINSTATUS FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO ANNA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO CATRIN */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO ELENA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO KATYA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO LANA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO LENA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO NASTYA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO NATA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO NATVL */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO ND */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO OKSANA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO VALERY */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO VIKA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL TO YULYA */
REVOKE EXECUTE ON PROCEDURE CLIENT_NORMALIZE_MOBIL FROM YULYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO ANNA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM ANNA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO CATRIN */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM CATRIN;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO ELENA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM ELENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO KATYA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM KATYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO LANA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM LANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO LENA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM LENA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO NASTYA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM NASTYA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO NASTYA17 */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM NASTYA17;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO NATA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM NATA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO NATVL */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM NATVL;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO ND */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM ND;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO OKSANA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM OKSANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO PUBLIC */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM PUBLIC;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO SVETLANA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM SVETLANA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO VALERY */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM VALERY;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO VIKA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM VIKA;

/* DROP: -- GRANT EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING TO YULYA */
REVOKE EXECUTE ON PROCEDURE ORDER_UNDO_DELIVERING FROM YULYA;

/* Create(Add) privilege */
GRANT ALL ON V_ADRESS_TEXT TO ANNA;

GRANT ALL ON V_ADRESS_TEXT TO CATRIN;

GRANT ALL ON V_ADRESS_TEXT TO ELENA;

GRANT ALL ON V_ADRESS_TEXT TO KATYA;

GRANT ALL ON V_ADRESS_TEXT TO LANA;

GRANT ALL ON V_ADRESS_TEXT TO LENA;

GRANT ALL ON V_ADRESS_TEXT TO NASTYA;

GRANT ALL ON V_ADRESS_TEXT TO NASTYA17;

GRANT ALL ON V_ADRESS_TEXT TO NATA;

GRANT ALL ON V_ADRESS_TEXT TO NATVL;

GRANT ALL ON V_ADRESS_TEXT TO ND;

GRANT ALL ON V_ADRESS_TEXT TO OKSANA;

GRANT ALL ON V_ADRESS_TEXT TO PUBLIC;

GRANT ALL ON V_ADRESS_TEXT TO SVETLANA;

GRANT ALL ON V_ADRESS_TEXT TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON V_ADRESS_TEXT TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ADRESS_TEXT TO VALERY;

GRANT ALL ON V_ADRESS_TEXT TO VIKA;

GRANT ALL ON V_ADRESS_TEXT TO YULYA;

GRANT ALL ON V_CLIENTADRESS TO ANNA;

GRANT ALL ON V_CLIENTADRESS TO CATRIN;

GRANT ALL ON V_CLIENTADRESS TO ELENA;

GRANT ALL ON V_CLIENTADRESS TO KATYA;

GRANT ALL ON V_CLIENTADRESS TO LANA;

GRANT ALL ON V_CLIENTADRESS TO LENA;

GRANT ALL ON V_CLIENTADRESS TO NASTYA;

GRANT ALL ON V_CLIENTADRESS TO NASTYA17;

GRANT ALL ON V_CLIENTADRESS TO NATA;

GRANT ALL ON V_CLIENTADRESS TO NATVL;

GRANT ALL ON V_CLIENTADRESS TO ND;

GRANT ALL ON V_CLIENTADRESS TO OKSANA;

GRANT ALL ON V_CLIENTADRESS TO PUBLIC;

GRANT ALL ON V_CLIENTADRESS TO SVETLANA;

GRANT ALL ON V_CLIENTADRESS TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON V_CLIENTADRESS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_CLIENTADRESS TO VALERY;

GRANT ALL ON V_CLIENTADRESS TO VIKA;

GRANT ALL ON V_CLIENTADRESS TO YULYA;

GRANT ALL ON V_MONEYBACK_BELPOST TO ANNA;

GRANT ALL ON V_MONEYBACK_BELPOST TO CATRIN;

GRANT ALL ON V_MONEYBACK_BELPOST TO ELENA;

GRANT ALL ON V_MONEYBACK_BELPOST TO KATYA;

GRANT ALL ON V_MONEYBACK_BELPOST TO LANA;

GRANT ALL ON V_MONEYBACK_BELPOST TO LENA;

GRANT ALL ON V_MONEYBACK_BELPOST TO NASTYA;

GRANT ALL ON V_MONEYBACK_BELPOST TO NASTYA17;

GRANT ALL ON V_MONEYBACK_BELPOST TO NATA;

GRANT ALL ON V_MONEYBACK_BELPOST TO NATVL;

GRANT ALL ON V_MONEYBACK_BELPOST TO ND;

GRANT ALL ON V_MONEYBACK_BELPOST TO OKSANA;

GRANT ALL ON V_MONEYBACK_BELPOST TO PUBLIC;

GRANT ALL ON V_MONEYBACK_BELPOST TO SVETLANA;

GRANT ALL ON V_MONEYBACK_BELPOST TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON V_MONEYBACK_BELPOST TO VALERY;

GRANT ALL ON V_MONEYBACK_BELPOST TO VIKA;

GRANT ALL ON V_MONEYBACK_BELPOST TO YULYA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO ANNA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO CATRIN;

GRANT ALL ON V_ORDERITEMS_RETURNING TO ELENA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO KATYA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO LANA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO LENA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO NASTYA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO NASTYA17;

GRANT ALL ON V_ORDERITEMS_RETURNING TO NATA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO NATVL;

GRANT ALL ON V_ORDERITEMS_RETURNING TO ND;

GRANT ALL ON V_ORDERITEMS_RETURNING TO OKSANA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO PUBLIC;

GRANT ALL ON V_ORDERITEMS_RETURNING TO SVETLANA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON V_ORDERITEMS_RETURNING TO VALERY;

GRANT ALL ON V_ORDERITEMS_RETURNING TO VIKA;

GRANT ALL ON V_ORDERITEMS_RETURNING TO YULYA;

GRANT ALL ON V_ORDERS TO ANNA;

GRANT ALL ON V_ORDERS TO CATRIN;

GRANT ALL ON V_ORDERS TO ELENA;

GRANT ALL ON V_ORDERS TO KATYA;

GRANT ALL ON V_ORDERS TO LANA;

GRANT ALL ON V_ORDERS TO LENA;

GRANT ALL ON V_ORDERS TO NASTYA;

GRANT ALL ON V_ORDERS TO NASTYA17;

GRANT ALL ON V_ORDERS TO NATA;

GRANT ALL ON V_ORDERS TO NATVL;

GRANT ALL ON V_ORDERS TO ND;

GRANT ALL ON V_ORDERS TO OKSANA;

GRANT ALL ON V_ORDERS TO PUBLIC;

GRANT ALL ON V_ORDERS TO SVETLANA;

GRANT ALL ON V_ORDERS TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON V_ORDERS TO USERS WITH GRANT OPTION;

GRANT ALL ON V_ORDERS TO VALERY;

GRANT ALL ON V_ORDERS TO VIKA;

GRANT ALL ON V_ORDERS TO YULYA;


