SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE ACTIONCODE_PARAMS
SET PARAM_VALUE = 'Списание средств на заявку [ANNOTATE]'
WHERE (ACTION_SIGN = 'ACCOUNT_CREDITORDER') AND (PARAM_NAME = 'NOTES') AND (PARAM_KIND = 'V');

UPDATE ACTIONCODE_PARAMS
SET PARAM_VALUE = 'Ручное списание cуммы [AMOUNT_EUR] EUR со счета по курсу [BYR2EUR] ([ANNOTATE])'
WHERE (ACTION_SIGN = 'ACCOUNT_MANUALCREDIT') AND (PARAM_NAME = 'NOTES') AND (PARAM_KIND = 'V');

UPDATE ACTIONCODE_PARAMS
SET PARAM_VALUE = 'Ручное зачисление cуммы [AMOUNT_EUR] EUR на счет по курсу [BYR2EUR] ([ANNOTATE])'
WHERE (ACTION_SIGN = 'ACCOUNT_MANUALDEBIT') AND (PARAM_NAME = 'NOTES') AND (PARAM_KIND = 'V');

UPDATE ACTIONCODE_PARAMS
SET PARAM_VALUE = 'Зачиление платежа [AMOUNT_BYR] BYR по заявке [ORDER_CODE] на сумму [AMOUNT_EUR] по курсу [BYR2EUR] [ANNOTATE]'
WHERE (ACTION_SIGN = 'ACCOUNT_PAYMENTIN') AND (PARAM_NAME = 'NOTES') AND (PARAM_KIND = 'V');



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (30, 'ANNOTATE', 'A', 'ANNOTATE');




INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (207, 'APPENDABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (212, 'BALANCEABLE');



UPDATE TEMPLATES
SET FILENAME_MASK = 'info_[[:DIGIT:]]{8}_[[:DIGIT:]]{5}_2pay_[[:DIGIT:]]{3}.txt'
WHERE (TEMPLATE_ID = 10);



INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (182, 181, 'ORDERITEM_ANULLED');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (183, 181, 'ORDERITEM_ANULLED');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (189, 185, 'ORDERITEM_PACKED');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (207, 209, 'ORDER_ANULLED');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (213, 210, 'ORDER_PACKED');

