SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE, ISSTATE)
  VALUES (280, 'Задержка 1 неделю', 'ORDERITEM', NULL, 'DELAY1WEEK', NULL, NULL, NULL, 1);


INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (280, 'AVAILABLE');

INSERT INTO FLAGS2STATUSES (STATUS_ID, FLAG_SIGN)
  VALUES (280, 'DELAY');


INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '21', 'DELAY1WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 1 Wochen', 'Задержка до 1 недели');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 3 Wochen', 'Задержка до 3 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 6 Wochen', 'Задержка до 6 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 8 Wochen', 'Задержка до 8 недель');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE_RUS', 'Nachlieferung, kommt in 9 Wochen', 'Задержка до 9 недель');


INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (204, 212, 'ORDER_ANULLED');


