SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE ACTIONCODE_PARAMS
SET PARAM_VALUE = 'NULL'
WHERE (ACTION_SIGN = 'ORDERITEM_INDOUBT') AND (PARAM_NAME = 'NEW.STATE_SIGN') AND (PARAM_KIND = 'V');

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_PREPACKED', 'NEW.STATE_SIGN', 'V', 'NULL');


