SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';



INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (175, 185, 'ORDERITEM_PACKED');

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_PACKED'
WHERE (OLD_STATUS_ID = 182) AND (NEW_STATUS_ID = 185);

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (205, 210, 'ORDER_PACKED');



