SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';



INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDER_DELIVERED', 'Заявка доставлена', 'ORDER', 'ORDER_STORE');



INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES ('ORDERITEM_APPROVE', 'STATUS_SIGN', 'S', '=', 'NEW', NULL);

INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES ('ORDERITEM_DELIVERED', 'STATUS_SIGN', 'S', '=', 'DELIVERING', NULL);



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_DELIVERED', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDER_DELIVERED', 'NEW.STATUS_SIGN', 'V', 'DELIVERED');



INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (35, 'ORDER_DELIVERED', 1, 'ORDER_FOREACH_ORDERITEM');



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (35, 'NEW.STATUS_SIGN', 'V', 'DELIVERED');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (35, 'ORDER_ID', 'A', 'ID');



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (926, 'ORDERITEM', 'ORDERITEM_INDEX', 'Позиция в заявке', 'ORDERITEM_INDEX', NULL);



UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 171);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 172);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 173);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 174);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 175);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 178);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 179);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 180);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 181);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 182);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 183);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 184);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 185);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 186);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 187);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 188);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 189);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 201);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 202);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 203);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 204);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 205);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 206);

UPDATE STATUSES
SET FLAG_SIGN_LIST = ',CANCELABLE,',
    ISSTATE = 0
WHERE (STATUS_ID = 207);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 208);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 209);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 210);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 211);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 212);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 213);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 215);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 216);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 217);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 218);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 219);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 253);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 254);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 255);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 256);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 257);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 258);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 259);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 260);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 261);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 262);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 263);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 264);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 265);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 266);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 267);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 268);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 269);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 270);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 271);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 272);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 273);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 274);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 275);

UPDATE STATUSES
SET ISSTATE = 1
WHERE (STATUS_ID = 276);

UPDATE STATUSES
SET ISSTATE = 0
WHERE (STATUS_ID = 279);



UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_DELIVERED'
WHERE (OLD_STATUS_ID = 186) AND (NEW_STATUS_ID = 278);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDER_DELIVERED'
WHERE (OLD_STATUS_ID = 211) AND (NEW_STATUS_ID = 218);



DELETE FROM FLAGS2STATUSES
WHERE (STATUS_ID = 207) AND (FLAG_SIGN = 'APPENDABLE');


