SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_DELIVERED', 'Позиция доставлена', 'ORDERITEM', 'ORDERITEM_STORE');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_DISCARD', 'Брак артикула', 'ORDERITEM', 'ORDERITEM_STORE');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDER_DISCARD', 'Брак в заявке', 'ORDER', 'ORDER_STORE');



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_DELIVERED', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_DELIVERED', 'NEW.STATUS_SIGN', 'V', 'DELIVERED');

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_DISCARD', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_DISCARD', 'NEW.STATUS_SIGN', 'V', 'DISCARDED');

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_RETURN', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_RETURN', 'NEW.STATUS_SIGN', 'V', 'RETURNING');



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (737, 'ORDER', 'STATUS_DTM', 'Дата обновления статуса', 'STATUS_DTM', 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (738, 'ORDER', 'STATUS_NAME', 'Наименование статуса', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (812, 'ORDERTAX', 'STATUS_DTM', 'Дата обновления статуса', 'STATUS_DTM', 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (813, 'ORDERTAX', 'STATUS_NAME', 'Наименование статуса', NULL, 'R');

UPDATE ATTRS
SET FIELD_NAME = 'MAGAZINE_ID',
    DIRECTION = NULL
WHERE (ATTR_ID = 918);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (938, 'ORDERITEM', 'STATUS_DTM', 'Дата обновления статуса ', 'STATUS_DTM', 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (939, 'ORDERITEM', 'STATUS_NAME', 'Наименование статуса', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (940, 'ORDERITEM', 'STATE_NAME', 'Наименование состояния', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (1904, 'ORDERMONEY', 'STATUS_DTM', 'Дата обновления статуса', 'STATUS_DTM', 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (1905, 'ORDERMONEY', 'STATUS_NAME', 'Наименование статуса', NULL, 'R');



UPDATE STATUSES
SET STATUS_NAME = 'Доставлена'
WHERE (STATUS_ID = 218);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (277, 'Брак', 'ORDERITEM', NULL, 'DISCARDED', NULL, NULL, NULL);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (278, 'Доставлен', 'ORDERITEM', NULL, 'DELIVERED', NULL, NULL, NULL);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (279, 'Воврат брака', 'ORDER', NULL, 'DISCARDED', NULL, NULL, NULL);



INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (186, 278, 'ORDERITEM_STORE');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (218, 279, 'ORDER_DISCARD');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (278, 187, 'ORDERITEM_RETURN');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (278, 277, 'ORDERITEM_DISCARD');


DELETE FROM ATTRS
WHERE (ATTR_ID = 724);
DELETE FROM ATTRS
WHERE (ATTR_ID = 725);
DELETE FROM ATTRS
WHERE (ATTR_ID = 726);
DELETE FROM ATTRS
WHERE (ATTR_ID = 727);
DELETE FROM ATTRS
WHERE (ATTR_ID = 728);
DELETE FROM ATTRS
WHERE (ATTR_ID = 729);
DELETE FROM ATTRS
WHERE (ATTR_ID = 922);
DELETE FROM ATTRS
WHERE (ATTR_ID = 923);
DELETE FROM ATTRS
WHERE (ATTR_ID = 924);
DELETE FROM ATTRS
WHERE (ATTR_ID = 925);
DELETE FROM ATTRS
WHERE (ATTR_ID = 926);
DELETE FROM ATTRS
WHERE (ATTR_ID = 927);
DELETE FROM ATTRS
WHERE (ATTR_ID = 928);
DELETE FROM ATTRS
WHERE (ATTR_ID = 929);
DELETE FROM ATTRS
WHERE (ATTR_ID = 930);
DELETE FROM ATTRS
WHERE (ATTR_ID = 931);
DELETE FROM ATTRS
WHERE (ATTR_ID = 932);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1401);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1402);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1403);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1700);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1701);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1702);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1703);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1704);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1705);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1706);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1707);
DELETE FROM ATTRS
WHERE (ATTR_ID = 1708);

