SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_REJECT', 'Отказ по позиции', 'ORDERITEM', 'ORDERITEM_STORE');


INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_REJECT', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_REJECT', 'NEW.STATUS_SIGN', 'V', 'REJECTED');


INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (10, 'ORDERITEM_REJECT', 1, 'ACCOUNT_DEBIT');


INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (10, 'AMOUNT_EUR', 'A', 'PRICE_EUR');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (10, 'ID', 'B', 'ORDER_ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (10, 'ORDERITEM_ID', 'A', 'ID');


INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '0', 'AVAILABLE');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '2', 'DELAY');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '22', 'DELAY2WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '23', 'DELAY3WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '24', 'DELAY4WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '25', 'DELAY5WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '26', 'DELAY6WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '27', 'DELAY7WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '28', 'DELAY8WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '29', 'DELAY9WEEK');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '3', 'REJECTED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '5', 'REJECTED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_CODE_TIME', '7', 'REJECTED');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('ORDERITEM', 'DELIVERY_MESSAGE', 'Nachlieferung', 'DELAY');

DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '0');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '2');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '22');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '23');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '24');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '25');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '26');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '27');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '28');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '29');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '3');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '5');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_CODE_TIME') AND (ORIGINAL_VALUE = '7');
DELETE FROM RECODES
WHERE (OBJECT_SIGN = 'ARTICLE') AND (ATTR_SIGN = 'DELIVERY_MESSAGE') AND (ORIGINAL_VALUE = 'Nachlieferung');

