SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE TAXRATES
SET TAXSERV_ID = 3
WHERE (TAXRATE_ID = 2);

UPDATE TAXRATES
SET TAXSERV_ID = 3
WHERE (TAXRATE_ID = 4);


INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (2, 1304, '3000');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (4, 1304, '3000');


