SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_DELIVERING', 'Установить статус отправлено в Вильнюс', 'ORDERITEM', 'ORDERITEM_STORE');



INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_DELIVERING', 'ID', 'I', NULL);

INSERT INTO ACTIONCODE_PARAMS (ACTION_SIGN, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES ('ORDERITEM_DELIVERING', 'NEW.STATUS_SIGN', 'V', 'DELIVERING');



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (722, 'ORDER', 'ITEMSCOST_EUR', 'Стоимость артикулов', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (723, 'ORDER', 'BAR_CODE', 'Сигнатура посылки', 'BAR_CODE', NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (724, 'ORDER', 'DTM.APPROVED', 'Дата оформления', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (725, 'ORDER', 'DTM.ACCEPTREQUEST', 'Дата отправки в Германию', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (726, 'ORDER', 'DTM.ACCEPTED', 'Дата принятия заявки', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (727, 'ORDER', 'DTM.PAID', 'Дата поступления оплаты', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (728, 'ORDER', 'DTM.PACKED', 'Дата обработки паклиста', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (729, 'ORDER', 'DTM.DELIVERING', 'Дата отправки информации в Вильнюс', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (927, 'ORDERITEM', 'DTM.CANCELLED', 'Дата ануляции ', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (928, 'ORDERITEM', 'DTM.BUNDLING', 'Дата комрлектации', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (929, 'ORDERITEM', 'DTM.PACKED', 'Дата паклиста', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (930, 'ORDERITEM', 'DTM.DELIVERING', 'Дата отпрвки информации в Вильнюс', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (931, 'ORDERITEM', 'DTM.NEW', 'Дата создания позиции', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (932, 'ORDERITEM', 'DTM.APPROVED', 'Дата оформления позиции', NULL, NULL);



UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 171);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 172);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 174);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 180);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 183);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 184);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 185);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 186);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 207);

UPDATE STATUSES
SET STORE_DATE = 1
WHERE (STATUS_ID = 211);


UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_DELIVERING'
WHERE (OLD_STATUS_ID = 185) AND (NEW_STATUS_ID = 186);

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDER_DELIVERING'
WHERE (OLD_STATUS_ID = 210) AND (NEW_STATUS_ID = 211);


INSERT INTO TEMPLATES (TEMPLATE_ID, FILENAME_MASK, PLUGIN_NAME)
  VALUES (9, 'Info_[[:DIGIT:]]{8}_artn[[:DIGIT:]]{3}.txt', 'ArtN');


