SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE OBJECTS
SET PROCEDURE_READ = 'PLACE_READ'
WHERE (OBJECT_SIGN = 'PLACE');


INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (503, 'PLACE', 'AREA_NAME', 'Район', NULL, 'R');

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (504, 'PLACE', 'REGION_NAME', 'Область', NULL, 'R');



