SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE PRODUCTS
SET STATUS_DTM = '1-FEB-2012 14:31:29'
WHERE (PRODUCT_ID = 2);


COMMIT WORK;

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (180, 185, 'ORDERITEM_PACKED');


COMMIT WORK;

UPDATE TAXPLANS
SET STATUS_DTM = '1-NOV-2011 11:29:13'
WHERE (TAXPLAN_ID = 1);

UPDATE TAXPLANS
SET STATUS_DTM = '1-NOV-2011 11:29:13'
WHERE (TAXPLAN_ID = 2);

UPDATE TAXPLANS
SET STATUS_DTM = '1-NOV-2011 11:29:13'
WHERE (TAXPLAN_ID = 3);

UPDATE TAXPLANS
SET STATUS_DTM = '1-NOV-2011 11:29:13'
WHERE (TAXPLAN_ID = 4);


COMMIT WORK;

UPDATE TEMPLATES
SET PLUGIN_NAME = 'order'
WHERE (TEMPLATE_ID = 1);


COMMIT WORK;

