SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERITEM_RETURN', 'Возврат позиции', 'ORDERITEM', 'ORDERITEM_STORE');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDERTAX_RETURN', 'Комиссия за возврат', 'ORDERTAX', 'ORDERTAX_STORE');

INSERT INTO ACTIONCODES (ACTION_SIGN, ACTION_NAME, OBJECT_SIGN, PROCEDURE_NAME)
  VALUES ('ORDER_HAVERETURN', 'Возврат по заявке', 'ORDER', 'ORDER_STORE');


COMMIT WORK;

INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (61, 'ORDER_HAVERETURN', 1, 'ORDER_FOREACH_TAXRATE');

INSERT INTO ACTIONTREE (ACTIONTREEITEM_ID, ACTION_SIGN, ORDER_NO, CHILD_ACTION)
  VALUES (62, 'ORDER_HAVERETURN', 2, 'ACCOUNT_DEBITORDER');


COMMIT WORK;

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (61, 'ORDER_ID', 'A', 'ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (62, 'AMOUNT_EUR', 'F', 'select coalesce(sum(om.amount_eur), 0) from ordermoneys om where om.order_id = [ID]');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (62, 'ID', 'A', 'ACCOUNT_ID');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (62, 'ORDER_ID', 'A', 'ID');


COMMIT WORK;

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (308, 'CLIENT', 'PERSONAL_NUM', 'Личный номер', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (309, 'CLIENT', 'PASSPORT_NUM', 'Номер паспорта', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (310, 'CLIENT', 'PASSPORT_ISSUED', 'Дата выдачи паспорта', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (311, 'CLIENT', 'PASSPORT_ISSUER', 'Орган выдавший паспорт', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (312, 'CLIENT', 'BANK_ACCOUNT_NUM', '13-значный счет в банке', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (313, 'CLIENT', 'BANK_NAME', 'Наименование банка', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (314, 'CLIENT', 'BANK_CLIENT_ACCOUNT', 'Счет клиента', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (315, 'CLIENT', 'BANK_MFO', 'МФО банка', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (316, 'CLIENT', 'BANK_UNP', 'УНП банка', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (735, 'ORDER', 'MONEYBACK_KIND', 'Способ возврата денег', NULL, NULL);

INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (736, 'ORDER', 'BELPOST_BAR_CODE', 'Код посылки БелПочты', NULL, NULL);


COMMIT WORK;

UPDATE STATUSES
SET FLAG_SIGN_LIST = NULL
WHERE (STATUS_ID = 187);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (215, 'Возрат доставлен Германию', 'ORDER', NULL, 'RETURNED', NULL, NULL, NULL);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (216, 'Завершен', 'ORDER', NULL, 'CLOSED', NULL, NULL, NULL);

INSERT INTO STATUSES (STATUS_ID, STATUS_NAME, OBJECT_SIGN, IS_DEFAULT, STATUS_SIGN, ACTION_SIGN, FLAG_SIGN_LIST, STORE_DATE)
  VALUES (217, 'Возврат по заявке', 'ORDER', NULL, 'HAVERETURN', NULL, NULL, NULL);


COMMIT WORK;

INSERT INTO CALCPOINTS (CALCPOINT_ID, OBJECT_SIGN, OBJECT_STATUS_ID)
  VALUES (3, 'ORDER', 217);


COMMIT WORK;

UPDATE STATUS_RULES
SET ACTION_SIGN = 'ORDERITEM_RETURN'
WHERE (OLD_STATUS_ID = 186) AND (NEW_STATUS_ID = 187);

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (211, 217, 'ORDER_HAVERETURN');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (218, 216, 'ORDER_STATUS');

INSERT INTO STATUS_RULES (OLD_STATUS_ID, NEW_STATUS_ID, ACTION_SIGN)
  VALUES (218, 217, 'ORDER_HAVERETURN');


COMMIT WORK;


INSERT INTO TAXSERVS (TAXSERV_ID, TAXSERV_NAME, STATUS_ID, CALCPOINT_ID)
  VALUES (4, 'Плата за возврат', 121, 3);


COMMIT WORK;

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (9, 4, 3, 'TAX_FIXED_SUM', 131);

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (10, 4, 4, 'TAX_FIXED_SUM', 131);

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (11, 4, 1, 'TAX_FIXED_SUM', 131);

INSERT INTO TAXRATES (TAXRATE_ID, TAXSERV_ID, TAXPLAN_ID, TAX_PROCEDURE, STATUS_ID)
  VALUES (12, 4, 2, 'TAX_FIXED_SUM', 131);


COMMIT WORK;

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (9, 1301, '3');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (10, 1301, '3');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (11, 1301, '3');

INSERT INTO TAXRATE_ATTRS (OBJECT_ID, ATTR_ID, ATTR_VALUE)
  VALUES (12, 1301, '3');


COMMIT WORK;

DELETE FROM FLAGS2STATUSES
WHERE (STATUS_ID = 187) AND (FLAG_SIGN = 'CREDIT');

COMMIT WORK;

