SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


UPDATE ACTIONTREE
SET ACTION_SIGN = 'CLIENT_CREATE'
WHERE (ACTIONTREEITEM_ID = 9);



INSERT INTO ACTIONTREE_CRITERIAS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES (65, 'KIND', 'S', '<>', 'LEAVE', NULL);



INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (62, 'NOTES', 'V', 'Зачисление средств по возврату с заявки [ORDER_CODE]');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (65, 'KIND', 'A', 'KIND');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (65, 'KIND_NAME', 'A', 'KIND_NAME');

INSERT INTO ACTIONTREE_PARAMS (ACTIONTREEITEM_ID, PARAM_NAME, PARAM_KIND, PARAM_VALUE)
  VALUES (65, 'NOTES', 'V', 'Отправка средств клиенту [KIND_NAME]');



INSERT INTO ATTRS (ATTR_ID, OBJECT_SIGN, ATTR_SIGN, ATTR_NAME, FIELD_NAME, DIRECTION)
  VALUES (1407, 'MONEYBACK', 'KIND_NAME', 'Наименование типа возврата', NULL, 'R');



INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('MONEYBACK', 'KIND', 'BANK', 'Банковским переводом');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('MONEYBACK', 'KIND', 'BELPOST', 'Почтовым переводом');

INSERT INTO RECODES (OBJECT_SIGN, ATTR_SIGN, ORIGINAL_VALUE, RECODED_VALUE)
  VALUES ('MONEYBACK', 'KIND', 'LEAVE', 'Оставить на счете');



