SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB 'fbclient.dll';


INSERT INTO ACTIONCODE_CRITERIAS (ACTIONCODE_SIGN, PARAM_NAME, PARAM_KIND, PARAM_ACTION, PARAM_VALUE_1, PARAM_VALUE_2)
  VALUES ('ORDERITEM_INDOUBT', 'STATUS_SIGN', 'S', 'IN', 'ACCEPTED,PREPAKED', NULL);


DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 72) AND (PARAM_NAME = 'NEW.STATUS_SIGN') AND (PARAM_KIND = 'V');
DELETE FROM ACTIONTREE_PARAMS
WHERE (ACTIONTREEITEM_ID = 72) AND (PARAM_NAME = 'ORDER_ID') AND (PARAM_KIND = 'A');

DELETE FROM ACTIONTREE_CRITERIAS
WHERE (ACTIONTREEITEM_ID = 71) AND (PARAM_NAME = 'STATUS_SIGN');
DELETE FROM ACTIONTREE_CRITERIAS
WHERE (ACTIONTREEITEM_ID = 72) AND (PARAM_NAME = 'STATUS_SIGN');


DELETE FROM ACTIONTREE
WHERE (ACTIONTREEITEM_ID = 72);

