
DECLARE EXTERNAL FUNCTION COPYFRONT_WITHKEY
    CSTRING(4000),
    CSTRING(20)
RETURNS CSTRING(4000) FREE_IT
ENTRY_POINT 'CopyFront_WithKey_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION COPYFRONT_WITHOUTKEY
    CSTRING(4000),
    CSTRING(20)
RETURNS CSTRING(4000) FREE_IT
ENTRY_POINT 'CopyFront_WithOutKey_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION COPY_START_END
    CSTRING(4000),
    CSTRING(20),
    CSTRING(20),
    INTEGER,
    INTEGER
RETURNS CSTRING(4000) FREE_IT
ENTRY_POINT 'Copy_Start_End_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION COPY_BETWEEN
    CSTRING(4000),
    CSTRING(20),
    CSTRING(20),
    INTEGER,
    INTEGER
RETURNS CSTRING(4000) FREE_IT
ENTRY_POINT 'Copy_Between_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION RECODE_UTF8
    CSTRING(4000),
    CSTRING(4000)
RETURNS CSTRING(4000) FREE_IT
ENTRY_POINT 'Recode_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION RECODE
    CSTRING(4000),
    CSTRING(4000)
RETURNS CSTRING(4000) FREE_IT
ENTRY_POINT 'Recode_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION CHARCOUNT
    CSTRING(4000),
    CSTRING(1)
RETURNS INTEGER BY VALUE FREE_IT
ENTRY_POINT 'CharCount_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION ESCAPESTRING
    CSTRING(4000)
RETURNS CSTRING(4000) FREE_IT
ENTRY_POINT 'EscapeString_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION UNESCAPESTRING
    CSTRING(4000)
RETURNS CSTRING(4000) FREE_IT
ENTRY_POINT 'UnEscapeString_UTF8' MODULE_NAME 'GvUDF.DLL';

DECLARE EXTERNAL FUNCTION STRLEN
    CSTRING(4000)
RETURNS INTEGER BY VALUE 
ENTRY_POINT 'StrLen_UTF8' MODULE_NAME 'GvUDF.DLL';
