      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;">
                <a href="http://otto-moda.by/catalogs/swf/avendro_ru/ss2012/index.html" title="Avendro" target="_blank"><img src="http://otto-moda.by/catalogs/swf/avendro_ru/ss2012/images/page1_thumbnail.jpg" alt="Avendro" width="110" height="134" border="0"></a>
              </div>
              <div class="catalogIconBar">
                <a href="http://otto-moda.by/catalogs/swf/avendro_ru/ss2012/index.html" title="Смотреть" target="_blank"><img src="assets/otto-by/images/icons/small/icon_browse.gif" width=30 height="23" alt="Смотреть"/></a>
                <a href="http://otto-moda.by/catalogs/swf/avendro_ru/ss2012/files/avendro_ru_ss2012.pdf" title="Скачать"><img src="assets/otto-by/images/icons/small/icon_download.gif" width=30 height="23" alt="Скачать"/></a>
                <!--img src="assets/otto-by/images/icons/small/scheme1/order.gif" width=30 height="23" alt="Заказать"/-->
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>Avendro</b>
            <p>Новинка имя среди каталогов OTTO.</p>
            <p>На русском языке</p>
          </div>
        </div>
      </div>
