      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;"><a href="http://otto-moda.by/catalogs/swf/heine_mix/fs2012/index.html" title="Alba Moda" target="_blank"><img src="assets/otto-by/images/catalogs2012_02/heine_mix_fs2012.jpg" alt="Heine Mix" width="102" height="125" border="0"/></a>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>Heine Mix</b>
            <p>&quot;Heine&quot; - это всегда благородный дизайн, тщательный подбор и высокое качество материалов, 
               изысканный стиль, элегантность и утончённость.</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p><a href="http://otto-moda.by/catalogs/swf/heine_mix/fs2012/index.html" target="_blank">Посмотреть</a>, <a href="http://otto-moda.by/catalogs/pdf/heine_mix_fs2012.pdf" target="_blank">Скачать</a>, <a href="">Заказать</a>
          </div>
        </div>
      </div>

