      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;">
                <a href="http://otto-moda.by/catalogs/swf/creation_l_ru/fs2013/index.html" title="Creation L" target="_blank"><img src="http://otto-moda.by/catalogs/swf/creation_l_ru/fs2013/images/page1_thumbnail.jpg" alt="Creation L" width="110" height="134" border="0"/></a>
              </div>
              <div class="catalogIconBar">
                <a href="http://otto-moda.by/catalogs/swf/creation_l_ru/fs2013/index.html" title="Смотреть" target="_blank"><img src="assets/otto-by/images/icons/small/icon_browse.gif" width=30 height="23" alt="Смотреть"/></a>
                <a href="http://otto-moda.by/catalogs/swf/creation_l_ru/fs2013/files/creation_l_ru_fs2013.pdf" title="Скачать"><img src="assets/otto-by/images/icons/small/icon_download.gif" width=30 height="23" alt="Скачать"/></a>
                <a href="http://оttokatalogi.by" title="Заказать" target="new"><img src="assets/otto-by/images/icons/small/icon_order.gif" width=30 height="23" alt="Заказать"/></a>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>Creation L</b>
            <p>В каталоге представлены различные коллекции модной актуальной верхней женской одежды, обуви, 
               аксессуаров. Непринужденная классика, бизнес-стиль, одежда для праздничных моментов, одежда для 
               отдыха и др.</p>
          </div>
        </div>
      </div>
