      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;"><a href="http://otto-moda.by/catalogs/swf/creation_l/fs2012/index.html" title="Alba Moda" target="_blank"><img src="assets/otto-by/images/catalogs2012_02/creation_l_fs2012.jpg" alt="Creation L" width="102" height="125" border="0"/></a>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>Creation L</b>
            <p>В каталоге представлены различные коллекции модной актуальной верхней женской одежды, обуви, 
               аксессуаров. Непринужденная классика, бизнес-стиль, одежда для праздничных моментов, одежда для 
               отдыха и др.</p>
            <p>&nbsp;</p>
            <p><a href="http://otto-moda.by/catalogs/swf/creation_l/fs2012/index.html" target="_blank">Посмотреть</a>, <a href="http://otto-moda.by/catalogs/pdf/creation_l_fs2012.pdf" target="_blank">Скачать</a>, <a href="">Заказать</a>
          </div>
        </div>
      </div>
