      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;"><a href="http://otto-moda.by/catalogs/swf/otto_ru/fs2012/index.html" title="ОТТО каталог" target="_blank"><img src="/assets/otto-by/images/catalogs2012_02/otto_ru_fs2012.jpg" alt="OTTO-Katalog" width="102" height="125" border="0"></a>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>OTTO-Katalog</b>
            <p>Основной каталог ОТТО Весна/Лето 2012.  И на каждой странице столько всего, и какого качества!... 
               Лучшие фирмы мира размещают свои товары  в каталогах OTTO, понимая, что этим они размещают 
               информацию о товаре по всему миру.</p>
            <p><a href="http://otto-moda.by/catalogs/swf/otto_ru/fs2012/index.html" title="ОТТО каталог" target="_blank">Посмотреть</a>, <a href="http://otto-moda.by/catalogs/pdf/otto_ru_fs2012.pdf" alter=""><a href="">Заказать</a>.
          </div>
        </div>
      </div>
