      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <p><div class="content" style="background-color:#fff;margin:1px 0 0 1px;"><a href="http://www.otto.de/is-bin/INTERSHOP.enfinity/WFS/Otto-OttoDe-Site/de_DE/-/EUR/OV_ViewTemplate-View?Template=popups/blaetterbarer_katalog&CatalogPage=1&ls=0&BlaetterbarerKatalog=sbi1_125" title="So Bin Ich" target="_blank"><img src="assets/otto-by/images/catalogs2012_02/so_bin_ich_fs2012.jpg" alt="So Bin Ich" width="102" height="125" border="0"/></a></p>
              <p><font size="1">&nbsp;</font></p>
              <p><a href="http://www.otto.de/is-bin/INTERSHOP.enfinity/WFS/Otto-OttoDe-Site/de_DE/-/EUR/OV_ViewTemplate-View?Template=popups/blaetterbarer_katalog&CatalogPage=1&ls=0&BlaetterbarerKatalog=sbi1_125" title="Смотреть" target="_blank"><img src="assets/otto-by/images/icons/small/scheme1/browse.gif" width=30 height="23" alt="Смотреть"/></a>
                 <img src="assets/otto-by/images/icons/small/scheme1/download.gif" width=30 height="23" alt="Скачать"/>
                 <img src="assets/otto-by/images/icons/small/scheme1/order.gif" width=30 height="23" alt="Заказать"/>
              </p>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>So Bin Ich</b>
            <p>На немецком языке.</p>
          </div>
        </div>
      </div>
