      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;"><a href="http://otto-moda.by/catalogs/swf/sheego/fs2012/index.html" title="Sheego" target="_blank"><img src="assets/otto-by/images/catalogs2012_02/sheego_fs2012.jpg" alt="Sheego" width="102" height="125" border="0"/></a>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>Sheego</b>
            <p>Каталог больших размеров. Новые модные идеи, актуальные тенденции и изысканная классика - разнообразие 
               Вам обеспечено! Но и любительниц известных марок, фанаток эксклюзивной обуви и сумочек ожидает 
               большое количество новинок.</p>
            <p><a href="http://otto-moda.by/catalogs/swf/sheego/fs2012/index.html" target="_blank">Посмотреть</a>, <a href="http://otto-moda.by/catalogs/pdf/sheego_fs2012.pdf" target="_blank">Скачать</a>, <a href="">Заказать</a>
          </div>
        </div>
      </div>
