      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;"><a href="http://www.otto.de/is-bin/INTERSHOP.enfinity/WFS/Otto-OttoDe-Site/de_DE/-/EUR/OV_ViewTemplate-View?Template=popups/blaetterbarer_katalog&CatalogPage=1&ls=0&BlaetterbarerKatalog=sbi2_124#lmPromo=la,3,hk,sh10972461,fl,Z1_S1_TTMI_Special" title="So Bin Ich" target="_blank"><img src="/assets/otto-by/images/catalogs2012_02/so_bin_ich_fs2012.jpg" alt="So Bin Ich" width="102" height="125" border="0"/></a>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>So Bin Ich</b>
            <p>Вы  можете найти и подобрать себе одежду, смоделированную специально для нестандартных фигур. 
               So Bin Ich&nbsp;- смело, дерзко, симпатично. Огромный выбор моделей больших размеров. 
               Стиль - от спортивного до элегантного.</p>
            <p>На немецком языке.</p>
            <p><a href="http://www.otto.de/is-bin/INTERSHOP.enfinity/WFS/Otto-OttoDe-Site/de_DE/-/EUR/OV_ViewTemplate-View?Template=popups/blaetterbarer_katalog&CatalogPage=1&ls=0&BlaetterbarerKatalog=sbi2_124#lmPromo=la,3,hk,sh10972461,fl,Z1_S1_TTMI_Special" target="_blank">Посмотреть</a>, <a href="">Заказать</a>
          </div>
        </div>
      </div>
