      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;"><a href="http://otto-moda.by/catalogs/swf/venca/fs2012/index.html" title="Venca" target="_blank"><img src="assets/otto-by/images/catalogs2012_02/venca_fs2012.jpg" alt="Venca" width="102" height="125" border="0"/></a>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>Venca</b>
            <p>Каталог испанской моды. Яркие, стильные и сексуальные модели женской и мужской одежды, аксессуаров, 
               средств по уходу за телом, нижнего белья. Цены в этом каталоге вас приятно удивят.</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p><a href="http://otto-moda.by/catalogs/swf/venca/fs2012/index.html" target="_blank">Посмотреть</a>, <a href="http://otto-moda.by/catalogs/pdf/venca_fs2012.pdf" target="_blank">Скачать</a>, <a href="">Заказать</a>
          </div>
        </div>
      </div>
