      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;">
                <a href="http://otto-moda.by/catalogs/swf/sheego_ru/ss2012/index.html" title="Creation L" target="_blank"><img src="http://otto-moda.by/catalogs/swf/sheego_ru/ss2012/images/page1_thumbnail.jpg" alt="Sheego" width="110" height="134" border="0"/></a>
              </div>
              <div class="catalogIconBar">
                <a href="http://otto-moda.by/catalogs/swf/sheego_ru/ss2012/index.html" title="Смотреть" target="_blank"><img src="assets/otto-by/images/icons/small/icon_browse.gif" width=30 height="23" alt="Смотреть"/></a>
                <a href="http://otto-moda.by/catalogs/swf/sheego_ru/ss2012/files/sheego_ru_ss2012.pdf" title="Скачать"><img src="assets/otto-by/images/icons/small/icon_download.gif" width=30 height="23" alt="Скачать"/></a>
                <!--img src="assets/otto-by/images/icons/small/scheme1/order.gif" width=30 height="23" alt="Заказать"/-->
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>Sheego</b>
            <p>Каталог больших размеров. Новые модные идеи, актуальные тенденции и изысканная классика - разнообразие 
               Вам обеспечено! Но и любительниц известных марок, фанаток эксклюзивной обуви и сумочек ожидает 
               большое количество новинок.</p>
          </div>
        </div>
      </div>
