      <div class="downloadBox">
        <table class="imageWrapper"><tbody>
          <tr>
            <td>
              <div class="content" style="background-color:#fff;margin:1px 0 0 1px;">
                <a href="http://otto-moda.by/catalogs/swf/otto_ru/fs2013/index.html" title="ОТТО каталог" target="_blank"><img src="http://otto-moda.by/catalogs/swf/otto_ru/fs2013/images/page1_thumbnail.jpg" alt="OTTO-Katalog" width="110" height="134" border="0"></a>
              </div>
              <div class="catalogIconBar">
                <a href="http://otto-moda.by/catalogs/swf/otto_ru/fs2013/index.html" title="Смотреть" target="_blank"><img src="assets/otto-by/images/icons/small/icon_browse.gif" width=30 height="23" alt="Смотреть"/></a>
                <a href="http://otto-moda.by/catalogs/swf/otto_ru/fs2013/files/otto_ru_fs2013.pdf" title="Скачать"><img src="assets/otto-by/images/icons/small/icon_download.gif" width=30 height="23" alt="Скачать"/></a>
                <a href="http://оttokatalogi.by" title="Заказать" target="new"><img src="assets/otto-by/images/icons/small/icon_order.gif" width=30 height="23" alt="Заказать"/></a>
              </div>
            </td>
          </tr>
        </tbody></table>
        <div class="text">
          <div class="inner">
            <b>OTTO-Katalog</b>
            <p>Основной каталог ОТТО Весна-Лето 2013. И на каждой странице столько всего, и какого качества!... 
               Лучшие фирмы мира размещают свои товары  в каталогах OTTO, понимая, что этим они размещают 
               информацию о товаре по всему миру.</p>
            <p>На русском языке</p>
          </div>
        </div>
      </div>
